"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import "../roadmap.css";

type Project={id:number;project_code:string;name_ar:string;planned_year:number;planned_quarter:string;status:"planned"|"in_progress"|"on_hold"|"completed";priority:"high"|"medium"|"low";progress_percent:number;executive_owner:string|null;target_outcome:string|null;recommended_technologies:string|null};
type LinkRow={project_id:number;control_id:number;controls:{frameworks:{code:string}|{code:string}[]|null}|null};
type Treatment={project_id:number;gap_title:string;treatment_type:"technology"|"procedure"|"policy"|"training";priority:"high"|"medium"|"low"};
const statusText={planned:"مخطط",in_progress:"قيد التنفيذ",on_hold:"متوقف",completed:"مكتمل"};
const treatmentText={technology:"تقنيات",procedure:"إجراءات",policy:"سياسات",training:"تدريب"};
const frameworkOf=(value:LinkRow["controls"])=>{const f=value?.frameworks;return Array.isArray(f)?f[0]:f};

export default function RoadmapDashboard(){
 const router=useRouter();const [projects,setProjects]=useState<Project[]>([]);const [links,setLinks]=useState<LinkRow[]>([]);const [treatments,setTreatments]=useState<Treatment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{try{await requireProfile();const [p,l,t]=await Promise.all([supabase.from("cybersecurity_projects").select("id,project_code,name_ar,planned_year,planned_quarter,status,priority,progress_percent,executive_owner,target_outcome,recommended_technologies").order("planned_year").order("planned_quarter"),supabase.from("cybersecurity_project_controls").select("project_id,control_id,controls(frameworks(code))"),supabase.from("cybersecurity_project_gap_treatments").select("project_id,gap_title,treatment_type,priority")]);if(p.error)throw p.error;if(l.error)throw l.error;if(t.error)throw t.error;if(live){setProjects((p.data??[]) as Project[]);setLinks((l.data??[]) as unknown as LinkRow[]);setTreatments((t.data??[]) as Treatment[]);}}catch(e){if(live){const message=e instanceof Error?e.message:"تعذر تحميل لوحة خارطة الطريق.";if(message.includes("تسجيل الدخول")){router.replace("/login");return;}setError(message);}}finally{if(live)setLoading(false);}})();return()=>{live=false};},[router]);
 const totals=useMemo(()=>{const active=projects.filter(p=>p.status==="in_progress").length;const complete=projects.filter(p=>p.status==="completed").length;const average=projects.length?Math.round(projects.reduce((sum,p)=>sum+Number(p.progress_percent||0),0)/projects.length):0;return{active,complete,average,controls:new Set(links.map(l=>l.control_id)).size,highGaps:treatments.filter(t=>t.priority==="high").length};},[projects,links,treatments]);
 const years=useMemo(()=>[2027,2028,2029].map(year=>{const items=projects.filter(p=>p.planned_year===year);return{year,items,progress:items.length?Math.round(items.reduce((sum,p)=>sum+Number(p.progress_percent||0),0)/items.length):0,high:items.filter(p=>p.priority==="high").length};}),[projects]);
 const frameworkCoverage=useMemo(()=>{const map=new Map<string,Set<number>>();links.forEach(link=>{const code=frameworkOf(link.controls)?.code||"غير مصنف";if(!map.has(code))map.set(code,new Set());map.get(code)?.add(link.control_id)});return[...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([code,ids])=>({code,count:ids.size}));},[links]);
 const topGaps=useMemo(()=>treatments.filter(t=>t.priority==="high").slice(0,6),[treatments]);
 if(loading)return <main className="roadmap-page" dir="rtl"><p className="roadmap-loading">جاري تحميل لوحة خارطة الطريق…</p></main>;
 return <main className="roadmap-page roadmap-executive" dir="rtl"><section className="roadmap-shell"><nav className="roadmap-view-tabs" aria-label="عرض خارطة الطريق"><Link href="/roadmap">سجل المشاريع</Link><Link className="active" href="/roadmap/dashboard">لوحة خارطة الطريق</Link></nav><header className="roadmap-exec-hero"><div><span>لوحة تنفيذية · 2027–2029</span><h1>محفظة التحول السيبراني</h1><p>رؤية موحدة للأولويات الاستثمارية، تقدم التنفيذ، والفجوات التي تتطلب قرارًا إداريًا.</p></div><Link href="/roadmap" className="roadmap-primary">إدارة المشاريع ←</Link></header>{error&&<p className="roadmap-alert">{error}</p>}
 <section className="roadmap-exec-kpis"><Kpi label="المبادرات الاستراتيجية" value={projects.length} detail="ضمن خطة السنوات الثلاث"/><Kpi label="متوسط تقدم المحفظة" value={totals.average+"%"} detail="محسوب من نسبة إنجاز المبادرات" tone="teal"/><Kpi label="فجوات عالية الأولوية" value={totals.highGaps} detail="تحتاج قرارًا أو تمويلًا" tone="amber"/><Kpi label="ضوابط مرتبطة" value={totals.controls} detail="مرتبطة بخطة إغلاق" tone="blue"/></section>
 <section className="roadmap-exec-grid"><article className="roadmap-exec-card roadmap-year-plan"><header><div><span>خطة التنفيذ</span><h2>التدرج السنوي</h2></div><small>{totals.active} قيد التنفيذ · {totals.complete} مكتمل</small></header><div className="roadmap-year-bars">{years.map(item=><article key={item.year}><div><b>{item.year}</b><span>{item.items.length} مبادرة · {item.high} عالية</span></div><div className="roadmap-bar"><i style={{width:item.progress+"%"}}/></div><strong>{item.progress}%</strong><ol>{item.items.map(project=><li key={project.id}><span className={"roadmap-dot "+project.status}/><b dir="ltr">{project.project_code}</b><span>{project.name_ar}</span><small>{statusText[project.status]}</small></li>)}</ol></article>)}</div></article>
 <article className="roadmap-exec-card roadmap-decision-card"><span>القرار التنفيذي التالي</span><h2>{topGaps.length?"اعتماد أولويات إغلاق الفجوات":"لا توجد فجوات عالية مسجلة"}</h2><p>{topGaps.length?`لديك ${topGaps.length} فجوات عالية الأولوية مرتبطة بالمبادرات؛ استخدم السجل لتعيين المالك والموعد وربط الضوابط.`:"سجل الفجوات محدث."}</p><Link href="/roadmap">فتح سجل المشاريع ←</Link></article>
 <article className="roadmap-exec-card"><header><div><span>مواءمة الأطر</span><h2>التغطية المخططة</h2></div></header><div className="roadmap-framework-bars">{frameworkCoverage.length?frameworkCoverage.map(item=><div key={item.code}><b dir="ltr">{item.code}</b><i style={{width:Math.min(100,Math.max(8,item.count*4))+"%"}}/><span>{item.count} ضوابط</span></div>):<p>لم تربط ضوابط بالمشاريع بعد.</p>}</div></article>
 <article className="roadmap-exec-card roadmap-gap-card"><header><div><span>أعلى الفجوات</span><h2>أولويات المعالجة</h2></div><Link href="/roadmap">عرض الكل ←</Link></header>{topGaps.length?<ul>{topGaps.map((gap,index)=><li key={index}><span>{treatmentText[gap.treatment_type]}</span><b>{gap.gap_title}</b><small>عالية</small></li>)}</ul>:<p>لا توجد فجوات عالية الأولوية.</p>}</article></section>
 </section></main>;
}
function Kpi({label,value,detail,tone=""}:{label:string;value:string|number;detail:string;tone?:string}){return <article className={"roadmap-exec-kpi "+tone}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
