"use client";

import { WorkflowHeading, WorkflowMetric as Kpi, ResultSummary } from "@/components/WorkflowUI";
import StatusBadge from "@/components/StatusBadge";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { requireProfile, type UserRole } from "@/lib/auth";
import { frameworkOf } from "@/lib/compliance";

type ControlTask = { id:number; control_code:string; title_ar:string; domain_ar:string; implementation_status:string; evidence_status:string; verification_status:string; due_date:string|null; control_owner_id:string|null; control_owner:string|null; frameworks:unknown };

export default function TasksPage(){
  const router=useRouter(); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [role,setRole]=useState<UserRole>("control_owner"); const [tasks,setTasks]=useState<ControlTask[]>([]); const [search,setSearch]=useState(""); const [filter,setFilter]=useState("pending"); const [framework,setFramework]=useState("all"); const [page,setPage]=useState(1); const pageSize=25;
  useEffect(()=>{ let active=true; async function load(){ try {
    const {user,profile}=await requireProfile(); if(!active)return; setRole(profile.role);
    const params=new URLSearchParams(window.location.search); const initialFilter=params.get("filter"); if(initialFilter&&["all","overdue","evidence","done","progress","pending","unassigned","due"].includes(initialFilter))setFilter(initialFilter); setFramework(params.get("framework")||"all");
    let query=supabase.from("controls").select("id,control_code,title_ar,domain_ar,implementation_status,evidence_status,verification_status,due_date,control_owner_id,control_owner,frameworks!inner(code,name_ar)").order("due_date",{ascending:true,nullsFirst:false});
    if(profile.role==="control_owner") query=query.eq("control_owner_id",user.id);
    const {data,error:controlsError}=await query; if(controlsError)throw controlsError; if(active)setTasks((data??[]) as ControlTask[]);
  } catch(loadError){ if(!active)return; const message=loadError instanceof Error?loadError.message:"تعذر تحميل التكليفات"; if(message.includes("تسجيل الدخول")){router.replace("/login");return;} setError(message); } finally {if(active)setLoading(false);} }
    load(); return()=>{active=false;}; },[router]);
  const frameworks=useMemo(()=>[...new Set(tasks.map(t=>frameworkOf(t.frameworks).code))].filter(code=>code!=="—").sort(),[tasks]);
  const filtered=useMemo(()=>tasks.filter(t=>{const q=search.trim().toLowerCase();const f=frameworkOf(t.frameworks);const matchesSearch=!q||`${f.code} ${t.control_code} ${t.title_ar} ${t.domain_ar} ${t.control_owner||""}`.toLowerCase().includes(q);const normalized=(t.implementation_status||"").toLowerCase();const matchesFilter=filter==="all"||(filter==="overdue"&&!!t.due_date&&t.due_date<new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Riyadh"})&&!["implemented","compliant"].includes(normalized))||(filter==="evidence"&&!["uploaded","pending_review","under_review","accepted","approved","verified"].includes(t.evidence_status))||(filter==="done"&&["implemented","compliant"].includes(normalized))||(filter==="progress"&&["in_progress","pending_review","under_review"].includes(normalized))||(filter==="pending"&&!["implemented","compliant"].includes(normalized))||(filter==="unassigned"&&!t.control_owner)||(filter==="due"&&!t.due_date);return matchesSearch&&matchesFilter&&(framework==="all"||f.code===framework);}),[tasks,search,filter,framework]);
  const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)); const visibleTasks=filtered.slice((page-1)*pageSize,page*pageSize); const rangeStart=filtered.length?((page-1)*pageSize)+1:0; const rangeEnd=Math.min(page*pageSize,filtered.length);
  useEffect(()=>{setPage(1);},[search,filter,framework]);
  const today=new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Riyadh"}); const overdue=tasks.filter(t=>t.due_date&&t.due_date<today&&!['implemented','compliant'].includes((t.implementation_status||'').toLowerCase())).length; const waitingEvidence=tasks.filter(t=>!['uploaded','pending_review','under_review','accepted','approved','verified'].includes((t.evidence_status||'').toLowerCase())).length; const completed=tasks.filter(t=>['implemented','compliant'].includes((t.implementation_status||'').toLowerCase())).length;
  if(loading)return <main dir="rtl" style={center}>جاري تحميل مهامك...</main>; if(error)return <main dir="rtl"><h1>تعذر تحميل البيانات</h1><p role="alert">{error}</p><button onClick={()=>window.location.reload()}>إعادة المحاولة</button></main>;
  return <main className="workflow-page" dir="rtl" style={{color:"var(--cgp-ink)"}}><div className="cgp-page-body" style={{display:"flex",minHeight:"calc(100vh - 86px)"}}><section style={{flex:1,padding:40,minWidth:0}}>
    <WorkflowHeading title={role==="control_owner"?"مهامي":"التكليفات"} description="راجع الاستحقاقات، جهّز الأدلة، وتابع حالة كل ضابط." action={<Link className="workflow-button" href="/controls">سجل الضوابط ←</Link>}/>
    <div className="cgp-responsive-grid cgp-kpi-grid" style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:16,marginBottom:22}}><Kpi label="إجمالي التكليفات" value={tasks.length}/><Kpi label="مكتملة" value={completed} tone="success"/><Kpi label="بانتظار أدلة" value={waitingEvidence} tone={waitingEvidence?"warning":"neutral"}/><Kpi label="متأخرة" value={overdue} tone={overdue?"danger":"neutral"}/></div>
    <div style={{background:"white",border:"1px solid #e2e7eb",borderRadius:14,padding:18,marginBottom:12,display:"flex",gap:8,flexWrap:"wrap"}} role="tablist" aria-label="عرض التكليفات"><button type="button" onClick={()=>setFilter("pending")} aria-selected={filter==="pending"} className="cgp-segment-button">تحتاج إجراء <b>{tasks.length-completed}</b></button><button type="button" onClick={()=>setFilter("evidence")} aria-selected={filter==="evidence"} className="cgp-segment-button">بانتظار الأدلة <b>{waitingEvidence}</b></button><button type="button" onClick={()=>setFilter("unassigned")} aria-selected={filter==="unassigned"} className="cgp-segment-button">بلا مالك <b>{tasks.filter(t=>!t.control_owner).length}</b></button><button type="button" onClick={()=>setFilter("done")} aria-selected={filter==="done"} className="cgp-segment-button">مكتملة <b>{completed}</b></button></div><div style={{background:"white",border:"1px solid #e2e7eb",borderRadius:14,padding:18,marginBottom:18,display:"flex",gap:12,flexWrap:"wrap"}}><div className="cgp-filter-field"><label className="cgp-field-label" htmlFor="task-search">البحث في التكليفات</label><input id="task-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالإطار أو رقم الضابط أو العنوان" style={{flex:1,minWidth:260,border:"1px solid #ccd6dc",borderRadius:9,padding:"11px 13px",fontSize:14}}/></div><div className="cgp-filter-field"><label className="cgp-field-label" htmlFor="task-framework">الإطار التنظيمي</label><select id="task-framework" value={framework} onChange={e=>setFramework(e.target.value)} style={{border:"1px solid #ccd6dc",borderRadius:9,padding:"11px 13px",background:"white"}}><option value="all">جميع الأطر</option>{frameworks.map(code=><option key={code}>{code}</option>)}</select></div><div className="cgp-filter-field"><label className="cgp-field-label" htmlFor="task-filter">حالة التكليف</label><select id="task-filter" value={filter} onChange={e=>setFilter(e.target.value)} style={{border:"1px solid #ccd6dc",borderRadius:9,padding:"11px 13px",background:"white"}}><option value="all">كل الحالات</option><option value="pending">غير مكتملة</option><option value="progress">قيد العمل</option><option value="done">مكتملة</option><option value="overdue">متأخرة</option><option value="evidence">بانتظار الأدلة</option><option value="unassigned">بلا مالك</option><option value="due">استحقاق غير محدد</option></select></div></div>
    <ResultSummary count={filtered.length} total={tasks.length} active={!!search||filter!=="pending"||framework!=="all"} reset={()=>{setSearch("");setFilter("pending");setFramework("all");}}/><p className="cgp-result-range">عرض {rangeStart}–{rangeEnd} من {filtered.length} تكليف</p>
    <div style={{background:"white",border:"1px solid #e2e7eb",borderRadius:14,overflow:"hidden"}}>{filtered.length===0?<div style={{padding:45,textAlign:"center",color:"#586875"}}>لا توجد تكليفات مطابقة حاليًا.</div>:visibleTasks.map(task=>{const isOverdue=!!task.due_date&&task.due_date<today&&!['implemented','compliant'].includes((task.implementation_status||'').toLowerCase());return <div className="workflow-row cgp-responsive-grid" key={task.id} style={{padding:20,borderBottom:"1px solid #edf0f2",display:"grid",gridTemplateColumns:"1.6fr .8fr .8fr .8fr auto",gap:15,alignItems:"center"}}><div><div style={{color:"var(--cgp-teal)",fontWeight:800,fontSize:13}}><span dir="ltr">{frameworkOf(task.frameworks).code} · {task.control_code}</span></div><div style={{fontWeight:800,marginTop:6}}>{task.title_ar}</div><div style={{fontSize:13,color:"#586875",marginTop:5}}>{task.domain_ar}{role!=="control_owner"&&task.control_owner?` · ${task.control_owner}`:""}</div></div><Status label="التنفيذ" value={task.implementation_status}/><Status label="الدليل" value={task.evidence_status}/><div><div style={{fontSize:12,color:"#586875",marginBottom:5}}>الاستحقاق</div><div style={{fontWeight:800,color:isOverdue?"#b42318":"#0b1f33"}}>{task.due_date||"غير محدد"}</div></div><Link href={`/controls/${task.id}`} style={{background:"#eef3f5",color:"#0b1f33",textDecoration:"none",padding:"10px 13px",borderRadius:8,fontWeight:800,fontSize:13}}>فتح الضابط</Link></div>})}</div>{pageCount>1&&<nav className="cgp-pagination" aria-label="صفحات التكليفات"><button type="button" disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>السابق</button><span>صفحة {page} من {pageCount}</span><button type="button" disabled={page===pageCount} onClick={()=>setPage(p=>Math.min(pageCount,p+1))}>التالي</button></nav>}
  </section></div></main>;
}
function Status({label,value}:{label:string;value:string}){return <div><div style={{fontSize:12,color:"#586875",marginBottom:5}}>{label}</div><StatusBadge status={value}/></div>}
const center={display:"grid",placeItems:"center",color:"var(--cgp-ink)"};
