"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { requireProfile } from "@/lib/auth";
import { ResultSummary, WorkflowHeading, WorkflowMetric } from "@/components/WorkflowUI";

type System={id:number;name:string;system_category:string;description:string|null;asset_count:number};
type Control={id:number;control_code:string;title_ar:string;domain_ar:string};
type Result={id?:number;system_id:number;control_id:number;compliance_status:string;notes:string|null;corrective_action:string|null;expected_compliance_date:string|null};
const labels:Record<string,string>={implemented:"مطبق كليًا",partially_implemented:"مطبق جزئيًا",not_implemented:"غير مطبق",not_applicable:"لا ينطبق"};
const categories=["خدمة إلكترونية","تطبيق إلكتروني لأجهزة ذكية","نظام تقني إلكتروني","نظام تقني تشغيلي / صناعي","شبكة تقنية معلومات","شبكة اتصالات هاتفية","شبكة تقنية تشغيلية / صناعية","غير ذلك"];

export default function AssessmentsPage(){
 const router=useRouter();
 const [systems,setSystems]=useState<System[]>([]),[controls,setControls]=useState<Control[]>([]),[results,setResults]=useState<Result[]>([]);
 const [selected,setSelected]=useState<number|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState<number|null>(null),[message,setMessage]=useState("");
 const [activeDomain,setActiveDomain]=useState(""),[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState("all");
 const [form,setForm]=useState({name:"",system_category:categories[2],description:"",asset_count:"0"});
 useEffect(()=>{let active=true;(async()=>{try{await requireProfile(["admin","cybersecurity_team"]);const [{data:s},{data:c,error}]=await Promise.all([supabase.from("cscc_systems").select("id,name,system_category,description,asset_count").order("id"),supabase.from("controls").select("id,control_code,title_ar,domain_ar,frameworks!inner(code)").eq("frameworks.code","CSCC").order("id")]);if(error)throw error;if(!active)return;const list=(s??[]) as System[];setSystems(list);setSelected(list[0]?.id??null);setControls((c??[]) as unknown as Control[]);}catch(e){const m=e instanceof Error?e.message:"";router.replace(m.includes("تسجيل الدخول")?"/login":"/");}finally{if(active)setLoading(false)}})();return()=>{active=false}},[router]);
 useEffect(()=>{const timer=setTimeout(()=>{if(!selected){setResults([]);return}void supabase.from("cscc_assessment_results").select("id,system_id,control_id,compliance_status,notes,corrective_action,expected_compliance_date").eq("system_id",selected).then(({data})=>setResults((data??[]) as Result[]));},0);return()=>clearTimeout(timer)},[selected]);
 const map=useMemo(()=>new Map(results.map(r=>[r.control_id,r])),[results]);
 const counts=useMemo(()=>Object.fromEntries(Object.keys(labels).map(k=>[k,results.filter(r=>r.compliance_status===k).length])),[results]);
 const domains=useMemo(()=>Map.groupBy(controls,c=>c.domain_ar||"غير مصنف"),[controls]);
 const selectedDomain=activeDomain&&domains.has(activeDomain)?activeDomain:[...domains.keys()][0]||"";
 const domainControls=domains.get(selectedDomain)??[];
 const visibleControls=domainControls.filter(c=>{
  const result=map.get(c.id);
  const matchesSearch=`${c.control_code} ${c.title_ar}`.toLowerCase().includes(search.trim().toLowerCase());
  const matchesStatus=statusFilter==="all"||(statusFilter==="unassessed"?!result:result?.compliance_status===statusFilter);
  return matchesSearch&&matchesStatus;
 });
 async function addSystem(e:React.FormEvent){e.preventDefault();const {data,error}=await supabase.from("cscc_systems").insert({name:form.name.trim(),system_category:form.system_category,description:form.description.trim()||null,asset_count:Number(form.asset_count)||0}).select("id,name,system_category,description,asset_count").single();if(error){setMessage("تعذر إضافة النظام: "+error.message);return}const system=data as System;setSystems(v=>[...v,system]);setSelected(system.id);setForm({name:"",system_category:categories[2],description:"",asset_count:"0"});setMessage("تمت إضافة النظام الحساس.")}
 async function save(controlId:number,patch:Partial<Result>){if(!selected)return;setSaving(controlId);const current=map.get(controlId);const payload={system_id:selected,control_id:controlId,compliance_status:patch.compliance_status??current?.compliance_status??"not_implemented",notes:patch.notes??current?.notes??null,corrective_action:patch.corrective_action??current?.corrective_action??null,expected_compliance_date:patch.expected_compliance_date??current?.expected_compliance_date??null,updated_at:new Date().toISOString()};const {data,error}=await supabase.from("cscc_assessment_results").upsert(payload,{onConflict:"system_id,control_id"}).select("id,system_id,control_id,compliance_status,notes,corrective_action,expected_compliance_date").single();if(!error&&data)setResults(v=>[...v.filter(r=>r.control_id!==controlId),data as Result]);setMessage(error?"تعذر حفظ التقييم.":"تم حفظ نتيجة الضابط.");setSaving(null)}
 if(loading)return <main className="workflow-page" dir="rtl">جاري تحميل أداة التقييم…</main>;
 const assessed=results.length,applicable=Math.max(assessed-counts.not_applicable,0),percent=applicable?Math.round(counts.implemented/applicable*100):0;
 return <main className="workflow-page" dir="rtl"><WorkflowHeading title="تقييم وقياس الالتزام — CSCC" description="تطبيق رقمي مبني على أداة NCA: عرّف النظام الحساس، قيّم الضوابط، ووثّق الملاحظات وإجراءات التصحيح."/>
 {message&&<p className="workflow-success" role="status">{message}</p>}
 <nav className="assessment-steps" aria-label="مراحل التقييم"><span className="active"><b>1</b> النظام</span><span className={selected?"active":""}><b>2</b> النتائج</span><span className={selected?"active":""}><b>3</b> المجالات</span><span className={selected?"active":""}><b>4</b> تقييم الضوابط</span></nav>
 <section className="framework-summary"><div><span className="catalog-kicker">الخطوة 1 · CSCC-1:2019</span><h2>النظام محل التقييم</h2><p>اختر نظامًا حساسًا، أو أضف نظامًا جديدًا لبدء تقييم مستقل.</p></div><select aria-label="النظام محل التقييم" value={selected??""} onChange={e=>{setSelected(Number(e.target.value)||null);setActiveDomain("");setSearch("");setStatusFilter("all")}}><option value="">اختر نظامًا</option>{systems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></section>
 <details className="workflow-filter" open={!systems.length}><summary>إضافة نظام حساس</summary><form onSubmit={addSystem} className="workflow-filter-grid" style={{marginTop:16}}><label>اسم النظام<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>فئة النظام<select value={form.system_category} onChange={e=>setForm({...form,system_category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>عدد الأصول<input type="number" min="0" value={form.asset_count} onChange={e=>setForm({...form,asset_count:e.target.value})}/></label><label>وصف مختصر<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="cgp-primary-button">إضافة النظام</button></form></details>
 {selected&&<><section aria-labelledby="assessment-summary"><div className="catalog-section-heading"><div><span>الخطوة 2</span><h2 id="assessment-summary">ملخص نتائج النظام</h2></div><small>{assessed} من {controls.length} ضابط تم تقييمه</small></div><div className="workflow-metrics"><WorkflowMetric label="مستوى الالتزام" value={`${percent}%`} tone="success"/><WorkflowMetric label="مطبق كليًا" value={counts.implemented}/><WorkflowMetric label="مطبق جزئيًا" value={counts.partially_implemented} tone="warning"/><WorkflowMetric label="غير مطبق" value={counts.not_implemented} tone="danger"/></div></section>
 <section aria-labelledby="assessment-domains"><div className="catalog-section-heading"><div><span>الخطوة 3</span><h2 id="assessment-domains">اختر المكون الأساسي</h2></div><small>{domains.size} مكونات</small></div><div className="assessment-domain-grid">{[...domains].map(([name,rows])=>{const done=rows.filter(c=>map.has(c.id)).length;return <button key={name} className={selectedDomain===name?"active":""} onClick={()=>{setActiveDomain(name);setSearch("");setStatusFilter("all")}} aria-pressed={selectedDomain===name}><span><strong>{name}</strong><small>{done} من {rows.length} تم تقييمه</small></span><b>{rows.length?Math.round(done/rows.length*100):0}%</b><progress max={rows.length} value={done}/></button>})}</div></section>
 <section className="catalog-workspace" aria-labelledby="assessment-controls"><div className="catalog-workspace-head"><div><span>الخطوة 4</span><h2 id="assessment-controls">تقييم ضوابط {selectedDomain}</h2><p>{domainControls.length} ضابط في هذا المكون</p></div></div><div className="workflow-filter workflow-filter-grid"><label>البحث داخل المكون<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="رقم الضابط أو اسمه"/></label><label>حالة التقييم<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">كل الحالات</option><option value="unassessed">لم يُقيّم</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div><ResultSummary count={visibleControls.length} total={domainControls.length} active={Boolean(search)||statusFilter!=="all"} reset={()=>{setSearch("");setStatusFilter("all")}}/>{visibleControls.map(c=>{const r=map.get(c.id);return <details className="subdomain-card assessment-control" key={c.id}><summary><span><b dir="ltr">{c.control_code}</b><strong>{c.title_ar.replace(/\s*[-–]\s*[\d-]+\s*$/,"")}</strong></span><span className={`assessment-state ${r?.compliance_status??"unassessed"}`}>{r?labels[r.compliance_status]:"لم يُقيّم"}</span></summary><div className="workflow-filter-grid assessment-fields"><label>مستوى الالتزام<select value={r?.compliance_status??""} onChange={e=>void save(c.id,{compliance_status:e.target.value})}><option value="" disabled>اختر الحالة</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>الملاحظات<textarea defaultValue={r?.notes??""} onBlur={e=>void save(c.id,{notes:e.target.value||null})} placeholder="نتيجة الفحص والمبررات"/></label><label>إجراءات التصحيح<textarea defaultValue={r?.corrective_action??""} onBlur={e=>void save(c.id,{corrective_action:e.target.value||null})} placeholder="الإجراء المطلوب لإغلاق الفجوة"/></label><label>تاريخ الالتزام المتوقع<input type="date" defaultValue={r?.expected_compliance_date??""} onBlur={e=>void save(c.id,{expected_compliance_date:e.target.value||null})}/></label>{saving===c.id&&<small>جاري الحفظ…</small>}</div></details>})}{!visibleControls.length&&<div className="workflow-empty">لا توجد ضوابط مطابقة داخل هذا المكون.</div>}</section></>}
 </main>;
}
