"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { requireProfile } from "@/lib/auth";
import { WorkflowHeading, WorkflowMetric } from "@/components/WorkflowUI";

type System={id:number;name:string;system_category:string;description:string|null;asset_count:number};
type Control={id:number;control_code:string;title_ar:string;domain_ar:string};
type Result={id?:number;system_id:number;control_id:number;compliance_status:string;notes:string|null;corrective_action:string|null;expected_compliance_date:string|null};
const labels:Record<string,string>={implemented:"مطبق كليًا",partially_implemented:"مطبق جزئيًا",not_implemented:"غير مطبق",not_applicable:"لا ينطبق"};
const categories=["خدمة إلكترونية","تطبيق إلكتروني لأجهزة ذكية","نظام تقني إلكتروني","نظام تقني تشغيلي / صناعي","شبكة تقنية معلومات","شبكة اتصالات هاتفية","شبكة تقنية تشغيلية / صناعية","غير ذلك"];

export default function AssessmentsPage(){
 const router=useRouter();
 const [systems,setSystems]=useState<System[]>([]),[controls,setControls]=useState<Control[]>([]),[results,setResults]=useState<Result[]>([]);
 const [selected,setSelected]=useState<number|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState<number|null>(null),[message,setMessage]=useState("");
 const [form,setForm]=useState({name:"",system_category:categories[2],description:"",asset_count:"0"});
 useEffect(()=>{let active=true;(async()=>{try{await requireProfile(["admin","cybersecurity_team"]);const [{data:s},{data:c,error}]=await Promise.all([supabase.from("cscc_systems").select("id,name,system_category,description,asset_count").order("id"),supabase.from("controls").select("id,control_code,title_ar,domain_ar,frameworks!inner(code)").eq("frameworks.code","CSCC").order("id")]);if(error)throw error;if(!active)return;const list=(s??[]) as System[];setSystems(list);setSelected(list[0]?.id??null);setControls((c??[]) as unknown as Control[]);}catch(e){const m=e instanceof Error?e.message:"";router.replace(m.includes("تسجيل الدخول")?"/login":"/");}finally{if(active)setLoading(false)}})();return()=>{active=false}},[router]);
 useEffect(()=>{const timer=setTimeout(()=>{if(!selected){setResults([]);return}void supabase.from("cscc_assessment_results").select("id,system_id,control_id,compliance_status,notes,corrective_action,expected_compliance_date").eq("system_id",selected).then(({data})=>setResults((data??[]) as Result[]));},0);return()=>clearTimeout(timer)},[selected]);
 const map=useMemo(()=>new Map(results.map(r=>[r.control_id,r])),[results]);
 const counts=useMemo(()=>Object.fromEntries(Object.keys(labels).map(k=>[k,controls.filter(c=>(map.get(c.id)?.compliance_status??"not_implemented")===k).length])),[controls,map]);
 async function addSystem(e:React.FormEvent){e.preventDefault();const {data,error}=await supabase.from("cscc_systems").insert({name:form.name.trim(),system_category:form.system_category,description:form.description.trim()||null,asset_count:Number(form.asset_count)||0}).select("id,name,system_category,description,asset_count").single();if(error){setMessage("تعذر إضافة النظام: "+error.message);return}const system=data as System;setSystems(v=>[...v,system]);setSelected(system.id);setForm({name:"",system_category:categories[2],description:"",asset_count:"0"});setMessage("تمت إضافة النظام الحساس.")}
 async function save(controlId:number,patch:Partial<Result>){if(!selected)return;setSaving(controlId);const current=map.get(controlId);const payload={system_id:selected,control_id:controlId,compliance_status:patch.compliance_status??current?.compliance_status??"not_implemented",notes:patch.notes??current?.notes??null,corrective_action:patch.corrective_action??current?.corrective_action??null,expected_compliance_date:patch.expected_compliance_date??current?.expected_compliance_date??null,updated_at:new Date().toISOString()};const {data,error}=await supabase.from("cscc_assessment_results").upsert(payload,{onConflict:"system_id,control_id"}).select("id,system_id,control_id,compliance_status,notes,corrective_action,expected_compliance_date").single();if(!error&&data)setResults(v=>[...v.filter(r=>r.control_id!==controlId),data as Result]);setMessage(error?"تعذر حفظ التقييم.":"تم حفظ نتيجة الضابط.");setSaving(null)}
 if(loading)return <main className="workflow-page" dir="rtl">جاري تحميل أداة التقييم…</main>;
 const assessed=results.length,percent=controls.length?Math.round((counts.implemented/Math.max(controls.length-counts.not_applicable,1))*100):0;
 return <main className="workflow-page" dir="rtl"><WorkflowHeading title="تقييم وقياس الالتزام — CSCC" description="تطبيق رقمي مبني على أداة NCA: عرّف النظام الحساس، قيّم الضوابط، ووثّق الملاحظات وإجراءات التصحيح."/>
 {message&&<p className="workflow-success" role="status">{message}</p>}
 <section className="framework-summary"><div><span className="catalog-kicker">CSCC-1:2019</span><h2>النظام محل التقييم</h2><p>يمكن إنشاء تقييمات مستقلة لعدة أنظمة حساسة.</p></div><select value={selected??""} onChange={e=>setSelected(Number(e.target.value)||null)}><option value="">اختر نظامًا</option>{systems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></section>
 <details className="workflow-filter" open={!systems.length}><summary>إضافة نظام حساس</summary><form onSubmit={addSystem} className="workflow-filter-grid" style={{marginTop:16}}><label>اسم النظام<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>فئة النظام<select value={form.system_category} onChange={e=>setForm({...form,system_category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>عدد الأصول<input type="number" min="0" value={form.asset_count} onChange={e=>setForm({...form,asset_count:e.target.value})}/></label><label>وصف مختصر<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="cgp-primary-button">إضافة النظام</button></form></details>
 {selected&&<><div className="workflow-metrics"><WorkflowMetric label="مستوى الالتزام" value={`${percent}%`} tone="success"/><WorkflowMetric label="مطبق كليًا" value={counts.implemented}/><WorkflowMetric label="مطبق جزئيًا" value={counts.partially_implemented} tone="warning"/><WorkflowMetric label="تم تقييمه" value={`${assessed}/${controls.length}`}/></div>
 <section className="catalog-workspace"><h2>حالة الالتزام بالضوابط</h2>{controls.map(c=>{const r=map.get(c.id);return <details className="subdomain-card" key={c.id}><summary><span><b dir="ltr">{c.control_code}</b><strong>{c.title_ar}</strong><small>{c.domain_ar}</small></span><span>{labels[r?.compliance_status??"not_implemented"]}</span></summary><div className="workflow-filter-grid" style={{padding:18}}><label>مستوى الالتزام<select value={r?.compliance_status??"not_implemented"} onChange={e=>void save(c.id,{compliance_status:e.target.value})}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>الملاحظات<textarea defaultValue={r?.notes??""} onBlur={e=>void save(c.id,{notes:e.target.value||null})}/></label><label>إجراءات التصحيح<textarea defaultValue={r?.corrective_action??""} onBlur={e=>void save(c.id,{corrective_action:e.target.value||null})}/></label><label>تاريخ الالتزام المتوقع<input type="date" defaultValue={r?.expected_compliance_date??""} onBlur={e=>void save(c.id,{expected_compliance_date:e.target.value||null})}/></label>{saving===c.id&&<small>جاري الحفظ…</small>}</div></details>})}</section></>}
 </main>;
}
