"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { WorkflowHeading, WorkflowMetric, ResultSummary } from "@/components/WorkflowUI";
import { requireProfile } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import "./third-parties.css";

type Party={id:number;name:string;service:string;relationship_owner:string|null;data_classification:string;criticality:string;inherent_risk_score:number;control_effectiveness:number;assessment_status:string;decision:string;treatment_plan:string|null;next_review_date:string|null;created_at:string};
const riskLabel:Record<string,string>={low:"منخفض",medium:"متوسط",high:"مرتفع",critical:"حرج"};
const statusLabel:Record<string,string>={draft:"مسودة",in_review:"قيد التقييم",completed:"مكتمل",expired:"منتهي"};
const decisionLabel:Record<string,string>={pending:"بانتظار القرار",approved:"معتمد",conditional:"اعتماد مشروط",rejected:"مرفوض"};
const residual=(p:Party)=>Math.max(1,Math.min(5,p.inherent_risk_score-(p.control_effectiveness-3)));
export default function ThirdPartiesPage(){
 const router=useRouter();const [items,setItems]=useState<Party[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[showForm,setShowForm]=useState(false),[filter,setFilter]=useState("all");
 const [form,setForm]=useState({name:"",service:"",relationship_owner:"",data_classification:"internal",criticality:"medium",inherent_risk_score:"3",control_effectiveness:"3",treatment_plan:"",next_review_date:""});
 async function load(){const {data,error:e}=await supabase.from("third_parties").select("*").order("created_at",{ascending:false});if(e)throw e;setItems((data??[]) as Party[])}
 useEffect(()=>{let active=true;(async()=>{try{await requireProfile(["admin","cybersecurity_team"]);if(active)await load()}catch(e){if(active){const m=e instanceof Error?e.message:"تعذر تحميل الموردين";setError(m);if(m.includes("تسجيل الدخول"))router.replace("/login");else if(m.includes("الصلاحية"))router.replace("/")}}finally{if(active)setLoading(false)}})();return()=>{active=false}},[router]);
 const visible=useMemo(()=>filter==="all"?items:items.filter(p=>p.criticality===filter),[items,filter]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const {user}=await requireProfile(["admin","cybersecurity_team"]);const {error:insertError}=await supabase.from("third_parties").insert({...form,relationship_owner:form.relationship_owner||null,treatment_plan:form.treatment_plan||null,next_review_date:form.next_review_date||null,inherent_risk_score:Number(form.inherent_risk_score),control_effectiveness:Number(form.control_effectiveness),created_by:user.id});if(insertError)throw insertError;await load();setShowForm(false);setForm({name:"",service:"",relationship_owner:"",data_classification:"internal",criticality:"medium",inherent_risk_score:"3",control_effectiveness:"3",treatment_plan:"",next_review_date:""})}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ الطرف الخارجي")}finally{setSaving(false)}}
 async function update(id:number,patch:Partial<Party>){const {error:e}=await supabase.from("third_parties").update({...patch,updated_at:new Date().toISOString()}).eq("id",id);if(e){setError("تعذر تحديث التقييم");return}setItems(rows=>rows.map(row=>row.id===id?{...row,...patch}:row))}
 if(loading)return <main className="workflow-page" role="status">جاري تحميل مخاطر الأطراف الخارجية…</main>;
 return <main className="workflow-page third-party-page" dir="rtl"><WorkflowHeading title="مخاطر الأطراف الخارجية" description="سجل الموردين والخدمات، تقييم المخاطر، خطط المعالجة وقرارات الاعتماد." action={<button className="workflow-button workflow-primary" onClick={()=>setShowForm(v=>!v)}>+ إضافة طرف خارجي</button>}/>
 {error&&<p className="cgp-shell-error" role="alert">{error}</p>}
 <div className="workflow-metrics"><WorkflowMetric label="إجمالي الأطراف" value={items.length}/><WorkflowMetric label="مخاطر حرجة" value={items.filter(p=>p.criticality==="critical").length} tone="danger"/><WorkflowMetric label="قيد التقييم" value={items.filter(p=>p.assessment_status==="in_review"||p.assessment_status==="draft").length} tone="warning"/><WorkflowMetric label="معتمدة" value={items.filter(p=>p.decision==="approved").length} tone="success"/></div>
 {showForm&&<form className="third-party-form" onSubmit={submit}><h2>تسجيل وتقييم طرف خارجي</h2><div className="third-party-fields"><label>اسم المورد<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>الخدمة المقدمة<input required value={form.service} onChange={e=>setForm({...form,service:e.target.value})}/></label><label>مالك العلاقة<input value={form.relationship_owner} onChange={e=>setForm({...form,relationship_owner:e.target.value})}/></label><label>تصنيف البيانات<select value={form.data_classification} onChange={e=>setForm({...form,data_classification:e.target.value})}><option value="public">عامة</option><option value="internal">داخلية</option><option value="confidential">سرية</option><option value="restricted">مقيدة</option></select></label><label>أهمية الطرف<select value={form.criticality} onChange={e=>setForm({...form,criticality:e.target.value})}><option value="low">منخفضة</option><option value="medium">متوسطة</option><option value="high">مرتفعة</option><option value="critical">حرجة</option></select></label><label>المخاطر الكامنة (1–5)<input type="number" min="1" max="5" value={form.inherent_risk_score} onChange={e=>setForm({...form,inherent_risk_score:e.target.value})}/></label><label>فعالية الضوابط (1–5)<input type="number" min="1" max="5" value={form.control_effectiveness} onChange={e=>setForm({...form,control_effectiveness:e.target.value})}/></label><label>موعد المراجعة القادمة<input type="date" value={form.next_review_date} onChange={e=>setForm({...form,next_review_date:e.target.value})}/></label><label className="wide">خطة المعالجة<textarea rows={3} value={form.treatment_plan} onChange={e=>setForm({...form,treatment_plan:e.target.value})}/></label></div><div className="third-party-actions"><button disabled={saving} className="workflow-button workflow-primary">{saving?"جاري الحفظ…":"حفظ التقييم"}</button><button type="button" className="workflow-button" onClick={()=>setShowForm(false)}>إلغاء</button></div></form>}
 <div className="workflow-filter"><label className="cgp-field-label" htmlFor="risk-filter">مستوى الأهمية</label><select id="risk-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">جميع المستويات</option>{Object.entries(riskLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><ResultSummary count={visible.length} total={items.length} active={filter!=="all"} reset={()=>setFilter("all")}/>
 {!visible.length?<div className="workflow-empty">لا توجد أطراف خارجية مسجلة ضمن هذا النطاق.</div>:<div className="third-party-grid">{visible.map(p=><article className="third-party-card" key={p.id}><header><div><span className={`risk-pill risk-${p.criticality}`}>{riskLabel[p.criticality]}</span><h2>{p.name}</h2><p>{p.service}</p></div><div className="risk-score"><small>المخاطر المتبقية</small><strong>{residual(p)}/5</strong></div></header><dl><div><dt>مالك العلاقة</dt><dd>{p.relationship_owner||"غير معيّن"}</dd></div><div><dt>تصنيف البيانات</dt><dd>{p.data_classification}</dd></div><div><dt>المراجعة القادمة</dt><dd>{p.next_review_date||"غير محددة"}</dd></div></dl>{p.treatment_plan&&<p className="treatment"><b>خطة المعالجة:</b> {p.treatment_plan}</p>}<div className="third-party-controls"><label>حالة التقييم<select value={p.assessment_status} onChange={e=>update(p.id,{assessment_status:e.target.value})}>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>قرار الاعتماد<select value={p.decision} onChange={e=>update(p.id,{decision:e.target.value})}>{Object.entries(decisionLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div></article>)}</div>}</main>
}
