"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { WorkflowHeading, WorkflowMetric, ResultSummary } from "@/components/WorkflowUI";
import { requireProfile } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import "./third-parties.css";

type Party={id:number;name:string;service:string;relationship_owner:string|null;data_classification:string;criticality:string;risk_scenario:string|null;likelihood:number;impact:number;inherent_risk_score:number;control_effectiveness:number;residual_risk_score:number;risk_treatment:string;assessment_status:string;decision:string;treatment_plan:string|null;next_review_date:string|null;created_at:string};
const riskLabel:Record<string,string>={low:"منخفض",medium:"متوسط",high:"مرتفع",critical:"حرج"};
const statusLabel:Record<string,string>={draft:"مسودة",in_review:"قيد التقييم",completed:"مكتمل",expired:"منتهي"};
const decisionLabel:Record<string,string>={pending:"بانتظار القرار",approved:"معتمد",conditional:"اعتماد مشروط",rejected:"مرفوض"};
const treatmentLabel:Record<string,string>={accept:"قبول",mitigate:"تخفيف",transfer:"نقل",avoid:"تجنب"};
const scoreLevel=(score:number)=>score>=20?"حرج":score>=12?"مرتفع":score>=6?"متوسط":"منخفض";
const calculateResidual=(likelihood:number,impact:number,effectiveness:number)=>Math.max(1,Math.round(likelihood*impact*((6-effectiveness)/5)));
export default function ThirdPartiesPage(){
 const router=useRouter();const [items,setItems]=useState<Party[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[showForm,setShowForm]=useState(false),[filter,setFilter]=useState("all");
 const [step,setStep]=useState(1);
 const emptyForm={name:"",service:"",relationship_owner:"",data_classification:"internal",criticality:"medium",risk_scenario:"",likelihood:"3",impact:"3",control_effectiveness:"3",risk_treatment:"mitigate",treatment_plan:"",next_review_date:""};
 const [form,setForm]=useState(emptyForm);
 const inherent=Number(form.likelihood)*Number(form.impact);
 const residual=calculateResidual(Number(form.likelihood),Number(form.impact),Number(form.control_effectiveness));
 async function load(){const {data,error:e}=await supabase.from("third_parties").select("*").order("created_at",{ascending:false});if(e)throw e;setItems((data??[]) as Party[])}
 useEffect(()=>{let active=true;(async()=>{try{await requireProfile(["admin","cybersecurity_team"]);if(active)await load()}catch(e){if(active){const m=e instanceof Error?e.message:"تعذر تحميل الموردين";setError(m);if(m.includes("تسجيل الدخول"))router.replace("/login");else if(m.includes("الصلاحية"))router.replace("/")}}finally{if(active)setLoading(false)}})();return()=>{active=false}},[router]);
 const visible=useMemo(()=>filter==="all"?items:items.filter(p=>p.criticality===filter),[items,filter]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const {user}=await requireProfile(["admin","cybersecurity_team"]);const {error:insertError}=await supabase.from("third_parties").insert({...form,relationship_owner:form.relationship_owner||null,treatment_plan:form.treatment_plan||null,next_review_date:form.next_review_date||null,likelihood:Number(form.likelihood),impact:Number(form.impact),control_effectiveness:Number(form.control_effectiveness),created_by:user.id});if(insertError)throw insertError;await load();setShowForm(false);setStep(1);setForm(emptyForm)}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ الطرف الخارجي")}finally{setSaving(false)}}
 async function update(id:number,patch:Partial<Party>){const {error:e}=await supabase.from("third_parties").update({...patch,updated_at:new Date().toISOString()}).eq("id",id);if(e){setError("تعذر تحديث التقييم");return}setItems(rows=>rows.map(row=>row.id===id?{...row,...patch}:row))}
 if(loading)return <main className="workflow-page" role="status">جاري تحميل مخاطر الأطراف الخارجية…</main>;
 return <main className="workflow-page third-party-page" dir="rtl"><WorkflowHeading title="مخاطر الأطراف الخارجية" description="سجل الموردين والخدمات، تقييم المخاطر، خطط المعالجة وقرارات الاعتماد." action={<button className="workflow-button workflow-primary" onClick={()=>setShowForm(v=>!v)}>+ إضافة طرف خارجي</button>}/>
 {error&&<p className="cgp-shell-error" role="alert">{error}</p>}
 <div className="workflow-metrics"><WorkflowMetric label="إجمالي الأطراف" value={items.length}/><WorkflowMetric label="مخاطر حرجة" value={items.filter(p=>p.criticality==="critical").length} tone="danger"/><WorkflowMetric label="قيد التقييم" value={items.filter(p=>p.assessment_status==="in_review"||p.assessment_status==="draft").length} tone="warning"/><WorkflowMetric label="معتمدة" value={items.filter(p=>p.decision==="approved").length} tone="success"/></div>
 {showForm&&<form className="third-party-form" onSubmit={submit}><div className="risk-wizard-head"><div><span>الخطوة {step} من 4</span><h2>{["تعريف الطرف والنطاق","تحديد سيناريو الخطر","قياس المخاطر والضوابط","المعالجة والمراجعة"][step-1]}</h2></div><div className="risk-steps">{[1,2,3,4].map(n=><i key={n} className={n<=step?"active":""}>{n}</i>)}</div></div>
 {step===1&&<div className="third-party-fields"><label>اسم المورد<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>الخدمة المقدمة<input required value={form.service} onChange={e=>setForm({...form,service:e.target.value})}/></label><label>مالك العلاقة<input value={form.relationship_owner} onChange={e=>setForm({...form,relationship_owner:e.target.value})}/></label><label>تصنيف البيانات<select value={form.data_classification} onChange={e=>setForm({...form,data_classification:e.target.value})}><option value="public">عامة</option><option value="internal">داخلية</option><option value="confidential">سرية</option><option value="restricted">مقيدة</option></select></label><label>أهمية الطرف<select value={form.criticality} onChange={e=>setForm({...form,criticality:e.target.value})}><option value="low">منخفضة</option><option value="medium">متوسطة</option><option value="high">مرتفعة</option><option value="critical">حرجة</option></select></label></div>}
 {step===2&&<div className="risk-guided"><p>صِف حدثًا محددًا وسببه وتأثيره. مثال: توقف مزود الخدمة السحابية يؤدي إلى تعطل نظام حرج.</p><label>سيناريو الخطر<textarea required rows={5} value={form.risk_scenario} onChange={e=>setForm({...form,risk_scenario:e.target.value})} placeholder="قد يؤدي… بسبب… إلى…"/></label></div>}
 {step===3&&<><div className="risk-scale-grid"><label>الاحتمالية<select value={form.likelihood} onChange={e=>setForm({...form,likelihood:e.target.value})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} — {['نادر','غير مرجح','ممكن','مرجح','شبه مؤكد'][n-1]}</option>)}</select></label><label>الأثر<select value={form.impact} onChange={e=>setForm({...form,impact:e.target.value})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} — {['طفيف','محدود','متوسط','كبير','جسيم'][n-1]}</option>)}</select></label><label>فعالية الضوابط<select value={form.control_effectiveness} onChange={e=>setForm({...form,control_effectiveness:e.target.value})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} — {['غير فعالة','ضعيفة','جزئية','فعالة','فعالة جدًا'][n-1]}</option>)}</select></label></div><div className="risk-calculation"><div><small>المخاطر الكامنة</small><strong>{inherent}/25</strong><span>{scoreLevel(inherent)}</span></div><b>← بعد الضوابط ←</b><div><small>المخاطر المتبقية</small><strong>{residual}/25</strong><span>{scoreLevel(residual)}</span></div></div><div className="risk-matrix">{[5,4,3,2,1].flatMap(i=>[1,2,3,4,5].map(l=>{const score=i*l;return <span key={`${i}-${l}`} className={score>=20?'critical':score>=12?'high':score>=6?'medium':'low'}>{score}</span>}))}</div><small className="risk-formula">المخاطر الكامنة = الاحتمالية × الأثر. المتبقية تُخفض بحسب فعالية الضوابط.</small></>}
 {step===4&&<div className="third-party-fields"><label>قرار المعالجة<select value={form.risk_treatment} onChange={e=>setForm({...form,risk_treatment:e.target.value})}>{Object.entries(treatmentLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>موعد المراجعة القادمة<input type="date" value={form.next_review_date} onChange={e=>setForm({...form,next_review_date:e.target.value})}/></label><label className="wide">خطة المعالجة<textarea required={form.risk_treatment==='mitigate'} rows={4} value={form.treatment_plan} onChange={e=>setForm({...form,treatment_plan:e.target.value})} placeholder="الإجراء، المسؤول، والموعد المستهدف"/></label></div>}
 <div className="third-party-actions">{step>1&&<button type="button" className="workflow-button" onClick={()=>setStep(s=>s-1)}>السابق</button>}{step<4?<button type="button" className="workflow-button workflow-primary" onClick={()=>setStep(s=>s+1)} disabled={(step===1&&(!form.name.trim()||!form.service.trim()))||(step===2&&!form.risk_scenario.trim())}>التالي</button>:<button disabled={saving} className="workflow-button workflow-primary">{saving?"جاري الحفظ…":"حفظ التقييم"}</button>}<button type="button" className="workflow-button" onClick={()=>{setShowForm(false);setStep(1)}}>إلغاء</button></div></form>}
 <div className="workflow-filter"><label className="cgp-field-label" htmlFor="risk-filter">مستوى الأهمية</label><select id="risk-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">جميع المستويات</option>{Object.entries(riskLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><ResultSummary count={visible.length} total={items.length} active={filter!=="all"} reset={()=>setFilter("all")}/>
 {!visible.length?<div className="workflow-empty">لا توجد أطراف خارجية مسجلة ضمن هذا النطاق.</div>:<div className="third-party-grid">{visible.map(p=><article className="third-party-card" key={p.id}><header><div><span className={`risk-pill risk-${p.criticality}`}>{riskLabel[p.criticality]}</span><h2>{p.name}</h2><p>{p.service}</p></div><div className="risk-score"><small>المخاطر المتبقية</small><strong>{p.residual_risk_score}/25</strong></div></header><dl><div><dt>مالك العلاقة</dt><dd>{p.relationship_owner||"غير معيّن"}</dd></div><div><dt>تصنيف البيانات</dt><dd>{p.data_classification}</dd></div><div><dt>المراجعة القادمة</dt><dd>{p.next_review_date||"غير محددة"}</dd></div></dl>{p.risk_scenario&&<p className="treatment"><b>سيناريو الخطر:</b> {p.risk_scenario}</p>}{p.treatment_plan&&<p className="treatment"><b>خطة المعالجة ({treatmentLabel[p.risk_treatment]}):</b> {p.treatment_plan}</p>}<div className="third-party-controls"><label>حالة التقييم<select value={p.assessment_status} onChange={e=>update(p.id,{assessment_status:e.target.value})}>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>قرار الاعتماد<select value={p.decision} onChange={e=>update(p.id,{decision:e.target.value})}>{Object.entries(decisionLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div></article>)}</div>}</main>
}
