"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { requireProfile,type UserRole } from "@/lib/auth";
import { WorkflowHeading,WorkflowMetric } from "@/components/WorkflowUI";
import "./risks.css";
type Risk={id:number;risk_code:string;risk_scope:string;risk_owner:string;risk_description:string;threat:string;inherent_likelihood:number;inherent_impact:number;inherent_score:number;treatment_type:string;treatment_owner:string;action_due_date:string|null;residual_likelihood:number;residual_impact:number;residual_score:number;next_steps:string;risk_status:"open"|"treatment_in_progress"|"accepted"|"closed"};
const score=(l:number,i:number)=>l*i;
const level=(s:number)=>s<=3?"منخفض جدًا":s<=6?"منخفض":s<=10?"متوسط":s<=16?"مرتفع":"حرج";
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Riyadh"});
const statusLabel=(s:Risk["risk_status"])=>({open:"مفتوح",treatment_in_progress:"قيد المعالجة",accepted:"مقبول",closed:"مغلق"}[s]);
export default function RisksPage(){
 const router=useRouter(),[items,setItems]=useState<Risk[]>([]),[role,setRole]=useState<UserRole>("control_owner"),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const [f,setF]=useState({risk_code:"",risk_scope:"business_operations",risk_owner:"",risk_description:"",threat:"",inherent_likelihood:"3",inherent_impact:"3",treatment_type:"mitigate",treatment_owner:"",action_due_date:"",residual_likelihood:"2",residual_impact:"3",next_steps:""});
 const load=async()=>{const {data,error}=await supabase.from("cyber_risks").select("*").order("residual_score",{ascending:false});if(error)throw error;setItems((data??[]) as Risk[])};
 useEffect(()=>{let live=true;(async()=>{try{const {profile}=await requireProfile();if(!live)return;setRole(profile.role);await load()}catch(e){if(live)setError(e instanceof Error?e.message:"تعذر تحميل سجل المخاطر")}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 const inherent=score(+f.inherent_likelihood,+f.inherent_impact),residual=score(+f.residual_likelihood,+f.residual_impact);
 const overdue=useMemo(()=>items.filter(x=>x.action_due_date&&x.action_due_date<today()&&x.residual_score>3).length,[items]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const {user}=await requireProfile(["admin","cybersecurity_team"]);const payload={...f,identification_date:today(),assessment_date:today(),last_assessment_date:today(),risk_cause:"لم يحدد بعد",risk_analysis:"قيد التقييم",treatment_description:"قيد التوثيق",residual_risk_description:"قيد التوثيق",notes:null,created_by:user.id,inherent_likelihood:+f.inherent_likelihood,inherent_impact:+f.inherent_impact,residual_likelihood:+f.residual_likelihood,residual_impact:+f.residual_impact,action_due_date:f.action_due_date||null};const {error}=await supabase.from("cyber_risks").insert(payload);if(error)throw error;await load();setOpen(false)}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ الخطر")}finally{setSaving(false)}}
 async function updateStatus(id:number,risk_status:Risk["risk_status"]){setSaving(true);setError("");try{const {user}=await requireProfile(["admin","cybersecurity_team"]);const patch={risk_status,last_assessment_date:today(),closed_at:risk_status==="closed"?new Date().toISOString():null,closed_by:risk_status==="closed"?user.id:null};const {error}=await supabase.from("cyber_risks").update(patch).eq("id",id);if(error)throw error;await load()}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث حالة الخطر")}finally{setSaving(false)}}
 if(loading)return <main className="workflow-page" dir="rtl">جاري تحميل سجل المخاطر…</main>;
 return <main className="workflow-page risks" dir="rtl"><WorkflowHeading title="سجل مخاطر الأمن السيبراني" description="سجل موحد للمخاطر الكامنة والمعالجة والمخاطر المتبقية وفق منهجية NCA." action={role!=="control_owner"?<button className="workflow-button workflow-primary" onClick={()=>setOpen(v=>!v)}>+ تسجيل خطر</button>:undefined}/>
 {error&&<p className="cgp-shell-error" role="alert">{error}</p>}
 <div className="workflow-metrics"><WorkflowMetric label="إجمالي المخاطر" value={items.length}/><WorkflowMetric label="حرجة متبقية" value={items.filter(x=>x.residual_score>=17).length} tone="danger"/><WorkflowMetric label="إجراءات متأخرة" value={overdue} tone={overdue?"danger":"neutral"}/><WorkflowMetric label="تحت المعالجة" value={items.filter(x=>x.risk_status==="treatment_in_progress").length}/></div>
 {open&&<form onSubmit={save} className="risk-form"><h2>تسجيل خطر جديد</h2><div><label>رقم الخطر<input required value={f.risk_code} onChange={e=>setF({...f,risk_code:e.target.value})} placeholder="RISK-001"/></label><label>نطاق الخطر<select value={f.risk_scope} onChange={e=>setF({...f,risk_scope:e.target.value})}><option value="business_operations">عمليات الأعمال</option><option value="it_assets">أصول تقنية المعلومات</option><option value="people">العاملون</option></select></label><label>مالك الخطر<input required value={f.risk_owner} onChange={e=>setF({...f,risk_owner:e.target.value})}/></label><label>التهديد<input required value={f.threat} onChange={e=>setF({...f,threat:e.target.value})}/></label><label className="wide">وصف الخطر<textarea required value={f.risk_description} onChange={e=>setF({...f,risk_description:e.target.value})}/></label><label>الاحتمالية الكامنة<select value={f.inherent_likelihood} onChange={e=>setF({...f,inherent_likelihood:e.target.value})}>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>الأثر الكامن<select value={f.inherent_impact} onChange={e=>setF({...f,inherent_impact:e.target.value})}>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>طريقة المعالجة<select value={f.treatment_type} onChange={e=>setF({...f,treatment_type:e.target.value})}><option value="mitigate">الحد من المخاطر</option><option value="avoid">تجنب المخاطر</option><option value="transfer">نقل المخاطر</option><option value="accept">قبول المخاطر</option></select></label><label>مالك المعالجة<input required value={f.treatment_owner} onChange={e=>setF({...f,treatment_owner:e.target.value})}/></label><label>موعد الإجراء<input type="date" value={f.action_due_date} onChange={e=>setF({...f,action_due_date:e.target.value})}/></label><label>الاحتمالية المتبقية<select value={f.residual_likelihood} onChange={e=>setF({...f,residual_likelihood:e.target.value})}>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>الأثر المتبقي<select value={f.residual_impact} onChange={e=>setF({...f,residual_impact:e.target.value})}>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">الخطوات التالية<textarea required value={f.next_steps} onChange={e=>setF({...f,next_steps:e.target.value})}/></label></div><p className="scores">الخطر الكامن: <b>{inherent}/25 — {level(inherent)}</b> · المتبقي: <b>{residual}/25 — {level(residual)}</b></p><button disabled={saving} className="workflow-button workflow-primary">{saving?"جاري الحفظ…":"حفظ الخطر"}</button> <button type="button" className="workflow-button" onClick={()=>setOpen(false)}>إلغاء</button></form>}
 <section className="risk-panel"><h2>المخطط الحراري والمخاطر الكلية</h2><p>يعرض السجل درجات المخاطر المتبقية بعد إجراء المعالجة.</p><div className="heatmap">{[5,4,3,2,1].flatMap(i=>[1,2,3,4,5].map(l=><span className={score(l,i)>=17?"critical":score(l,i)>=11?"high":score(l,i)>=7?"medium":"low"} key={l+"-"+i}>{items.filter(x=>x.residual_likelihood===l&&x.residual_impact===i).length}</span>))}</div></section>
 <section className="risk-list"><h2>سجل المخاطر</h2>{items.length===0?<p>لا توجد مخاطر مسجلة حتى الآن.</p>:<table><thead><tr><th>الخطر</th><th>المالك</th><th>الكامن</th><th>المتبقي</th><th>المعالجة والاستحقاق</th><th>الحالة</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b dir="ltr">{x.risk_code}</b><br/>{x.risk_description}<small>{x.threat}</small></td><td>{x.risk_owner}</td><td>{x.inherent_score}/25<br/>{level(x.inherent_score)}</td><td>{x.residual_score}/25<br/>{level(x.residual_score)}</td><td>{x.treatment_owner}<small>{x.action_due_date||"غير محدد"}</small></td><td><select aria-label={`حالة ${x.risk_code}`} value={x.risk_status} disabled={saving||role==="control_owner"} onChange={e=>updateStatus(x.id,e.target.value as Risk["risk_status"])}><option value="open">مفتوح</option><option value="treatment_in_progress">قيد المعالجة</option><option value="accepted">مقبول</option><option value="closed">مغلق</option></select><small>{statusLabel(x.risk_status)}</small></td></tr>)}</tbody></table>}</section></main>
}