"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { WorkflowHeading, WorkflowMetric, ResultSummary } from "@/components/WorkflowUI";
import { requireProfile, type UserRole } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import "./risks.css";

type CyberRisk={id:number;risk_code:string;risk_scope:string;risk_owner:string;identification_date:string;risk_description:string;risk_cause:string;threat:string;risk_analysis:string;assessment_date:string;inherent_likelihood:number;inherent_impact:number;inherent_score:number;inherent_override:string|null;treatment_type:string;treatment_description:string;treatment_owner:string;action_due_date:string|null;residual_risk_description:string;residual_likelihood:number;residual_impact:number;residual_score:number;next_steps:string;last_assessment_date:string;notes:string|null};
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Riyadh"});
const emptyForm={risk_code:"",risk_scope:"business_operations",risk_owner:"",identification_date:today(),risk_description:"",risk_cause:"",threat:"",risk_analysis:"",assessment_date:today(),inherent_likelihood:"3",inherent_impact:"3",inherent_override:"",treatment_type:"mitigate",treatment_description:"",treatment_owner:"",action_due_date:"",residual_risk_description:"",residual_likelihood:"2",residual_impact:"3",next_steps:"",last_assessment_date:today(),notes:""};
const scopeLabels:Record<string,string>={it_assets:"أصول تقنية المعلومات",business_operations:"عمليات الأعمال",people:"العاملون"};
const treatmentLabels:Record<string,string>={mitigate:"الحدّ من المخاطر",avoid:"تجنّب المخاطر",transfer:"نقل المخاطر",accept:"قابلية تحمُّل المخاطر"};
const ratingLabels:Record<string,string>={very_low:"منخفض جدًا",low:"منخفض",medium:"متوسط",high:"مرتفع",critical:"حرج",not_applicable:"لا ينطبق"};
const likelihoodLabels=["","نادر جدًا","نادر","غير مرجح","مرجح","شبه مؤكد"];
const impactLabels=["","منخفض جدًا","منخفض","متوسط","مرتفع","كارثي"];
const rating=(score:number)=>score<=3?"very_low":score<=6?"low":score<=10?"medium":score<=16?"high":"critical";
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;

export default function RisksPage(){
 const router=useRouter();const [items,setItems]=useState<CyberRisk[]>([]),[role,setRole]=useState<UserRole>("control_owner"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[showForm,setShowForm]=useState(false),[search,setSearch]=useState(""),[scope,setScope]=useState("all"),[form,setForm]=useState(emptyForm);
 async function load(){const {data,error}=await supabase.from("cyber_risks").select("*").order("residual_score",{ascending:false}).order("action_due_date",{ascending:true,nullsFirst:false});if(error)throw error;setItems((data??[]) as CyberRisk[])}
 useEffect(()=>{let active=true;(async()=>{try{const {profile}=await requireProfile();if(!active)return;setRole(profile.role);await load()}catch(e){if(!active)return;const m=e instanceof Error?e.message:"";if(m.includes("تسجيل الدخول")){router.replace("/login");return}setError(m.includes("cyber_risks")||m.includes("schema cache")||m.includes("relation")?"سجل المخاطر جاهز وينتظر تفعيل قاعدة البيانات للنسخة التجريبية.":"تعذر تحميل سجل المخاطر. حاول التحديث مرة أخرى.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[router]);
 const visible=useMemo(()=>items.filter(r=>{const q=search.trim().toLowerCase();return(!q||`${r.risk_code} ${r.risk_description} ${r.risk_owner} ${r.threat}`.toLowerCase().includes(q))&&(scope==="all"||r.risk_scope===scope)}),[items,search,scope]);
 const currentDate=today();const overdue=items.filter(r=>r.action_due_date&&r.action_due_date<currentDate&&r.residual_score>3).length;const levels=["critical","high","medium","low","very_low"];const levelCount=(kind:"inherent"|"residual",level:string)=>items.filter(r=>rating(kind==="inherent"?r.inherent_score:r.residual_score)===level).length;const heatCount=(kind:"inherent"|"residual",likelihood:number,impact:number)=>items.filter(r=>(kind==="inherent"?r.inherent_likelihood:r.residual_likelihood)===likelihood&&(kind==="inherent"?r.inherent_impact:r.residual_impact)===impact).length;
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");try{const {user}=await requireProfile(["admin","cybersecurity_team"]);const payload={...form,inherent_likelihood:Number(form.inherent_likelihood),inherent_impact:Number(form.inherent_impact),residual_likelihood:Number(form.residual_likelihood),residual_impact:Number(form.residual_impact),inherent_override:form.inherent_override||null,action_due_date:form.action_due_date||null,notes:form.notes||null,created_by:user.id};const {error}=await supabase.from("cyber_risks").insert(payload);if(error)throw error;await load();setForm(emptyForm);setShowForm(false);setMessage("تمت إضافة الخطر إلى سجل NCA.")}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ الخطر")}finally{setSaving(false)}}
 function exportNca(){const headers=["رقم تعريف المخاطر","نطاق المخاطر","مالك المخاطر","تاريخ تحديد المخاطر","وصف المخاطر","سبب المخاطر","التهديد","تحليل المخاطر وعواقبها","تاريخ تحليل وتقييم المخاطر","احتمالية المخاطر الكامنة (1-5)","حجم/أثر المخاطر الكامنة (1-5)","التصنيف الكلّي للمخاطر الكامنة","التصنيف الكلّي المحدث للمخاطر الكامنة (إمكانية التجاوز يدويًا)","نوع إجراء المعالجة","وصف معالجة المخاطر","مالك إجراء المعالجة","الموعد النهائي للإجراء","وصف المخاطر المتبقية","احتمالية المخاطر المتبقية (1-5)","حجم/أثر المخاطر المتبقية (1-5)","التصنيف الكلّي للمخاطر المتبقية","وصف الخطوات التالية","تاريخ آخر تقييم","الملاحظات"];const rows=items.map(r=>[r.risk_code,scopeLabels[r.risk_scope],r.risk_owner,r.identification_date,r.risk_description,r.risk_cause,r.threat,r.risk_analysis,r.assessment_date,r.inherent_likelihood,r.inherent_impact,ratingLabels[rating(r.inherent_score)],r.inherent_override?ratingLabels[r.inherent_override]:"لا ينطبق",treatmentLabels[r.treatment_type],r.treatment_description,r.treatment_owner,r.action_due_date||"",r.residual_risk_description,r.residual_likelihood,r.residual_impact,ratingLabels[rating(r.residual_score)],r.next_steps,r.last_assessment_date,r.notes||""]);const csv="\ufeff"+[headers,...rows].map(row=>row.map(csvCell).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`NCA-Cyber-Risk-Register-${currentDate}.csv`;a.click();URL.revokeObjectURL(a.href)}
 if(loading)return <main className="workflow-page" dir="rtl"><p>جاري تحميل سجل المخاطر…</p></main>;
 const inherentScore=Number(form.inherent_likelihood)*Number(form.inherent_impact),residualScore=Number(form.residual_likelihood)*Number(form.residual_impact);
 return <main className="workflow-page" dir="rtl"><WorkflowHeading title="سجل مخاطر الأمن السيبراني" description="مطابق لحقول نموذج NCA الرسمي ومنهجية المخاطر الكامنة والمعالجة والمخاطر المتبقية." action={<div className="third-party-actions"><button className="workflow-button" onClick={exportNca} disabled={!items.length}>تصدير سجل NCA</button>{role!=="control_owner"&&<button className="workflow-button workflow-primary" onClick={()=>setShowForm(v=>!v)}>+ تسجيل خطر</button>}</div>}/>
 {error&&<p className="cgp-shell-error" role="alert">{error}</p>}{message&&<p className="workflow-success" role="status">{message}</p>}
 <div className="workflow-metrics"><WorkflowMetric label="إجمالي المخاطر" value={items.length}/><WorkflowMetric label="حرجة كامنة" value={items.filter(r=>rating(r.inherent_score)==="critical").length} tone="danger"/><WorkflowMetric label="حرجة متبقية" value={items.filter(r=>rating(r.residual_score)==="critical").length} tone="danger"/><WorkflowMetric label="إجراءات متأخرة" value={overdue} tone={overdue?"danger":"neutral"}/></div>
 {showForm&&<form className="risk-register-form" onSubmit={submit}><header><h2>تسجيل خطر جديد</h2><p>تتبع الحقول ترتيب سجل المخاطر المنشور ضمن أدوات الأمن السيبراني للهيئة الوطنية للأمن السيبراني.</p></header>
 <h3 className="risk-section">تحديد وتحليل المخاطر</h3><div className="risk-fields"><label>رقم تعريف المخاطر<input required value={form.risk_code} onChange={e=>setForm({...form,risk_code:e.target.value})} placeholder="RISK-001"/></label><label>نطاق المخاطر<select value={form.risk_scope} onChange={e=>setForm({...form,risk_scope:e.target.value})}>{Object.entries(scopeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>مالك المخاطر<input required value={form.risk_owner} onChange={e=>setForm({...form,risk_owner:e.target.value})}/></label><label>تاريخ تحديد المخاطر<input type="date" required value={form.identification_date} onChange={e=>setForm({...form,identification_date:e.target.value})}/></label><label className="wide">وصف المخاطر<textarea required rows={3} value={form.risk_description} onChange={e=>setForm({...form,risk_description:e.target.value})}/></label><label className="wide">سبب المخاطر<textarea required rows={3} value={form.risk_cause} onChange={e=>setForm({...form,risk_cause:e.target.value})}/></label><label>التهديد<input required value={form.threat} onChange={e=>setForm({...form,threat:e.target.value})}/></label><label>تاريخ تحليل وتقييم المخاطر<input type="date" required value={form.assessment_date} onChange={e=>setForm({...form,assessment_date:e.target.value})}/></label><label className="wide">تحليل المخاطر وعواقبها<textarea required rows={3} value={form.risk_analysis} onChange={e=>setForm({...form,risk_analysis:e.target.value})}/></label></div>
 <h3 className="risk-section">المخاطر الكامنة</h3><div className="risk-fields"><label>احتمالية المخاطر الكامنة (1–5)<select value={form.inherent_likelihood} onChange={e=>setForm({...form,inherent_likelihood:e.target.value})}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v} — {likelihoodLabels[v]}</option>)}</select></label><label>حجم/أثر المخاطر الكامنة (1–5)<select value={form.inherent_impact} onChange={e=>setForm({...form,inherent_impact:e.target.value})}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v} — {impactLabels[v]}</option>)}</select></label><label>التصنيف المحدث يدويًا<select value={form.inherent_override} onChange={e=>setForm({...form,inherent_override:e.target.value})}><option value="">لا ينطبق</option>{Object.entries(ratingLabels).filter(([v])=>v!=="not_applicable").map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><small>يُستخدم فقط إذا اعتمد مالك المخاطر تجاوز التصنيف المحسوب.</small></label></div><div className={`risk-score-card ${rating(inherentScore)}`}><span>التصنيف الكلّي للمخاطر الكامنة</span><strong>{inherentScore}/25</strong><b>{ratingLabels[rating(inherentScore)]}</b></div>
 <h3 className="risk-section">معالجة المخاطر</h3><div className="risk-fields"><label>نوع إجراء المعالجة<select value={form.treatment_type} onChange={e=>setForm({...form,treatment_type:e.target.value})}>{Object.entries(treatmentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>مالك إجراء المعالجة<input required value={form.treatment_owner} onChange={e=>setForm({...form,treatment_owner:e.target.value})}/></label><label>الموعد النهائي للإجراء<input type="date" value={form.action_due_date} onChange={e=>setForm({...form,action_due_date:e.target.value})}/></label><label className="wide">وصف معالجة المخاطر<textarea required rows={3} value={form.treatment_description} onChange={e=>setForm({...form,treatment_description:e.target.value})}/></label></div>
 <h3 className="risk-section">المخاطر المتبقية والمتابعة</h3><div className="risk-fields"><label className="wide">وصف المخاطر المتبقية<textarea required rows={3} value={form.residual_risk_description} onChange={e=>setForm({...form,residual_risk_description:e.target.value})}/></label><label>احتمالية المخاطر المتبقية (1–5)<select value={form.residual_likelihood} onChange={e=>setForm({...form,residual_likelihood:e.target.value})}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v} — {likelihoodLabels[v]}</option>)}</select></label><label>حجم/أثر المخاطر المتبقية (1–5)<select value={form.residual_impact} onChange={e=>setForm({...form,residual_impact:e.target.value})}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v} — {impactLabels[v]}</option>)}</select></label><label className="wide">وصف الخطوات التالية<textarea required rows={3} value={form.next_steps} onChange={e=>setForm({...form,next_steps:e.target.value})}/></label><label>تاريخ آخر تقييم<input type="date" required value={form.last_assessment_date} onChange={e=>setForm({...form,last_assessment_date:e.target.value})}/></label><label className="wide">الملاحظات<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className={`risk-score-card ${rating(residualScore)}`}><span>التصنيف الكلّي للمخاطر المتبقية</span><strong>{residualScore}/25</strong><b>{ratingLabels[rating(residualScore)]}</b></div><div className="third-party-actions"><button disabled={saving} className="workflow-button workflow-primary">{saving?"جاري الحفظ…":"حفظ الخطر"}</button><button type="button" className="workflow-button" onClick={()=>setShowForm(false)}>إلغاء</button></div></form>}
 <section className="risk-analytics" aria-label="تحليل المخاطر"><article className="risk-panel"><h2>المخاطر الكليّة</h2><p>مقارنة التصنيف الكامن بالمخاطر المتبقية بعد المعالجة.</p>{levels.map(level=><div className="risk-total-row" key={level}><span>{ratingLabels[level]}</span><div className="risk-total-bar inherent"><span style={{width:`${items.length?levelCount("inherent",level)/items.length*100:0}%`}}/></div><b>{levelCount("inherent",level)}</b><div className="risk-total-bar residual"><span style={{width:`${items.length?levelCount("residual",level)/items.length*100:0}%`}}/></div><b className="residual-count">{levelCount("residual",level)}</b></div>)}<div className="risk-legend"><span><i/>كامنة</span><span><i/>متبقية</span></div></article><article className="risk-panel"><h2>المخطط الحراري</h2><p>توزيع المخاطر وفق مصفوفة NCA: الاحتمالية × الأثر.</p><div className="risk-heatmaps">{(["inherent","residual"] as const).map(kind=><div key={kind}><div className="risk-heatmap-title">{kind==="inherent"?"المخاطر الكامنة":"المخاطر المتبقية"}</div><div className="risk-heatmap"><span/>{[1,2,3,4,5].map(v=><span className="risk-heatmap-label" key={v}>{v}</span>)}{[5,4,3,2,1].flatMap(impact=>[<span className="risk-heatmap-label" key={`l-${impact}`}>{impact}</span>,...[1,2,3,4,5].map(likelihood=><span className={`risk-heatmap-cell ${rating(likelihood*impact)}`} key={`${impact}-${likelihood}`}>{heatCount(kind,likelihood,impact)}</span>)])}</div><div className="risk-heatmap-axis">الاحتمالية ← | الأثر ↑</div></div>)}</div></article></section>
 <div className="workflow-filter workflow-filter-grid"><label>البحث<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="رقم الخطر، الوصف، التهديد أو المالك"/></label><label>نطاق المخاطر<select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">جميع النطاقات</option>{Object.entries(scopeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><ResultSummary count={visible.length} total={items.length} active={Boolean(search)||scope!=="all"} reset={()=>{setSearch("");setScope("all")}}/>
 {!visible.length?<div className="workflow-empty">لا توجد مخاطر مطابقة في السجل.</div>:<div className="risk-table-wrap"><table className="risk-table"><thead><tr><th>الخطر</th><th>النطاق</th><th>الكامن</th><th>المعالجة</th><th>المتبقي</th><th>المالك والموعد</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><b dir="ltr">{r.risk_code}</b><strong>{r.risk_description}</strong><small>{r.threat}</small></td><td>{scopeLabels[r.risk_scope]}</td><td><span className={`risk-pill ${rating(r.inherent_score)}`}>{ratingLabels[rating(r.inherent_score)]} · {r.inherent_score}/25</span></td><td>{treatmentLabels[r.treatment_type]}</td><td><span className={`risk-pill ${rating(r.residual_score)}`}>{ratingLabels[rating(r.residual_score)]} · {r.residual_score}/25</span></td><td className={r.action_due_date&&r.action_due_date<currentDate&&r.residual_score>3?"risk-overdue":""}>{r.risk_owner}<small>{r.action_due_date||"بدون موعد"}</small></td></tr>)}</tbody></table></div>}
 </main>
}
