"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type Control={id:number;domain_ar:string;implementation_status:string;evidence_status:string;verification_status:string;due_date:string|null};
type Evidence={status:string|null};
const good=(v:string|null|undefined)=>["implemented","compliant","accepted","approved","verified","uploaded"].includes((v||"").toLowerCase());
const progress=(v:string|null|undefined)=>["in_progress","pending_review","under_review"].includes((v||"").toLowerCase());

export default function ExecutivePage(){
 const router=useRouter(); const [loading,setLoading]=useState(true); const [controls,setControls]=useState<Control[]>([]); const [evidence,setEvidence]=useState<Evidence[]>([]); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:s}=await supabase.auth.getSession();if(!s.session){router.replace("/login");return;}const {data:p}=await supabase.from("profiles").select("role,is_active").eq("user_id",s.session.user.id).maybeSingle();if(!p||p.is_active===false||!["admin","cybersecurity_team"].includes(p.role)){router.replace("/");return;}const [{data:c,error:ce},{data:e,error:ee}]=await Promise.all([supabase.from("controls").select("id,domain_ar,implementation_status,evidence_status,verification_status,due_date"),supabase.from("evidence").select("status")]);if(ce||ee){setError(ce?.message||ee?.message||"تعذر تحميل اللوحة التنفيذية");setLoading(false);return;}setControls((c??[]) as Control[]);setEvidence((e??[]) as Evidence[]);setLoading(false)})()},[router]);
 const metrics=useMemo(()=>{const now=new Date();const total=controls.length;const compliant=controls.filter(c=>good(c.implementation_status)).length;const verified=controls.filter(c=>good(c.verification_status)).length;const overdue=controls.filter(c=>c.due_date&&new Date(c.due_date)<now&&!good(c.implementation_status)).length;const pendingEvidence=evidence.filter(e=>progress(e.status)).length;const compliance=total?Math.round(compliant/total*100):0;const verification=total?Math.round(verified/total*100):0;return{total,compliant,verified,overdue,pendingEvidence,compliance,verification}},[controls,evidence]);
 const domains=useMemo(()=>{const m=new Map<string,{name:string,total:number,done:number,overdue:number}>();const now=new Date();controls.forEach(c=>{const n=c.domain_ar||"غير مصنف";const r=m.get(n)||{name:n,total:0,done:0,overdue:0};r.total++;if(good(c.implementation_status))r.done++;if(c.due_date&&new Date(c.due_date)<now&&!good(c.implementation_status))r.overdue++;m.set(n,r)});return [...m.values()].sort((a,b)=>(b.done/b.total)-(a.done/a.total))},[controls]);
 if(loading)return <main dir="rtl" style={center}>جاري تحميل اللوحة التنفيذية...</main>;
 const riskLevel=metrics.overdue>10?"مرتفع":metrics.overdue>0?"متوسط":"منخفض";
 return <main dir="rtl" style={page}>
  <header style={header}><div><div style={{fontSize:25,fontWeight:800}}>Cyber Governance Platform</div><div style={{fontSize:13,opacity:.72,marginTop:5}}>Executive Governance Dashboard</div></div><div style={{display:"flex",gap:10}}><button onClick={()=>window.print()} style={headerButton}>طباعة</button><Link href="/reports" style={headerLink}>التقارير</Link><Link href="/" style={headerLink}>التشغيلية</Link></div></header>
  <section style={{maxWidth:1380,margin:"0 auto",padding:"38px 30px 60px"}}>
   <div style={{display:"flex",justifyContent:"space-between",gap:24,flexWrap:"wrap",alignItems:"flex-end",marginBottom:28}}><div><div style={eyebrow}>EXECUTIVE VIEW · NCA ECC</div><h1 style={h1}>لوحة الحوكمة التنفيذية</h1><p style={muted}>نظرة قيادية مختصرة على مستوى الالتزام والمخاطر والتقدم في دورة التقييم 2026.</p></div><div style={{background:riskLevel==="مرتفع"?"#fff0ee":riskLevel==="متوسط"?"#fff7e6":"#eaf7f1",color:riskLevel==="مرتفع"?"#a43b2d":riskLevel==="متوسط"?"#8a5a00":"#176b50",padding:"12px 18px",borderRadius:12,fontWeight:800}}>مستوى الانتباه: {riskLevel}</div></div>
   {error&&<div style={errorBox}>{error}</div>}
   <div style={heroGrid}>
    <div style={heroCard}><div style={{fontSize:14,opacity:.72}}>مستوى الالتزام العام</div><div style={{fontSize:64,fontWeight:900,margin:"14px 0 6px"}}>{metrics.compliance}%</div><div style={{opacity:.78}}>{metrics.compliant} من {metrics.total} ضابط</div><div style={{height:10,background:"rgba(255,255,255,.18)",borderRadius:99,marginTop:22,overflow:"hidden"}}><div style={{height:"100%",width:`${metrics.compliance}%`,background:"white"}}/></div></div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:16}}><Metric label="نسبة التحقق" value={`${metrics.verification}%`} note={`${metrics.verified} ضابط تم التحقق منها`}/><Metric label="ضوابط متأخرة" value={metrics.overdue} note="تحتاج متابعة فورية" danger={metrics.overdue>0}/><Metric label="أدلة بانتظار المراجعة" value={metrics.pendingEvidence} note="ضمن مسار المراجعة"/><Metric label="إجمالي الضوابط" value={metrics.total} note="نطاق دورة التقييم الحالية"/></div>
   </div>
   <div style={{display:"grid",gridTemplateColumns:"1.55fr .85fr",gap:20,alignItems:"start"}}>
    <div style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={sectionTitle}>التقدم حسب المجال</h2><span style={{fontSize:12,color:"#7a8794"}}>بيانات مباشرة من CGP</span></div>{domains.length===0?<div style={empty}>لا توجد بيانات بعد</div>:domains.map(d=>{const pct=d.total?Math.round(d.done/d.total*100):0;return <div key={d.name} style={{padding:"16px 0",borderBottom:"1px solid #edf0f2"}}><div style={{display:"flex",justifyContent:"space-between",gap:15,marginBottom:9}}><div><strong>{d.name}</strong><div style={{fontSize:12,color:"#7a8794",marginTop:4}}>{d.done}/{d.total} مكتمل · {d.overdue} متأخر</div></div><strong style={{color:"#0f7d73",fontSize:18}}>{pct}%</strong></div><div style={{height:9,background:"#edf1f3",borderRadius:99,overflow:"hidden"}}><div style={{height:"100%",width:`${pct}%`,background:pct>=80?"#0f7d73":pct>=50?"#b88319":"#b64a3b"}}/></div></div>})}</div>
    <div style={{display:"grid",gap:20}}><div style={card}><h2 style={sectionTitle}>ملخص الإدارة</h2><Insight title="الأولوية الأولى" text={metrics.overdue?`إغلاق ${metrics.overdue} ضابط متأخر قبل توسيع نطاق التحقق.`:"لا توجد ضوابط متأخرة حاليًا."}/><Insight title="الأدلة" text={metrics.pendingEvidence?`${metrics.pendingEvidence} دليل بانتظار المراجعة والقرار.`:"لا يوجد تراكم في مراجعة الأدلة."}/><Insight title="التحقق" text={`تم التحقق من ${metrics.verification}% من نطاق الضوابط الحالي.`}/></div><div style={{...card,background:"#0b1f33",color:"white"}}><div style={{fontSize:13,opacity:.65}}>الهدف التشغيلي التالي</div><div style={{fontSize:21,fontWeight:800,marginTop:10}}>رفع الالتزام والتحقق بالتوازي</div><p style={{lineHeight:1.8,opacity:.78,marginBottom:0}}>إغلاق المتأخرات، مراجعة الأدلة المعلقة، ثم تحويل الضوابط المكتملة إلى حالة تحقق نهائية.</p></div></div>
   </div>
  </section>
 </main>
}
function Metric({label,value,note,danger=false}:{label:string;value:string|number;note:string;danger?:boolean}){return <div style={{background:"white",border:"1px solid #e2e7eb",borderRadius:16,padding:22,minHeight:112}}><div style={{fontSize:13,color:"#7a8794"}}>{label}</div><div style={{fontSize:34,fontWeight:900,color:danger?"#b42318":"#0b1f33",margin:"9px 0 6px"}}>{value}</div><div style={{fontSize:12,color:"#7a8794"}}>{note}</div></div>}
function Insight({title,text}:{title:string;text:string}){return <div style={{padding:"14px 0",borderBottom:"1px solid #edf0f2"}}><div style={{fontSize:12,color:"#0f7d73",fontWeight:800,marginBottom:6}}>{title}</div><div style={{lineHeight:1.7,fontSize:14}}>{text}</div></div>}
const page={minHeight:"100vh",background:"#f5f7f9",fontFamily:"Arial, sans-serif",color:"#0b1f33"};const center={...page,display:"grid",placeItems:"center"};const header={minHeight:88,background:"#081a2c",color:"white",display:"flex",alignItems:"center",justifyContent:"space-between",gap:20,padding:"0 38px"};const headerLink={color:"white",textDecoration:"none",border:"1px solid rgba(255,255,255,.2)",borderRadius:9,padding:"9px 13px",fontSize:13};const headerButton={...headerLink,background:"transparent",cursor:"pointer"};const eyebrow={color:"#0f7d73",fontWeight:900,fontSize:12,letterSpacing:.8,marginBottom:8};const h1={fontSize:36,margin:0};const muted={color:"#7a8794",maxWidth:700,lineHeight:1.7};const heroGrid={display:"grid",gridTemplateColumns:"1.1fr 1.3fr",gap:20,marginBottom:20};const heroCard={background:"linear-gradient(135deg,#0f7d73,#0a5e58)",color:"white",borderRadius:18,padding:30,minHeight:195};const card={background:"white",border:"1px solid #e2e7eb",borderRadius:16,padding:24};const sectionTitle={fontSize:20,margin:0};const errorBox={background:"#fff2f0",color:"#9d2e24",padding:14,borderRadius:10,marginBottom:18};const empty={textAlign:"center" as const,color:"#7a8794",padding:35};
