"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { requireProfile, type UserRole } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import "./roadmap.css";

type Control = { id:number; control_code:string; title_ar:string; frameworks: { code:string; name_ar:string } | { code:string; name_ar:string }[] | null };
type Project = { id:number; project_code:string; name_ar:string; description_ar:string|null; planned_year:number; planned_quarter:string; status:"planned"|"in_progress"|"on_hold"|"completed"; priority:"high"|"medium"|"low"; executive_owner:string|null; solution_scope:string|null; framework_scope:string|null; target_outcome:string|null; recommended_technologies:string|null; actual_start_date:string|null; target_end_date:string|null; actual_end_date:string|null; progress_percent:number; notes:string|null; };
type LinkRow = { project_id:number; control_id:number; relationship_type:"primary"|"coverage"|"dependency"; controls:Control | Control[] | null };
type GapTreatment = { id:number; project_id:number; gap_title:string; treatment_type:"technology"|"procedure"|"policy"|"training"; recommendation:string; priority:"high"|"medium"|"low" };
const treatmentText={technology:"تقنية",procedure:"إجراء",policy:"وثيقة/سياسة",training:"تدريب"};
type Form = { project_code:string; name_ar:string; planned_year:number; planned_quarter:string; status:Project["status"]; priority:Project["priority"]; executive_owner:string; solution_scope:string; framework_scope:string; target_outcome:string; recommended_technologies:string; target_end_date:string; progress_percent:number; notes:string };
const emptyForm:Form={project_code:"",name_ar:"",planned_year:2027,planned_quarter:"Q1",status:"planned",priority:"medium",executive_owner:"",solution_scope:"",framework_scope:"",target_outcome:"",recommended_technologies:"",target_end_date:"",progress_percent:0,notes:""};
const statusText={planned:"مخطط",in_progress:"قيد التنفيذ",on_hold:"متوقف",completed:"مكتمل"};
const priorityText={high:"عالية",medium:"متوسطة",low:"منخفضة"};
const frameworkOf=(value:Control["frameworks"]|undefined)=>Array.isArray(value)?value[0]:value;

export default function RoadmapPage(){
 const router=useRouter(); const [role,setRole]=useState<UserRole>("control_owner"); const [projects,setProjects]=useState<Project[]>([]); const [controls,setControls]=useState<Control[]>([]); const [links,setLinks]=useState<LinkRow[]>([]); const [treatments,setTreatments]=useState<GapTreatment[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [selected,setSelected]=useState<Project|null>(null); const [form,setForm]=useState<Form>(emptyForm); const [controlId,setControlId]=useState(""); const [relationship,setRelationship]=useState<LinkRow["relationship_type"]>("coverage"); const [gapTitle,setGapTitle]=useState(""); const [treatmentType,setTreatmentType]=useState<GapTreatment["treatment_type"]>("technology"); const [recommendation,setRecommendation]=useState(""); const [treatmentPriority,setTreatmentPriority]=useState<GapTreatment["priority"]>("medium"); const canManage=role==="admin"||role==="cybersecurity_team";
 async function load(){const [p,c,l,t]=await Promise.all([supabase.from("cybersecurity_projects").select("*").order("planned_year").order("planned_quarter").order("project_code"),supabase.from("controls").select("id,control_code,title_ar,frameworks!inner(code,name_ar)").order("control_code"),supabase.from("cybersecurity_project_controls").select("project_id,control_id,relationship_type,controls(id,control_code,title_ar,frameworks(code,name_ar))"),supabase.from("cybersecurity_project_gap_treatments").select("id,project_id,gap_title,treatment_type,recommendation,priority").order("id")]); if(p.error)throw p.error; if(c.error)throw c.error; if(l.error)throw l.error; if(t.error)throw t.error; setProjects((p.data??[]) as Project[]);setControls((c.data??[]) as unknown as Control[]);setLinks((l.data??[]) as unknown as LinkRow[]);setTreatments((t.data??[]) as GapTreatment[]);}
 useEffect(()=>{let live=true;(async()=>{try{const {profile}=await requireProfile();if(!live)return;setRole(profile.role);await load();}catch(e){if(!live)return;const m=e instanceof Error?e.message:"";if(m.includes("تسجيل الدخول")){router.replace("/login");return;}setError(m.includes("cybersecurity_projects")||m.includes("schema cache")?"خارطة الطريق جاهزة في الواجهة وتنتظر تطبيق تحديث قاعدة البيانات.":m||"تعذر تحميل خارطة الطريق.");}finally{if(live)setLoading(false);}})();return()=>{live=false};},[router]);
 const linkedFor=(projectId:number)=>links.filter(link=>link.project_id===projectId);
 const treatmentsFor=(projectId:number)=>treatments.filter(treatment=>treatment.project_id===projectId);
 const stats=useMemo(()=>({total:projects.length,planned:projects.filter(p=>p.status==="planned").length,active:projects.filter(p=>p.status==="in_progress").length,linked:new Set(links.map(l=>l.control_id)).size}),[projects,links]);
 const grouped=useMemo(()=>[2027,2028,2029].map(year=>({year,projects:projects.filter(p=>p.planned_year===year)})),[projects]);
 function startCreate(){setSelected(null);setForm(emptyForm);setOpen(true);setMessage("");}
 function openProject(project:Project){setSelected(project);setForm({project_code:project.project_code,name_ar:project.name_ar,planned_year:project.planned_year,planned_quarter:project.planned_quarter,status:project.status,priority:project.priority,executive_owner:project.executive_owner??"",solution_scope:project.solution_scope??"",framework_scope:project.framework_scope??"",target_outcome:project.target_outcome??"",recommended_technologies:project.recommended_technologies??"",target_end_date:project.target_end_date??"",progress_percent:Number(project.progress_percent)||0,notes:project.notes??""});setControlId("");setGapTitle("");setRecommendation("");setTreatmentType("technology");setTreatmentPriority("medium");setOpen(true);setMessage("");}
 async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");setMessage("");try{const {user}=await requireProfile(["admin","cybersecurity_team"]);const payload={...form,executive_owner:form.executive_owner||null,solution_scope:form.solution_scope||null,framework_scope:form.framework_scope||null,target_outcome:form.target_outcome||null,recommended_technologies:form.recommended_technologies||null,target_end_date:form.target_end_date||null,notes:form.notes||null,progress_percent:Number(form.progress_percent),updated_at:new Date().toISOString()};const result=selected?await supabase.from("cybersecurity_projects").update(payload).eq("id",selected.id):await supabase.from("cybersecurity_projects").insert({...payload,created_by:user.id});if(result.error)throw result.error;await load();setMessage(selected?"تم حفظ المشروع.":"تمت إضافة المشروع. يمكنك الآن ربط ضوابطه.");if(!selected)setOpen(false);}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ المشروع.");}finally{setSaving(false);}}
 async function addLink(){if(!selected||!controlId)return;setSaving(true);setError("");try{const {user}=await requireProfile(["admin","cybersecurity_team"]);const {error:linkError}=await supabase.from("cybersecurity_project_controls").upsert({project_id:selected.id,control_id:Number(controlId),relationship_type:relationship,created_by:user.id});if(linkError)throw linkError;await load();setControlId("");setMessage("تم ربط الضابط بالمشروع. حالة الامتثال لم تتغير.");}catch(e){setError(e instanceof Error?e.message:"تعذر ربط الضابط.");}finally{setSaving(false);}}
 async function removeLink(id:number){if(!selected)return;setSaving(true);const {error:removeError}=await supabase.from("cybersecurity_project_controls").delete().eq("project_id",selected.id).eq("control_id",id);if(removeError)setError("تعذر إلغاء الربط.");else{await load();setMessage("تم إلغاء الربط.");}setSaving(false);}
 async function addTreatment(){if(!selected||!gapTitle.trim()||!recommendation.trim())return;setSaving(true);setError("");try{const {user}=await requireProfile(["admin","cybersecurity_team"]);const {error:treatmentError}=await supabase.from("cybersecurity_project_gap_treatments").insert({project_id:selected.id,gap_title:gapTitle.trim(),treatment_type:treatmentType,recommendation:recommendation.trim(),priority:treatmentPriority,created_by:user.id});if(treatmentError)throw treatmentError;await load();setGapTitle("");setRecommendation("");setMessage("تمت إضافة معالجة الفجوة. لا تتغير حالة الالتزام إلا بعد الدليل والمراجعة.");}catch(e){setError(e instanceof Error?e.message:"تعذر إضافة معالجة الفجوة.");}finally{setSaving(false);}}
 async function removeTreatment(id:number){setSaving(true);const {error:removeError}=await supabase.from("cybersecurity_project_gap_treatments").delete().eq("id",id);if(removeError)setError("تعذر حذف معالجة الفجوة.");else{await load();setMessage("تم حذف معالجة الفجوة.");}setSaving(false);}
 if(loading)return <main className="roadmap-page" dir="rtl"><p className="roadmap-loading">جاري تحميل خارطة الطريق…</p></main>;
 return <main className="roadmap-page" dir="rtl"><section className="roadmap-shell"><header className="roadmap-hero"><div><span>المحفظة التنفيذية</span><h1>خارطة الطريق السيبرانية</h1><p>تابع المبادرات الاستراتيجية 2027–2029 واربط كل مشروع بالضوابط التي يغطيها.</p></div>{canManage&&<button className="roadmap-primary" onClick={startCreate}>+ مشروع جديد</button>}</header>
 {error&&<p className="roadmap-alert" role="alert">{error}</p>}{message&&<p className="roadmap-message" role="status">{message}</p>}
 <section className="roadmap-metrics" aria-label="مؤشرات خارطة الطريق"><Metric label="إجمالي المبادرات" value={stats.total}/><Metric label="مخططة" value={stats.planned} tone="muted"/><Metric label="قيد التنفيذ" value={stats.active} tone="active"/><Metric label="ضوابط مغطاة" value={stats.linked} tone="linked"/></section>
 <section className="roadmap-guidance"><div><strong>القرار التنفيذي</strong><p>يعرض المشروع تقدم التنفيذ، بينما يبقى تقييم الضابط مرتبطًا بالدليل والمراجعة فقط.</p></div><Link href="/controls">استعراض سجل الضوابط ←</Link></section>
 <section className="roadmap-timeline" aria-label="خارطة السنوات">{grouped.map(group=><div className="roadmap-year" key={group.year}><header><span>{group.year}</span><small>{group.projects.length} مبادرة</small></header><div className="roadmap-projects">{group.projects.length?group.projects.map(project=>{const projectLinks=linkedFor(project.id);return <article className="roadmap-card" key={project.id}><div className="roadmap-card-top"><span className={"roadmap-status "+project.status}>{statusText[project.status]}</span><b dir="ltr">{project.project_code}</b></div><h2>{project.name_ar}</h2><p>{project.target_outcome||"لم يحدد الناتج المستهدف بعد."}</p>{project.recommended_technologies&&<div className="roadmap-tech"><span>تقنيات مرشحة</span><small>{project.recommended_technologies}</small></div>}<div className="roadmap-meta"><span>{project.planned_quarter}</span><span>{priorityText[project.priority]} الأولوية</span><span>{projectLinks.length} ضوابط</span></div><div className="roadmap-progress"><i style={{width:Math.max(0,Math.min(100,project.progress_percent))+"%"}}/><span>{project.progress_percent}%</span></div><footer><span>{project.executive_owner||"مالك تنفيذي غير محدد"}</span><button onClick={()=>openProject(project)}>عرض وإدارة ←</button></footer></article>}):<p className="roadmap-empty">لا توجد مبادرات ضمن هذه السنة.</p>}</div></div>)}</section>
 </section>
 {open&&<div className="roadmap-dialog-backdrop" role="presentation" onMouseDown={()=>setOpen(false)}><section className="roadmap-dialog" role="dialog" aria-modal="true" aria-labelledby="roadmap-dialog-title" onMouseDown={e=>e.stopPropagation()}><header><div><span>{selected?"تفاصيل المشروع":"إضافة مشروع"}</span><h2 id="roadmap-dialog-title">{selected?.name_ar||"مبادرة سيبرانية جديدة"}</h2></div><button aria-label="إغلاق" onClick={()=>setOpen(false)}>×</button></header><form onSubmit={save} className="roadmap-form"><label>رمز المشروع<input required dir="ltr" disabled={!!selected} value={form.project_code} onChange={e=>setForm({...form,project_code:e.target.value.toUpperCase()})} placeholder="R-12"/></label><label>اسم المشروع<input required value={form.name_ar} onChange={e=>setForm({...form,name_ar:e.target.value})}/></label><label>السنة<select value={form.planned_year} onChange={e=>setForm({...form,planned_year:Number(e.target.value)})}>{[2027,2028,2029].map(y=><option key={y}>{y}</option>)}</select></label><label>الربع<select value={form.planned_quarter} onChange={e=>setForm({...form,planned_quarter:e.target.value})}>{["Q1","Q2","Q3","Q4"].map(q=><option key={q}>{q}</option>)}</select></label><label>الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Project["status"]})}>{Object.entries(statusText).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>الأولوية<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Project["priority"]})}>{Object.entries(priorityText).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>المالك التنفيذي<input value={form.executive_owner} onChange={e=>setForm({...form,executive_owner:e.target.value})}/></label><label>نسبة الإنجاز<input type="number" min="0" max="100" value={form.progress_percent} onChange={e=>setForm({...form,progress_percent:Number(e.target.value)})}/></label><label className="wide">نطاق الحلول<textarea rows={2} value={form.solution_scope} onChange={e=>setForm({...form,solution_scope:e.target.value})}/></label><label className="wide">الأطر المرتبطة<input value={form.framework_scope} onChange={e=>setForm({...form,framework_scope:e.target.value})}/></label><label className="wide">الناتج المستهدف<textarea rows={2} value={form.target_outcome} onChange={e=>setForm({...form,target_outcome:e.target.value})}/></label><label className="wide">تقنيات مرشحة لإغلاق الفجوات<textarea rows={2} value={form.recommended_technologies} onChange={e=>setForm({...form,recommended_technologies:e.target.value})}/></label><label className="wide">ملاحظات<textarea rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><footer><button type="button" onClick={()=>setOpen(false)}>إلغاء</button>{canManage&&<button className="roadmap-primary" disabled={saving}>{saving?"جاري الحفظ…":"حفظ المشروع"}</button>}</footer></form>
 {selected&&<section className="roadmap-treatments"><header><div><span>خطة إغلاق الفجوات</span><h3>الفجوات والمعالجات المقترحة</h3><p>المعالجة قد تكون تقنية أو إجراءً أو سياسة أو تدريبًا. لا ينعكس ذلك على الالتزام إلا بعد اعتماد الدليل.</p></div></header>{canManage&&<div className="roadmap-treatment-form"><input value={gapTitle} onChange={e=>setGapTitle(e.target.value)} placeholder="وصف الفجوة"/><select value={treatmentType} onChange={e=>setTreatmentType(e.target.value as GapTreatment["treatment_type"])}>{Object.entries(treatmentText).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={treatmentPriority} onChange={e=>setTreatmentPriority(e.target.value as GapTreatment["priority"])}>{Object.entries(priorityText).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><textarea value={recommendation} onChange={e=>setRecommendation(e.target.value)} placeholder="التقنية أو الإجراء المقترح لإغلاق الفجوة"/><button className="roadmap-primary" type="button" disabled={saving||!gapTitle.trim()||!recommendation.trim()} onClick={addTreatment}>إضافة معالجة</button></div>}<div className="roadmap-treatment-list">{treatmentsFor(selected.id).length?treatmentsFor(selected.id).map(treatment=><article key={treatment.id}><div><b>{treatment.gap_title}</b><p>{treatment.recommendation}</p></div><aside><span className={"roadmap-type "+treatment.treatment_type}>{treatmentText[treatment.treatment_type]}</span><small>{priorityText[treatment.priority]} الأولوية</small>{canManage&&<button type="button" onClick={()=>removeTreatment(treatment.id)} aria-label="حذف معالجة الفجوة">×</button>}</aside></article>):<p className="roadmap-empty">لم تسجل معالجات فجوات لهذا المشروع بعد.</p>}</div></section>}
 {selected&&<section className="roadmap-links"><header><div><span>نطاق الامتثال</span><h3>الضوابط المرتبطة</h3><p>الربط يوضح تغطية المشروع ولا يغير حالة تطبيق الضابط.</p></div></header>{canManage&&<div className="roadmap-add-link"><select value={controlId} onChange={e=>setControlId(e.target.value)}><option value="">اختر ضابطًا للربط</option>{controls.filter(control=>!linkedFor(selected.id).some(link=>link.control_id===control.id)).map(control=>{const fw=frameworkOf(control.frameworks);return <option key={control.id} value={control.id}>{fw?.code||"—"} · {control.control_code} — {control.title_ar}</option>})}</select><select value={relationship} onChange={e=>setRelationship(e.target.value as LinkRow["relationship_type"])}><option value="primary">ضابط رئيسي</option><option value="coverage">تغطية</option><option value="dependency">اعتمادية</option></select><button className="roadmap-primary" disabled={!controlId||saving} onClick={addLink} type="button">ربط الضابط</button></div>}<div className="roadmap-linked-list">{linkedFor(selected.id).length?linkedFor(selected.id).map(link=>{const control=Array.isArray(link.controls)?link.controls[0]:link.controls;const fw=frameworkOf(control?.frameworks);return <div key={link.control_id}><span><b dir="ltr">{fw?.code||"—"} · {control?.control_code}</b><strong>{control?.title_ar}</strong></span><small>{link.relationship_type==="primary"?"رئيسي":link.relationship_type==="dependency"?"اعتمادية":"تغطية"}</small>{canManage&&<button onClick={()=>removeLink(link.control_id)} aria-label="إلغاء الربط">×</button>}</div>}):<p>لم تربط ضوابط بهذا المشروع بعد.</p>}</div></section>}</section></div>}</main>;
}
function Metric({label,value,tone=""}:{label:string;value:number;tone?:string}){return <article className={"roadmap-metric "+tone}><span>{label}</span><strong>{value}</strong></article>}
