'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {cycleLabels,displayPercent} from '@/lib/assessment';
import {todayRiyadh} from '@/lib/grc';
type Summary={id:number;framework:string;framework_version:string;scope_name:string;status:string;total:number;assessed:number;not_applicable:number;compliant:number;compliance:number|null;completion:number|null;open_gaps:number;critical_gaps:number;overdue_actions:number;missing_data:number;pending_evidence:number;evidence_needing_refresh:number;improvement:number|null;due_date:string|null;next_review_date:string|null;approved_at:string|null};
export const assessmentPath=(code:string)=>({CSCC:'/assessments',DCC:'/dcc-assessment',TCC:'/tcc-assessment',OSMACC:'/osmacc-assessment'}[code]??'/assessments');
export default function AssessmentPortfolio({framework,view='all'}:{framework?:string;view?:'all'|'attention'|'schedule'}){
 const [rows,setRows]=useState<Summary[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[filter,setFilter]=useState('');
 useEffect(()=>{let active=true;void supabase.rpc('cgp_assessment_summary').then(r=>{if(active){setError(r.error?.message??'');setRows(r.data??[]);setLoading(false);}});return()=>{active=false;};},[]);
 const needsAttention=(r:Summary)=>r.missing_data>0||r.overdue_actions>0||r.critical_gaps>0||r.pending_evidence>0||r.status==='completed'||r.evidence_needing_refresh>0||!!(r.next_review_date&&r.next_review_date<=todayRiyadh())||!!(r.due_date&&r.due_date<todayRiyadh()&&!['approved','closed'].includes(r.status));
 const visible=rows.filter(r=>view==='all'||(view==='attention'?needsAttention(r):!!r.next_review_date)).filter(r=>(!framework||r.framework===framework)&&(!filter||(filter==='approved'?['approved','closed'].includes(r.status):filter==='attention'?needsAttention(r):!['approved','closed'].includes(r.status))));
 return <section className="workflow-card" dir="rtl"><h2>{view==='schedule'?'مواعيد إعادة تقييم الأطر':view==='attention'?'تقييمات تحتاج متابعة':'دورات قياس الالتزام حسب النطاق'}</h2><p>نتائج التقييمات المعتمدة مستقلة عن حالة التطبيق العامة للضابط. كل صف يمثل نطاقًا ودورة؛ لا يُحتسب متوسط بين نطاقات مختلفة.</p><label>عرض <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">جميع الدورات</option><option value="approved">المعتمدة</option><option value="progress">قيد العمل</option><option value="attention">تحتاج إجراءً</option></select></label>{error&&<p role="alert">تعذر تحميل مؤشرات التقييم: {error}</p>}{loading?<p>جاري تحميل التقييمات…</p>:!visible.length?<p>لا توجد دورات مطابقة ضمن صلاحياتك.</p>:<div style={{overflowX:'auto'}}><table className="workflow-table"><thead><tr><th>الإطار والنطاق</th><th>الحالة</th><th>الالتزام المعتمد</th><th>اكتمال الإدخال</th><th>الفجوات</th><th>{view==='schedule'?'موعد إعادة التقييم والإجراء':'الإجراء التالي'}</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><Link href={`${assessmentPath(r.framework)}?cycle=${r.id}`}>{r.framework} · {r.scope_name} · #{r.id}</Link><small style={{display:'block'}}>الإصدار {r.framework_version} {r.approved_at?`· اعتماد ${r.approved_at.slice(0,10)}`:''}</small></td><td>{cycleLabels[r.status]}</td><td>{displayPercent(r.compliance)}{r.improvement!==null&&<small style={{display:'block'}}>التغير عن الدورة السابقة: {r.improvement>=0?'+':''}{Math.round(r.improvement)} نقطة مئوية</small>}</td><td>{displayPercent(r.completion)} · {r.assessed}/{r.total}</td><td>{r.open_gaps} مفتوحة · {r.critical_gaps} حرجة · {r.overdue_actions} متأخرة</td><td>{view==='schedule'&&<p>{r.next_review_date}</p>}{r.evidence_needing_refresh>0?`${r.evidence_needing_refresh} دليل يحتاج تحديثًا`:r.status==='completed'?'بانتظار اعتماد':r.next_review_date&&r.next_review_date<todayRiyadh()?'إعادة تقييم مستحقة':r.due_date&&r.due_date<todayRiyadh()&&!['approved','closed'].includes(r.status)?'دورة متأخرة':r.missing_data?`${r.missing_data} متطلبًا يحتاج استكمالًا`:r.pending_evidence?`${r.pending_evidence} دليل ينتظر المراجعة`:'متابعة الدورة'}<br/><Link href={`${assessmentPath(r.framework)}?cycle=${r.id}`}>فتح المتطلبات والمعالجة ←</Link></td></tr>)}</tbody></table></div>}</section>;
}
