'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {requireProfile} from '@/lib/auth';
import {AssessmentCycle,AssessmentItem,AssessmentFinding,Person,assessmentLabels,cycleLabels,cycleColumns,assessmentMetrics,displayPercent,reviewLabels} from '@/lib/assessment';
import {EvidenceRecord,csvDownload,todayRiyadh} from '@/lib/grc';
import {WorkflowHeading,WorkflowMetric} from '@/components/WorkflowUI';
import AssessmentItemEditor from '@/components/AssessmentItemEditor';
import './assessment-workspace.css';

type Framework={id:number;code:string;version:string};
type System={id:number;name:string};
type LinkRow={item_id:number;evidence_id:number};
const actions:Record<string,[string,string][]>= {draft:[['start','بدء التقييم']],in_progress:[['collect','جمع الأدلة'],['submit','إرسال للمراجعة']],evidence_collection:[['submit','إرسال للمراجعة']],under_review:[['return','إعادة للاستكمال'],['complete','إكمال المراجعة']],completed:[['return','إعادة للمراجعة والاستكمال'],['approve','اعتماد النسخة']],approved:[['close','إغلاق الدورة'],['reassess','إنشاء إعادة تقييم']],closed:[['reassess','إنشاء إعادة تقييم']]};
export default function AssessmentWorkspace({frameworkCode}:{frameworkCode:string}){
 const [framework,setFramework]=useState<Framework|null>(null),[actor,setActor]=useState(''),[role,setRole]=useState('');
 const [cycles,setCycles]=useState<AssessmentCycle[]>([]),[selected,setSelected]=useState<number|null>(null),[items,setItems]=useState<AssessmentItem[]>([]),[people,setPeople]=useState<Person[]>([]),[systems,setSystems]=useState<System[]>([]);
 const [evidence,setEvidence]=useState<EvidenceRecord[]>([]),[links,setLinks]=useState<LinkRow[]>([]),[findings,setFindings]=useState<AssessmentFinding[]>([]),[projects,setProjects]=useState<{id:number;name_ar:string}[]>([]);
 const [loadedKey,setLoadedKey]=useState('');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0);
 const [search,setSearch]=useState(''),[domain,setDomain]=useState(''),[status,setStatus]=useState(''),[mode,setMode]=useState('operational'),[open,setOpen]=useState<number|null>(null),[page,setPage]=useState(0);
 const [newScope,setNewScope]=useState(''),[systemId,setSystemId]=useState(''),[due,setDue]=useState(''),[systemName,setSystemName]=useState(''),[systemCategory,setSystemCategory]=useState('نظام تقني إلكتروني');
 const [decisionReason,setDecisionReason]=useState(''),[nextDate,setNextDate]=useState('');
 const epoch=useRef(0); const cycle=cycles.find(c=>c.id===selected); const team=['admin','cybersecurity_team'].includes(role);
 useEffect(()=>{let active=true;void(async()=>{try{
  const {user,profile}=await requireProfile(['admin','cybersecurity_team','control_owner','nca_external_auditor']);
  const f=await supabase.from('frameworks').select('id,code,version').eq('code',frameworkCode).single();if(f.error)throw f.error;
  const c=await supabase.from('assessment_cycles').select(cycleColumns).eq('framework_id',f.data.id).order('id',{ascending:false});if(c.error)throw c.error;
  const isTeam=['admin','cybersecurity_team'].includes(profile.role);
  const [p,s,pr]=await Promise.all([isTeam?supabase.from('profiles').select('user_id,display_name,role').eq('is_active',true):Promise.resolve({data:[],error:null}),frameworkCode==='CSCC'&&isTeam?supabase.from('cscc_systems').select('id,name'):Promise.resolve({data:[],error:null}),supabase.from('cybersecurity_projects').select('id,name_ar').order('id')]);
  if(p.error||s.error||pr.error)throw p.error||s.error||pr.error;
  if(active){setActor(user.id);setRole(profile.role);setFramework(f.data);setCycles(c.data as AssessmentCycle[]);setSelected(prev=>(c.data??[]).some(x=>x.id===prev)?prev:(c.data??[]).find(x=>x.id===Number(new URLSearchParams(window.location.search).get('cycle')))?.id??c.data?.[0]?.id??null);setPeople(p.data??[]);setSystems(s.data??[]);setProjects(pr.data??[]);setError('');}
 }catch(e){if(active)setError(e instanceof Error?e.message:'تعذر تحميل التقييم. سجّل الدخول أو أعد المحاولة.');}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[frameworkCode,refresh]);
 useEffect(()=>{let active=true;const token=++epoch.current;if(!selected)return;void(async()=>{try{
  const [i,e]=await Promise.all([supabase.from('assessment_items').select('*').eq('cycle_id',selected).order('id'),supabase.rpc('grc_evidence_register')]);if(i.error||e.error)throw i.error||e.error;
  const ids=(i.data??[]).map(x=>x.id);const [l,f]=ids.length?await Promise.all([supabase.from('assessment_item_evidence').select('item_id,evidence_id').in('item_id',ids),supabase.from('assessment_findings').select('*').in('item_id',ids)]):[{data:[],error:null},{data:[],error:null}];if(l.error||f.error)throw l.error||f.error;
  if(active&&epoch.current===token){setItems(i.data??[]);setEvidence(e.data??[]);setLinks(l.data??[]);setFindings(f.data??[]);setLoadedKey(`${selected}:${refresh}`);}
 }catch(e){if(active&&epoch.current===token)setError(e instanceof Error?e.message:'تعذر تحميل المتطلبات');}finally{if(active&&epoch.current===token)setLoading(false);}})();return()=>{active=false;};},[selected,refresh]);
 const command=async(action:string,data:Record<string,unknown>={})=>{if(busy)return false;setBusy(true);setError('');setMessage('');try{
  const r=await supabase.rpc('cgp_assessment_command',{p_action:action,p_cycle:selected,p_data:{cycle_revision:cycle?.revision,...data}});if(r.error)throw r.error;
  setLoading(true);if(['create','reassess'].includes(action)){setSelected(r.data.id);setOpen(null);setPage(0);}setRefresh(v=>v+1);setMessage('تم حفظ الإجراء وتسجيله في سجل التدقيق.');return true;
 }catch(e){setError(e instanceof Error?e.message:typeof e==='object'&&e&&'message'in e?String(e.message):'تعذر تنفيذ الإجراء');return false;}finally{setBusy(false);}};
 const metrics=assessmentMetrics(items,!!cycle&&['approved','closed'].includes(cycle.status));
 const openGaps=findings.filter(f=>f.status!=='closed'); const overdue=openGaps.filter(f=>f.due_date&&f.due_date<todayRiyadh());
 const domains=[...new Set(items.map(i=>i.domain_ar))];
 const visible=items.filter(i=>(!domain||i.domain_ar===domain)&&(!search||`${i.control_code} ${i.title_ar} ${i.description_ar??''}`.toLowerCase().includes(search.toLowerCase()))&&(!status||(status==='unassessed'?!i.compliance_status:status==='scoring'?i.is_scoring:status==='changes_requested'?i.review_status===status:status==='gap'?openGaps.some(f=>f.item_id===i.id):status==='overdue'?overdue.some(f=>f.item_id===i.id):i.compliance_status===status)));
 const exportRows=()=>csvDownload(`${frameworkCode}-assessment-${selected}.csv`,[['الإطار','الإصدار','النطاق','الدورة','حالة الدورة','الرمز','المتطلب','داخل الحساب','النتيجة','قرار المراجعة','المبرر','المعالجة','الموعد'],...items.map(i=>[frameworkCode,cycle?.framework_version??'',cycle?.scope_name??'',selected??'',cycleLabels[cycle?.status??'']??'',i.control_code,i.description_ar||i.title_ar,i.is_scoring?'نعم':'للسياق فقط',assessmentLabels[i.compliance_status??'']??'لم يقيم',reviewLabels[i.review_status],i.notes??'',i.corrective_action??'',i.expected_compliance_date??''])]);
 return <main dir="rtl" className="workflow-page ae-page"><WorkflowHeading title={`تقييم وقياس الالتزام — ${frameworkCode}`} description="تقييمات مستقلة حسب النطاق، وأدلة مركزية، ومراجعة واعتماد محفوظان بالتاريخ."/>
 {error&&<p role="alert" className="ae-error">{error} <button onClick={()=>setRefresh(v=>v+1)}>إعادة المحاولة</button></p>}{message&&<p role="status" className="workflow-success">{message}</p>}
 <div className="ae-toolbar"><label>الدورة والنطاق<select disabled={busy} value={selected??''} onChange={e=>{setLoading(true);setItems([]);setOpen(null);setPage(0);setSelected(Number(e.target.value));setDomain('');setStatus('');setSearch('');}}><option value="">اختر دورة</option>{cycles.map(c=><option key={c.id} value={c.id}>#{c.id} · {c.scope_name} · {cycleLabels[c.status]} · {c.created_at.slice(0,10)}</option>)}</select></label><label>العرض<select value={mode} onChange={e=>setMode(e.target.value)}><option value="operational">تشغيلي</option>{role!=='control_owner'&&<option value="executive">تنفيذي</option>}</select></label><button disabled={!cycle||loading} onClick={exportRows}>تصدير CSV — Excel</button><button disabled={!cycle||loading} onClick={()=>window.print()}>طباعة / PDF</button></div>
 {team&&<details className="ae-card ae-no-print"><summary>إنشاء تقييم جديد {frameworkCode==='CSCC'?'أو إضافة نظام حساس':''}</summary><form className="ae-form-grid" onSubmit={e=>{e.preventDefault();void command('create',{framework_id:framework?.id,scope_name:newScope,system_id:systemId||null,due_date:due||null});}}><label>وصف النطاق<input required value={newScope} onChange={e=>setNewScope(e.target.value)} placeholder="الوحدة أو الخدمة والفترة المشمولة"/></label>{frameworkCode==='CSCC'&&<label>النظام الحساس<select required value={systemId} onChange={e=>setSystemId(e.target.value)}><option value="">اختر النظام</option>{systems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>الموعد<input type="date" value={due} onInput={e=>setDue(e.currentTarget.value)} onChange={e=>setDue(e.target.value)}/></label><button disabled={busy||!framework}>إنشاء مسودة</button></form>{frameworkCode==='CSCC'&&<form className="ae-form-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await supabase.from('cscc_systems').insert({name:systemName,system_category:systemCategory,asset_count:0}).select('id').single();setBusy(false);if(r.error)setError(r.error.message);else{setSystemId(String(r.data.id));setSystemName('');setRefresh(v=>v+1);}}}><label>اسم نظام جديد<input required minLength={2} value={systemName} onChange={e=>setSystemName(e.target.value)}/></label><label>تصنيف النظام<input required value={systemCategory} onChange={e=>setSystemCategory(e.target.value)}/></label><button disabled={busy}>إضافة النظام</button></form>}</details>}
 {(loading||(!error&&selected&&loadedKey!==`${selected}:${refresh}`))?<p role="status">جاري تحميل دورة التقييم…</p>:!cycle?<div className="workflow-empty">لا توجد دورة تقييم ضمن صلاحياتك. أنشئ مسودة أو اطلب التكليف من مدير الامتثال.</div>:<>
 <section className="ae-card"><div className="ae-heading"><div><h2>{cycle.scope_name}</h2><p>الإصدار {cycle.framework_version} · الدورة #{cycle.id} · <strong>{cycleLabels[cycle.status]}</strong>{cycle.imported?' · بيانات موروثة دون اعتماد سابق':''}</p></div><div><p>الاستحقاق: {cycle.due_date||'غير محدد'}</p><p>المراجعة القادمة: {cycle.next_review_date||'غير محددة'}</p></div></div>
 {!cycle.scope_confirmed_at&&<p className="ae-warning">وحدات الحساب المقترحة هي المتطلبات النهائية. راجع نطاق الحساب وأكّده قبل بدء التقييم.</p>}
 {team&&<><div className="ae-form-grid ae-no-print"><label>سبب القرار<input value={decisionReason} onChange={e=>setDecisionReason(e.target.value)} placeholder="مطلوب للإعادة والاعتماد والإغلاق"/></label><label>موعد إعادة التقييم<input type="date" value={nextDate} onInput={e=>setNextDate(e.currentTarget.value)} onChange={e=>setNextDate(e.target.value)}/></label></div><div className="ae-actions ae-no-print">{(actions[cycle.status]??[]).filter(([a])=>a==='reassess'||(['start','collect','submit'].includes(a)?actor===cycle.assessor_id:['return','complete'].includes(a)?actor===cycle.reviewer_id:actor===cycle.approver_id)).map(([a,l])=><button key={a} disabled={busy} className={a==='approve'?'cgp-primary-button':''} onClick={()=>void command(a,{reason:decisionReason,next_review_date:nextDate||null,due_date:nextDate||null})}>{l}</button>)}</div></>}
 </section>
 {team&&cycle.status==='draft'&&<CycleSetup key={`${cycle.id}-${cycle.revision}`} cycle={cycle} items={items} people={people} busy={busy} command={command}/>}
 <div className="workflow-metrics"><WorkflowMetric label="الالتزام المعتمد" value={displayPercent(metrics.compliance)} tone="success"/><WorkflowMetric label="اكتمال إدخال النتائج" value={displayPercent(metrics.completion)}/><button className="ae-metric" onClick={()=>{setStatus('unassessed');setMode('operational');setPage(0);}}>لم يُقيّم<strong>{metrics.unassessed}</strong></button><button className="ae-metric" onClick={()=>{setStatus('gap');setMode('operational');setPage(0);}}>فجوات مفتوحة<strong>{openGaps.length}</strong></button><button className="ae-metric" onClick={()=>{setStatus('overdue');setMode('operational');setPage(0);}}>معالجات متأخرة<strong>{overdue.length}</strong></button></div>
 <p className="ae-muted">{role==='control_owner'?'المعروض ضمن نطاق تكليفك فقط. ':''}الحساب: {metrics.total} متطلبًا داخل النطاق، {metrics.na} غير منطبق معتمد. النسبة المعتمدة = الممتثل المعتمد ÷ المنطبق. غير المقيم يبقى ضمن المقام. اكتمال الإدخال ليس امتثالًا. {metrics.compliance===null?'لا توجد نسبة معتمدة قابلة للاحتساب لهذه الدورة.':''}</p>
 {mode==='executive'?<section className="ae-card"><h2>ما الذي يحتاج قرارًا؟</h2><ul>{metrics.missing>0&&<li>{metrics.missing} متطلبًا يحتاج استكمال بيانات قبل المراجعة.</li>}{openGaps.filter(f=>f.severity==='critical').length>0&&<li>{openGaps.filter(f=>f.severity==='critical').length} فجوة حرجة مفتوحة.</li>}{cycle.status==='completed'&&<li>التقييم بانتظار قرار المعتمد.</li>}{cycle.next_review_date&&cycle.next_review_date<todayRiyadh()&&<li>حان موعد إعادة التقييم.</li>}{overdue.length>0&&<li>{overdue.length} معالجة تجاوزت موعدها.</li>}</ul><h3>الالتزام حسب المجال</h3>{domains.map(d=>{const m=assessmentMetrics(items.filter(i=>i.domain_ar===d),['approved','closed'].includes(cycle.status));return <button className="ae-domain" key={d} onClick={()=>{setDomain(d);setMode('operational');setPage(0);}}><span>{d}</span><span>الالتزام {displayPercent(m.compliance)} · إدخال {displayPercent(m.completion)}</span></button>;})}<p>لا يُستنتج تحسن تاريخي من مقارنة نطاقات أو إصدارات مختلفة. اختر دورة سابقة من أعلى الصفحة لعرض نتائجها المحفوظة.</p></section>:<>
 <div className="ae-toolbar"><label>بحث في كل النطاق<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="الرمز أو نص المتطلب"/></label><label>المجال<select value={domain} onChange={e=>{setDomain(e.target.value);setPage(0);}}><option value="">جميع المجالات</option>{domains.map(d=><option key={d}>{d}</option>)}</select></label><label>التصفية<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">جميع المتطلبات</option><option value="scoring">داخل الحساب</option><option value="unassessed">لم يُقيّم</option><option value="changes_requested">يحتاج استكمالًا</option><option value="gap">فجوات مفتوحة</option><option value="overdue">معالجات متأخرة</option>{Object.entries(assessmentLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div>
 <p role="status">عرض {Math.min(visible.length,page*15+15)} من {visible.length} متطلبًا</p><div className="ae-table-wrap ae-no-print"><table className="ae-table"><thead><tr><th>المتطلب</th><th>النتيجة</th><th>المراجعة</th><th>الأدلة</th><th>التفاصيل</th></tr></thead><tbody>{visible.slice(page*15,page*15+15).map(i=><ItemRow key={i.id} item={i} expanded={open===i.id} onOpen={()=>setOpen(open===i.id?null:i.id)} count={links.filter(l=>l.item_id===i.id).length}><AssessmentItemEditor key={`${i.id}-${i.revision}-${findings.find(f=>f.item_id===i.id)?.revision??0}`} item={i} cycle={cycle} people={people} projects={projects} evidence={[...new Map(evidence.filter(e=>e.control_id===i.control_id).map(e=>[e.id,e])).values()]} evidenceIds={links.filter(l=>l.item_id===i.id).map(l=>l.evidence_id)} finding={findings.find(f=>f.item_id===i.id)} actor={actor} role={role} busy={busy} command={command}/></ItemRow>)}</tbody></table></div><div className="ae-print-only"><table className="ae-table"><thead><tr><th>الضابط</th><th>المتطلب</th><th>النتيجة</th><th>المراجعة</th><th>المبرر والمعالجة</th></tr></thead><tbody>{visible.map(i=><tr key={i.id}><td dir="ltr">{i.control_code}</td><td>{i.description_ar||i.title_ar}{!i.is_scoring?' (للسياق فقط)':''}</td><td>{assessmentLabels[i.compliance_status??'']??'لم يقيم'}</td><td>{reviewLabels[i.review_status]}</td><td>{i.notes}<br/>{i.corrective_action}<br/>{i.expected_compliance_date}</td></tr>)}</tbody></table></div>{visible.length===0&&<p className="workflow-empty">لا توجد نتائج لهذه التصفية.</p>}<div className="ae-actions"><button disabled={page===0} onClick={()=>setPage(v=>v-1)}>السابق</button><span dir="ltr">{page+1} / {Math.max(1,Math.ceil(visible.length/15))}</span><button disabled={(page+1)*15>=visible.length} onClick={()=>setPage(v=>v+1)}>التالي</button></div>
 </>}
 </>}
 </main>;
}
function ItemRow({item,expanded,onOpen,count,children}:{item:AssessmentItem;expanded:boolean;onOpen:()=>void;count:number;children:React.ReactNode}){return <><tr><td><b dir="ltr">{item.control_code}</b><p>{item.description_ar||item.title_ar}</p>{!item.is_scoring&&<small>سياق تنظيمي — لا يدخل في النسبة</small>}</td><td>{assessmentLabels[item.compliance_status??'']??'لم يُقيّم'}</td><td>{reviewLabels[item.review_status]}</td><td>{count}</td><td><button aria-expanded={expanded} onClick={onOpen}>{expanded?'إغلاق':'فتح'}</button></td></tr>{expanded&&<tr><td colSpan={5}>{children}</td></tr>}</>;}
function CycleSetup({cycle,items,people,busy,command}:{cycle:AssessmentCycle;items:AssessmentItem[];people:Person[];busy:boolean;command:(a:string,d:Record<string,unknown>)=>Promise<boolean>}){
 const [assessor,setAssessor]=useState(cycle.assessor_id??''),[reviewer,setReviewer]=useState(cycle.reviewer_id??''),[approver,setApprover]=useState(cycle.approver_id??''),[due,setDue]=useState(cycle.due_date??''),[reason,setReason]=useState(cycle.scope_reason??'');const [ids,setIds]=useState(items.filter(i=>i.is_scoring).map(i=>i.id));
 const members=people.filter(p=>['admin','cybersecurity_team'].includes(p.role));
 return <details className="ae-card ae-no-print"><summary>إعداد المسؤوليات ونطاق الحساب</summary><form className="ae-form-grid" onSubmit={e=>{e.preventDefault();void command('configure',{assessor_id:assessor,reviewer_id:reviewer,approver_id:approver,due_date:due});}}>{([['المقيم',assessor,setAssessor],['المراجع',reviewer,setReviewer],['المعتمد',approver,setApprover]] as const).map(([label,value,set])=><label key={label}>{label}<select required value={value} onChange={e=>set(e.target.value)}><option value="">اختر المسؤول</option>{members.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label>)}<label>الموعد<input required type="date" value={due} onInput={e=>setDue(e.currentTarget.value)} onChange={e=>setDue(e.target.value)}/></label><button disabled={busy}>حفظ المسؤوليات</button></form><form onSubmit={e=>{e.preventDefault();void command('scope',{item_ids:ids,reason});}}><p>اختر وحدات القياس. لا يمكن احتساب الرئيسي وفرعه معًا. تبقى المتطلبات الأخرى ظاهرة للسياق.</p><div className="ae-scope">{items.map(i=><label key={i.id} className="ae-check"><input type="checkbox" checked={ids.includes(i.id)} onChange={e=>setIds(v=>e.target.checked?[...v,i.id]:v.filter(id=>id!==i.id))}/><b dir="ltr">{i.control_code}</b> {i.title_ar}</label>)}</div><label>مبرر النطاق<textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>تأكيد نطاق الحساب ({ids.length})</button></form></details>;
}
