'use client';
import { myControlsReturn } from '@/lib/my-controls-context';
import {Suspense,useEffect,useRef,useState} from 'react';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import {supabase} from '@/lib/supabase';
import {requireProfile} from '@/lib/auth';
import {AssessmentCycle,AssessmentItem,AssessmentFinding,Person,assessmentLabels,cycleLabels,assessmentMetrics,displayPercent,reviewLabels} from '@/lib/assessment';
import {csvDownload,todayRiyadh,formatComplianceDate} from '@/lib/grc';
import {WorkflowMetric} from '@/components/WorkflowUI';
import Link from 'next/link';
import {assessmentContext,assessmentItemHref,cycleActions,filterAssessmentItems,itemNeedsInput} from '@/lib/assessment-journey';
import {loadFrameworkCycles,loadAssessmentCycle,type ItemFindingSummary} from '@/lib/assessment-journey-read';
import AssessmentItemEditor from '@/components/AssessmentItemEditor';
import './assessment-workspace.css';

type Framework={id:number;code:string;version:string};
type System={id:number;name:string};
type LinkRow={item_id:number;evidence_id:number};
export default function AssessmentWorkspace({frameworkCode}:{frameworkCode:string}){
 return <Suspense fallback={<div role="status">جاري تحميل التقييم…</div>}><AssessmentWorkspaceContent frameworkCode={frameworkCode}/></Suspense>;
}
function AssessmentWorkspaceContent({frameworkCode}:{frameworkCode:string}){
 const router=useRouter(),pathname=usePathname(),searchParams=useSearchParams();
 const [framework,setFramework]=useState<Framework|null>(null),[actor,setActor]=useState(''),[role,setRole]=useState('');
 const [cycles,setCycles]=useState<AssessmentCycle[]>([]),[items,setItems]=useState<AssessmentItem[]>([]),[people,setPeople]=useState<Person[]>([]),[systems,setSystems]=useState<System[]>([]);
 const [links,setLinks]=useState<LinkRow[]>([]),[findings,setFindings]=useState<AssessmentFinding[]>([]),[sharedFindings,setSharedFindings]=useState<ItemFindingSummary[]>([]),[projects,setProjects]=useState<{id:number;name_ar:string}[]>([]);
 const [loadedKey,setLoadedKey]=useState('');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0);
 const [mode,setMode]=useState('operational');
 const context=assessmentContext(searchParams.toString()),search=context.get('q')??'',domain=context.get('domain')??'';
 const page=Math.max(0,Number(context.get('page')??1)-1);
 const updateFilter=(key:string,value:string)=>{const next=assessmentContext(searchParams.toString());next.delete('item');next.delete('page');if(value)next.set(key,value);else next.delete(key);if(selected)next.set('cycle',String(selected));router.replace(`${pathname}?${next}`,{scroll:false});};
 const [newScope,setNewScope]=useState(''),[systemId,setSystemId]=useState(''),[due,setDue]=useState(''),[systemName,setSystemName]=useState(''),[systemCategory,setSystemCategory]=useState('نظام تقني إلكتروني');
 const [decisionReason,setDecisionReason]=useState(''),[nextDate,setNextDate]=useState('');
 const requestedCycle=Number(searchParams.get('cycle'));
 const selected=searchParams.has('cycle')?cycles.find(c=>c.id===requestedCycle)?.id??null:cycles[0]?.id??null;
 const requestedItem=Number(searchParams.get('item'));
 const open=Number.isSafeInteger(requestedItem)&&requestedItem>0?requestedItem:null;
 const epoch=useRef(0); const cycle=cycles.find(c=>c.id===selected); const team=['admin','cybersecurity_team'].includes(role);
 useEffect(()=>{let active=true;void(async()=>{try{
  const {user,profile}=await requireProfile(['admin','cybersecurity_team','control_owner','nca_external_auditor']);
  const f=await supabase.from('frameworks').select('id,code,version').eq('code',frameworkCode).single();if(f.error)throw f.error;
  const c=await loadFrameworkCycles(f.data.id);
  const isTeam=['admin','cybersecurity_team'].includes(profile.role);
  const [p,s,pr]=await Promise.all([isTeam?supabase.from('profiles').select('user_id,display_name,role').eq('is_active',true):Promise.resolve({data:[],error:null}),frameworkCode==='CSCC'&&isTeam?supabase.from('cscc_systems').select('id,name'):Promise.resolve({data:[],error:null}),supabase.from('cybersecurity_projects').select('id,name_ar').order('id')]);
  if(p.error||s.error||pr.error)throw p.error||s.error||pr.error;
  if(active){setActor(user.id);setRole(profile.role);setFramework(f.data);setCycles(c);setPeople(p.data??[]);setSystems(s.data??[]);setProjects(pr.data??[]);setError('');}
 }catch{if(active)setError('تعذر تحميل التقييم. تحقق من تسجيل الدخول وصلاحياتك ثم أعد المحاولة.');}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[frameworkCode,refresh]);
 useEffect(()=>{let active=true;const token=++epoch.current;if(!selected)return;void(async()=>{try{
  const result=await loadAssessmentCycle(selected);
  if(active&&epoch.current===token){setItems(result.items);setLinks(result.links);setFindings(result.findings);setSharedFindings(result.sharedFindings);setLoadedKey(`${selected}:${refresh}`);setError('');}
 }catch{if(active&&epoch.current===token)setError('تعذر تحميل بنود الدورة ضمن صلاحياتك. أعد المحاولة.');}finally{if(active&&epoch.current===token)setLoading(false);}})();return()=>{active=false;};},[selected,refresh]);
 const command=async(action:string,data:Record<string,unknown>={})=>{if(busy)return false;setBusy(true);setError('');setMessage('');try{
  const r=await supabase.rpc('cgp_assessment_command',{p_action:action,p_cycle:selected,p_data:{cycle_revision:cycle?.revision,...data}});if(r.error)throw r.error;
  setLoading(true);if(['create','reassess'].includes(action)){router.push(`${pathname}?cycle=${r.data.id}`,{scroll:false});}setRefresh(v=>v+1);setMessage('تم حفظ الإجراء وتسجيله في سجل التدقيق.');return true;
 }catch{setError('لم يتم حفظ الإجراء. تحقق من اكتمال البيانات والتكليف واستقلالية المراجعة وصلاحية الأدلة، ثم أعد المحاولة.');return false;}finally{setBusy(false);}};
 const metrics=assessmentMetrics(items,!!cycle&&['approved','closed'].includes(cycle.status));
 const openGaps=findings.filter(f=>f.status!=='closed'); const overdue=openGaps.filter(f=>f.due_date&&f.due_date<todayRiyadh());
 const domains=[...new Set(items.map(i=>i.domain_ar))];
 const evidenceCounts=new Map<number,number>();for(const link of links)evidenceCounts.set(link.item_id,(evidenceCounts.get(link.item_id)??0)+1);
 const openFindingItems=new Set([...openGaps.map(f=>f.item_id),...sharedFindings.filter(f=>f.status!=='closed').map(f=>f.assessment_item_id)]);
 const visible=filterAssessmentItems(items,context,evidenceCounts,openFindingItems);
 const openedIndex=visible.findIndex(i=>i.id===open);
 const displayPage=Math.min(page,Math.max(0,Math.ceil(visible.length/15)-1));
 const itemHref=(itemId:number|null)=>assessmentItemHref(frameworkCode,selected??0,itemId,context.toString())??pathname;
 const changePage=(nextPage:number)=>{const next=assessmentContext(context.toString());next.delete('item');if(selected)next.set('cycle',String(selected));next.set('page',String(nextPage+1));router.push(`${pathname}?${next}`,{scroll:false});};
 const openedItem=items.find(i=>i.id===open);
 const availableActions=cycle?cycleActions(cycle,actor,role):[];
 const canContinue=!!cycle&&team&&actor===cycle.assessor_id&&['in_progress','evidence_collection'].includes(cycle.status)&&items.length>0&&items.some(i=>i.is_scoring&&(itemNeedsInput(i)||i.review_status==='changes_requested'));
 const primaryAction=cycle?.status==='closed'||canContinue?null:availableActions[0];
 const exportRows=()=>csvDownload(`${frameworkCode}-assessment-${selected}.csv`,[['الإطار','الإصدار','النطاق','الدورة','حالة الدورة','الرمز','المتطلب','داخل الحساب','النتيجة','قرار المراجعة','المبرر','المعالجة','الموعد'],...items.map(i=>[frameworkCode,cycle?.framework_version??'',cycle?.scope_name??'',selected??'',cycleLabels[cycle?.status??'']??'',i.control_code,i.description_ar||i.title_ar,i.is_scoring?'نعم':'للسياق فقط',assessmentLabels[i.compliance_status??'']??'لم يقيم',reviewLabels[i.review_status],i.notes??'',i.corrective_action??'',i.expected_compliance_date??''])]);
 if(!framework)return <div role={error?'alert':'status'}>{error||'جاري تحميل التقييم…'}</div>;
 return <div className="assessment-workspace-content">
 {error&&<p role="alert" className="ae-error">{error} <button onClick={()=>setRefresh(v=>v+1)}>إعادة المحاولة</button></p>}{message&&<p role="status" className="workflow-success">{message}</p>}
 {(loading||(selected&&loadedKey!==`${selected}:${refresh}`))?<p role={error?'alert':'status'}>{error?'لم تُحمّل الدورة؛ لن تُعرض بيانات دورة أخرى.':'جاري تحميل دورة التقييم…'}</p>:!cycle?<div className="workflow-empty">{searchParams.has('cycle')?'الدورة المطلوبة غير متاحة ضمن هذا الإطار وصلاحياتك.':'لا توجد دورة تقييم ضمن صلاحياتك. اطلب التكليف من مدير الامتثال أو أنشئ مسودة إن كنت مخولًا.'}</div>:<>
 {searchParams.has('item')&&!open?<p role="alert" className="workflow-empty">رابط البند غير صحيح. <Link href={itemHref(null)}>العودة إلى الدورة ←</Link></p>:open?openedItem?<AssessmentItemEditor key={`${openedItem.id}-${openedItem.revision}-${findings.find(f=>f.item_id===open)?.revision??0}`} item={openedItem} cycle={cycle} people={people} projects={projects} evidenceIds={links.filter(l=>l.item_id===open).map(l=>l.evidence_id)} finding={findings.find(f=>f.item_id===open)} actor={actor} role={role} busy={busy} command={command} context={context.toString()} returnHref={myControlsReturn(context)??(context.get('from')==='review'?'/review#assessment-review':itemHref(null))} previousHref={openedIndex>0?itemHref(visible[openedIndex-1].id):undefined} nextHref={openedIndex>=0&&openedIndex+1<visible.length?itemHref(visible[openedIndex+1].id):undefined} sharedCount={sharedFindings.filter(f=>f.assessment_item_id===open).length}/>:<div className="workflow-empty">البند غير متاح ضمن هذه الدورة وصلاحياتك. <Link href={itemHref(null)}>العودة إلى الدورة ←</Link></div>:<>
 <section className="ae-card ae-cycle-current" aria-label="الدورة الحالية">
 <div className="ae-heading"><div><h2>الدورة #{cycle.id}</h2><p className="ae-cycle-meta"><strong>{cycleLabels[cycle.status]}</strong><span>النطاق: {cycle.scope_name}</span>{cycle.system_id&&<span>النظام الحساس: {systems.find(s=>s.id===cycle.system_id)?.name||`#${cycle.system_id}`}</span>}{cycle.due_date&&<span>الاستحقاق: {formatComplianceDate(cycle.due_date)}</span>}{cycle.imported&&<span>بيانات موروثة دون اعتماد سابق</span>}{['under_review','completed','approved','closed'].includes(cycle.status)&&<span>قُبلت مراجعة {metrics.reviewed} من {metrics.total}</span>}</p></div>
 <div className="ae-actions ae-no-print">{canContinue?<Link className="cgp-primary-button ae-task-link" href={itemHref(items.find(i=>i.is_scoring&&(itemNeedsInput(i)||i.review_status==='changes_requested'))?.id??items[0].id)}>متابعة التقييم ←</Link>:primaryAction&&<button className="cgp-primary-button" disabled={busy||(primaryAction[0]==='start'&&(!cycle.scope_confirmed_at||!cycle.assessor_id||!cycle.reviewer_id||!cycle.approver_id||!cycle.due_date))} onClick={()=>void command(primaryAction[0],{reason:decisionReason,next_review_date:nextDate||null,due_date:nextDate||null})}>{primaryAction[1]}</button>}</div></div>
 <div className="ae-cycle-progress"><strong>تم تقييم {metrics.assessed} من {metrics.total}</strong><progress aria-label="اكتمال إدخال نتائج البنود ضمن النطاق المسموح" max={Math.max(metrics.total,1)} value={metrics.assessed}/><span dir="ltr">{displayPercent(metrics.completion)}</span><small>اكتمال الإدخال ليس نسبة امتثال.{role==='control_owner'?' المعروض ضمن نطاق تكليفك فقط.':''}</small></div>
 {!cycle.scope_confirmed_at&&<p className="ae-cycle-note">أكّد نطاق الحساب من إدارة الدورة قبل البدء.</p>}
 {primaryAction&&['approve','close'].includes(primaryAction[0])&&<label className="ae-no-print">مبرر القرار<input value={decisionReason} onChange={e=>setDecisionReason(e.target.value)} placeholder="مطلوب للاعتماد والإغلاق"/></label>}
 </section>
 <section className="ae-item-queue" aria-label="قائمة عمل بنود التقييم"><h2>بنود التقييم</h2><div className="ae-toolbar"><label>البحث<input value={search} onChange={e=>updateFilter('q',e.target.value)} placeholder="رمز الضابط أو نص المتطلب"/></label><label>المجال<select value={domain} onChange={e=>updateFilter('domain',e.target.value)}><option value="">جميع المجالات</option>{domains.map(d=><option key={d}>{d}</option>)}</select></label><label>النتيجة<select value={context.get('result')??''} onChange={e=>updateFilter('result',e.target.value)}><option value="">كل النتائج</option><option value="unassessed">لم يُقيّم</option>{Object.entries(assessmentLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>المراجعة<select value={context.get('review')??''} onChange={e=>updateFilter('review',e.target.value)}><option value="">كل الحالات</option>{Object.entries(reviewLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>الأدلة المرتبطة<select value={context.get('evidence')??''} onChange={e=>updateFilter('evidence',e.target.value)}><option value="">كل البنود</option><option value="linked">مع ارتباط دليل</option><option value="missing">دون ارتباط دليل</option></select></label><label>الاهتمام<select value={context.get('attention')??''} onChange={e=>updateFilter('attention',e.target.value)}><option value="">كل البنود</option><option value="input">تحتاج استكمالًا</option><option value="findings">مع ملاحظات / فجوات مفتوحة</option></select></label></div>
 <p role="status">{visible.length?`${displayPage*15+1}–${Math.min(visible.length,displayPage*15+15)} من ${visible.length}`:'0'} بندًا ضمن التصفية والصلاحيات</p><div className="ae-table-wrap ae-no-print"><table className="ae-table"><thead><tr><th>المتطلب</th><th>النتيجة</th><th>الأدلة</th><th>المراجعة</th><th>الحالة / الاهتمام</th></tr></thead><tbody>{visible.slice(displayPage*15,displayPage*15+15).map(i=><tr key={i.id}><td><Link href={itemHref(i.id)}><b dir="ltr">{i.control_code}</b><span className="ae-preview">{i.title_ar}</span></Link>{!i.is_scoring&&<small>للسياق فقط — خارج الحساب</small>}</td><td>{assessmentLabels[i.compliance_status??'']??'لم يُقيّم'}</td><td>{evidenceCounts.get(i.id)??0}</td><td>{reviewLabels[i.review_status]}</td><td>{itemNeedsInput(i)?'تحتاج استكمالًا':i.review_status==='changes_requested'?'مطلوب استكمال المراجعة':'مكتمل الإدخال'}{sharedFindings.some(f=>f.assessment_item_id===i.id)&&<small>{sharedFindings.filter(f=>f.assessment_item_id===i.id).length} ملاحظة مشتركة</small>}{findings.some(f=>f.item_id===i.id)&&<small>فجوة تقييم سابقة</small>}</td></tr>)}</tbody></table></div><div className="ae-print-only"><table className="ae-table"><thead><tr><th>الضابط</th><th>المتطلب</th><th>النتيجة</th><th>المراجعة</th><th>المبرر والمعالجة</th></tr></thead><tbody>{visible.map(i=><tr key={i.id}><td dir="ltr">{i.control_code}</td><td>{i.description_ar||i.title_ar}{!i.is_scoring?' (للسياق فقط)':''}</td><td>{assessmentLabels[i.compliance_status??'']??'لم يقيم'}</td><td>{reviewLabels[i.review_status]}</td><td>{i.notes}<br/>{i.corrective_action}<br/>{i.expected_compliance_date}</td></tr>)}</tbody></table></div>{visible.length===0&&<p className="workflow-empty">{items.length?'لا توجد بنود ضمن هذه التصفية.':'لا توجد بنود في الدورة ضمن صلاحياتك.'}</p>}<div className="ae-actions"><button disabled={displayPage===0} onClick={()=>changePage(displayPage-1)}>السابق</button><span dir="ltr">{displayPage+1} / {Math.max(1,Math.ceil(visible.length/15))}</span><button disabled={(displayPage+1)*15>=visible.length} onClick={()=>changePage(displayPage+1)}>التالي</button></div></section>
 </>}
 </>}
 {!open&&<details className="ae-card ae-cycle-admin ae-no-print"><summary>إدارة الدورة والمزيد</summary>
 <details className="ae-card ae-no-print"><summary>الدورات السابقة وخيارات العرض والتصدير</summary><div className="ae-toolbar"><label>الدورة والنطاق<select disabled={busy} value={selected??''} onChange={e=>{setLoading(true);setItems([]);router.push(`${pathname}?cycle=${e.target.value}`,{scroll:false});}}><option value="">اختر دورة</option>{cycles.map(c=><option key={c.id} value={c.id}>#{c.id} · {c.scope_name} · {cycleLabels[c.status]} · {formatComplianceDate(c.created_at)}</option>)}</select></label><label>العرض<select value={mode} onChange={e=>setMode(e.target.value)}><option value="operational">بنود التقييم</option>{role!=='control_owner'&&<option value="executive">ملخص المجالات والقرارات</option>}</select></label><button disabled={!cycle||loading} onClick={exportRows}>تصدير CSV — Excel</button><button disabled={!cycle||loading} onClick={()=>window.print()}>طباعة / PDF</button></div></details>
 {team&&!open&&<details className="ae-card ae-no-print"><summary>إنشاء تقييم جديد {frameworkCode==='CSCC'?'أو إضافة نظام حساس':''}</summary><form className="ae-form-grid" onSubmit={e=>{e.preventDefault();void command('create',{framework_id:framework?.id,scope_name:newScope,system_id:systemId||null,due_date:due||null});}}><label>وصف النطاق<input required value={newScope} onChange={e=>setNewScope(e.target.value)} placeholder="الوحدة أو الخدمة والفترة المشمولة"/></label>{frameworkCode==='CSCC'&&<label>النظام الحساس<select required value={systemId} onChange={e=>setSystemId(e.target.value)}><option value="">اختر النظام</option>{systems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>الموعد<input type="date" value={due} onInput={e=>setDue(e.currentTarget.value)} onChange={e=>setDue(e.target.value)}/></label><button disabled={busy||!framework}>إنشاء مسودة</button></form>{frameworkCode==='CSCC'&&<form className="ae-form-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await supabase.from('cscc_systems').insert({name:systemName,system_category:systemCategory,asset_count:0}).select('id').single();setBusy(false);if(r.error)setError('تعذر إضافة النظام. تحقق من البيانات وصلاحياتك.');else{setSystemId(String(r.data.id));setSystemName('');setRefresh(v=>v+1);}}}><label>اسم نظام جديد<input required minLength={2} value={systemName} onChange={e=>setSystemName(e.target.value)}/></label><label>تصنيف النظام<input required value={systemCategory} onChange={e=>setSystemCategory(e.target.value)}/></label><button disabled={busy}>إضافة النظام</button></form>}</details>}
 {cycle&&loadedKey===`${selected}:${refresh}`&&<>
 <details className="ae-muted"><summary>مسؤولو الدورة وتاريخها</summary>{cycle.next_review_date&&<p>المراجعة القادمة: {formatComplianceDate(cycle.next_review_date)}</p>}<p>نسخة الدورة: {cycle.framework_version} · أُنشئت {formatComplianceDate(cycle.created_at)}{cycle.approved_at?` · اعتُمدت ${formatComplianceDate(cycle.approved_at)}`:''}</p>{([['المقيم',cycle.assessor_id],['المراجع',cycle.reviewer_id],['المعتمد',cycle.approver_id]] as const).map(([label,id])=><p key={label}>{label}: {people.find(p=>p.user_id===id)?.display_name||(id?'مسؤول مكلّف — الاسم غير متاح ضمن هذا العرض':'غير معيّن')}</p>)}</details>
 {team&&cycle.status==='draft'&&<CycleSetup key={`${cycle.id}-${cycle.revision}`} cycle={cycle} items={items} people={people} busy={busy} command={command}/>}
 {availableActions.length>0&&<details className="ae-no-print"><summary>خيارات الدورة ومبرر القرار</summary><div className="ae-form-grid"><label>سبب القرار<input value={decisionReason} onChange={e=>setDecisionReason(e.target.value)} placeholder="مطلوب للإعادة والاعتماد والإغلاق"/></label><label>موعد إعادة التقييم<input type="date" value={nextDate} onChange={e=>setNextDate(e.target.value)}/></label></div><div className="ae-actions">{availableActions.filter(([a])=>a!==primaryAction?.[0]).map(([a,l])=><button key={a} disabled={busy} onClick={()=>void command(a,{reason:decisionReason,next_review_date:nextDate||null,due_date:nextDate||null})}>{l}</button>)}</div></details>}
 <details className="ae-no-print"><summary>ملخص النتائج المعتمدة ونطاق الحساب</summary>
 <div className="workflow-metrics"><WorkflowMetric label={`الالتزام المعتمد — دورة #${cycle.id}${role==='control_owner'?' / ضمن تكليفك':''}`} value={displayPercent(metrics.compliance)} tone="success"/><WorkflowMetric label="بنود قُبلت مراجعتها" value={`${metrics.reviewed} / ${metrics.total}`}/><WorkflowMetric label="فجوات تقييم سابقة مفتوحة" value={openGaps.length}/><WorkflowMetric label="معالجات سابقة متأخرة" value={overdue.length}/></div>
 <details className="ae-muted"><summary>نطاق حساب النسبة</summary><p>نطاق الدورة: {cycle.scope_name}. {metrics.total} متطلبًا داخل نطاقك المسموح، {metrics.na} غير منطبق معتمد. النسبة المعتمدة = الممتثل المعتمد ÷ المنطبق. غير المقيم يبقى ضمن المقام. {metrics.compliance===null?'لا توجد نسبة معتمدة قابلة للاحتساب لهذه الدورة.':''}</p></details>
 {mode==='executive'&&<section className="ae-card"><h2>ما الذي يحتاج قرارًا؟</h2><ul>{metrics.missing>0&&<li>{metrics.missing} متطلبًا يحتاج استكمال بيانات قبل المراجعة.</li>}{openGaps.filter(f=>f.severity==='critical').length>0&&<li>{openGaps.filter(f=>f.severity==='critical').length} فجوة حرجة مفتوحة.</li>}{cycle.status==='completed'&&<li>التقييم بانتظار قرار المعتمد.</li>}{cycle.next_review_date&&cycle.next_review_date<todayRiyadh()&&<li>حان موعد إعادة التقييم.</li>}{overdue.length>0&&<li>{overdue.length} معالجة تجاوزت موعدها.</li>}</ul><h3>الالتزام حسب المجال</h3>{domains.map(d=>{const m=assessmentMetrics(items.filter(i=>i.domain_ar===d),['approved','closed'].includes(cycle.status));return <button className="ae-domain" key={d} onClick={()=>{updateFilter('domain',d);setMode('operational');}}><span>{d}</span><span>الالتزام {displayPercent(m.compliance)} · إدخال {displayPercent(m.completion)}</span></button>;})}<p>لا يُستنتج تحسن تاريخي من مقارنة نطاقات أو إصدارات مختلفة. اختر دورة سابقة من إدارة الدورة لعرض نتائجها المحفوظة.</p></section>}
</details>
</>}
</details>}
 </div>;
}
function CycleSetup({cycle,items,people,busy,command}:{cycle:AssessmentCycle;items:AssessmentItem[];people:Person[];busy:boolean;command:(a:string,d:Record<string,unknown>)=>Promise<boolean>}){
 const [assessor,setAssessor]=useState(cycle.assessor_id??''),[reviewer,setReviewer]=useState(cycle.reviewer_id??''),[approver,setApprover]=useState(cycle.approver_id??''),[due,setDue]=useState(cycle.due_date??''),[reason,setReason]=useState(cycle.scope_reason??'');const [ids,setIds]=useState(items.filter(i=>i.is_scoring).map(i=>i.id));
 const members=people.filter(p=>['admin','cybersecurity_team'].includes(p.role));
 return <details className="ae-card ae-no-print"><summary>إعداد المسؤوليات ونطاق الحساب</summary><form className="ae-form-grid" onSubmit={e=>{e.preventDefault();void command('configure',{assessor_id:assessor,reviewer_id:reviewer,approver_id:approver,due_date:due});}}>{([['المقيم',assessor,setAssessor],['المراجع',reviewer,setReviewer],['المعتمد',approver,setApprover]] as const).map(([label,value,set])=><label key={label}>{label}<select required value={value} onChange={e=>set(e.target.value)}><option value="">اختر المسؤول</option>{members.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label>)}<label>الموعد<input required type="date" value={due} onInput={e=>setDue(e.currentTarget.value)} onChange={e=>setDue(e.target.value)}/></label><button disabled={busy}>حفظ المسؤوليات</button></form><form onSubmit={e=>{e.preventDefault();void command('scope',{item_ids:ids,reason});}}><p>اختر وحدات القياس. لا يمكن احتساب الرئيسي وفرعه معًا. تبقى المتطلبات الأخرى ظاهرة للسياق.</p><div className="ae-scope">{items.map(i=><label key={i.id} className="ae-check"><input type="checkbox" checked={ids.includes(i.id)} onChange={e=>setIds(v=>e.target.checked?[...v,i.id]:v.filter(id=>id!==i.id))}/><b dir="ltr">{i.control_code}</b> {i.title_ar}</label>)}</div><label>مبرر النطاق<textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>تأكيد نطاق الحساب ({ids.length})</button></form></details>;
}
