'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {type ReviewCycle,type EvidenceRequest,type EvidenceRecord,requestLabels,formatComplianceDate as formatGrcDate,isExpired} from '@/lib/grc';
import StatusBadge from './StatusBadge';
type Assessment={id:number;result:string;rationale:string;assessed_at:string;evidence_ids:number[]};
export default function ControlReviewPanel({controlId,canManage,canSubmit}:{controlId:number;canManage:boolean;canSubmit:boolean}){
 const [cycles,setCycles]=useState<ReviewCycle[]>([]),[requests,setRequests]=useState<EvidenceRequest[]>([]),[assessments,setAssessments]=useState<Assessment[]>([]),[evidence,setEvidence]=useState<EvidenceRecord[]>([]),[userId,setUserId]=useState('');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState('in_progress'),[reason,setReason]=useState(''),[nextDate,setNextDate]=useState(''),[selected,setSelected]=useState<number[]>([]);
 const load=useCallback(async()=>{const [c,r,a,e,u]=await Promise.all([supabase.from('control_review_cycles').select('*').eq('control_id',controlId).order('id',{ascending:false}),supabase.from('evidence_requests').select('*').eq('control_id',controlId).order('id',{ascending:false}),supabase.from('control_assessments').select('*').eq('control_id',controlId).order('id',{ascending:false}),supabase.rpc('grc_evidence_register'),supabase.auth.getUser()]);setError(c.error?.message||r.error?.message||a.error?.message||e.error?.message||'');setCycles(c.data??[]);setRequests(r.data??[]);setAssessments(a.data??[]);setEvidence(((e.data??[]) as EvidenceRecord[]).filter(x=>x.control_id===controlId));setUserId(u.data.user?.id??'');},[controlId]);
 useEffect(()=>{const t=setTimeout(()=>{void load();},0);return()=>clearTimeout(t);},[load]);
 const cycle=cycles.find(c=>c.status==='open');
 const eligible=evidence.filter(e=>e.is_current&&e.status==='accepted'&&!isExpired(e.valid_until)&&e.uploaded_by!==userId);
 async function assess(){if(!cycle||busy)return;setBusy(true);setError('');const r=await supabase.rpc('cgp_grc_command',{p_action:'assess',p_control_id:controlId,p_data:{cycle_id:cycle.id,result,reason,evidence_ids:selected,next_due_date:nextDate||null}});if(r.error)setError(r.error.message);else window.location.reload();setBusy(false);}
 async function cancel(requestId:number){if(!reason.trim()){setError('اكتب سبب إلغاء الطلب في حقل مبرر القرار أولًا.');return;}setBusy(true);const r=await supabase.rpc('cgp_grc_command',{p_action:'cancel_request',p_control_id:controlId,p_data:{request_id:requestId,reason}});setError(r.error?.message??'');if(!r.error)await load();setBusy(false);}
 return <section className="detail-card"><h2>دورة المراجعة وتقييم الضابط</h2><p className="detail-hint">قبول ملف يثبت ملاءمة الدليل. يُعتمد امتثال الضابط بقرار تقييم مستقل يحفظ التاريخ.</p>{error&&<p role="alert" className="cgp-shell-error">{error}</p>}
 {assessments[0]?<p>آخر تقييم معتمد: <StatusBadge status={assessments[0].result}/> · {formatGrcDate(assessments[0].assessed_at)}</p>:<p>لم يسجل تقييم وفق دورة المراجعة الجديدة بعد. الحالة السابقة محفوظة.</p>}
 {cycle?<p>دورة #{cycle.id} · الموعد: <b>{formatGrcDate(cycle.due_date)}</b></p>:<p>لا توجد دورة مراجعة مفتوحة. {canManage&&<Link href={`/audit-schedule?control=${controlId}`}>إنشاء دورة مراجعة</Link>}</p>}
 {requests.filter(r=>r.cycle_id===cycle?.id).map(r=><article className="control-evidence-item" key={r.id}><b>طلب #{r.id}: {r.requirement}</b><p>{requestLabels[r.status]} · {formatGrcDate(r.due_date)}</p>{['open','changes_requested','rejected'].includes(r.status)&&<>{canSubmit&&<Link className="detail-button" href={`/controls/${controlId}/evidence/new?request=${r.id}`}>تقديم الدليل</Link>}{canManage&&<button disabled={busy} onClick={()=>cancel(r.id)}>إلغاء الطلب بسبب موثق</button>}</>}</article>)}
 {cycle&&canManage&&<form className="grc-form" onSubmit={e=>{e.preventDefault();void assess();}}><label>نتيجة التقييم<select disabled={cycle.reviewer_id!==userId||busy} value={result} onChange={e=>setResult(e.target.value)}><option value="in_progress">مطبق جزئيًا</option><option value="implemented">مطبق كليًا</option><option value="not_implemented">غير مطبق</option><option value="not_applicable">غير منطبق بمبرر</option></select></label><label>مبرر القرار / سبب إلغاء الطلب<textarea required value={reason} onChange={e=>setReason(e.target.value)} rows={3}/></label><fieldset><legend>الأدلة المقبولة الداعمة للتقييم</legend>{!eligible.length&&<p>لا توجد أدلة حالية صالحة ومستقلة متاحة لك.</p>}{eligible.map(e=><label key={`${e.id}-${e.link_id}`}><input type="checkbox" checked={selected.includes(e.id)} onChange={event=>setSelected(prev=>event.target.checked?[...new Set([...prev,e.id])]:prev.filter(id=>id!==e.id))}/>{e.file_name} · إصدار {e.version_number}</label>)}</fieldset>{cycle.frequency==='custom'&&<label>موعد الدورة التالية<input required type="date" value={nextDate} onChange={e=>setNextDate(e.target.value)}/></label>}<button className="detail-button" disabled={busy||cycle.reviewer_id!==userId}>{busy?'جاري الحفظ…':'اعتماد التقييم وإغلاق الدورة'}</button>{cycle.reviewer_id!==userId&&<p>اعتماد التقييم متاح للمراجع المكلّف بهذه الدورة.</p>}</form>}
 {(cycles.length>1||assessments.length>0)&&<details><summary>الدورات والتقييمات السابقة</summary>{cycles.filter(c=>c.status!=='open').map(c=><p key={c.id}>الدورة #{c.id} · {formatGrcDate(c.completed_at)} · {c.notes}</p>)}{assessments.map(a=><p key={a.id}><StatusBadge status={a.result}/> {a.rationale} · {formatGrcDate(a.assessed_at)}</p>)}</details>}
 </section>;
}
