'use client';
import {useCallback,useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {formatComplianceDateTime,csvDownload,parseComplianceDateInput} from '@/lib/grc';
type Event={id:number;control_id:number|null;entity_type:string;entity_id:string;action:string;actor_name:string|null;actor_id:string|null;occurred_at:string;previous_data:Record<string,unknown>|null;new_data:Record<string,unknown>|null};
const entities:Record<string,string>={assessment_cycles:"دورة تقييم إطار",assessment_items:"نتيجة تقييم",assessment_item_evidence:"أدلة التقييم",assessment_findings:"فجوة ومعالجة",control_framework_links:"مواءمة الضوابط",controls:'الضابط',evidence:'الدليل',evidence_reviews:'قرار الدليل',evidence_control_links:'ربط دليل',evidence_control_link_reviews:'قرار دليل مشترك',control_review_cycles:'دورة المراجعة',evidence_requests:'طلب دليل',control_assessments:'تقييم الضابط',cybersecurity_projects:'مشروع سيبراني',cybersecurity_requirements:'متطلب سيبراني',cybersecurity_project_requirements:'ربط مشروع بمتطلب',cybersecurity_requirement_controls:'ربط متطلب بضابط'};
const actions:Record<string,string>={insert:'إنشاء',update:'تعديل',delete:'حذف',start:'بدء التقييم',collect:'جمع الأدلة',submit:'إرسال للمراجعة',return:'إعادة للاستكمال',complete:'إكمال المراجعة',approve:'اعتماد',close:'إغلاق'};
const fields:Record<string,string>={status:'الحالة',implementation_status:'حالة التطبيق',verification_status:'حالة التحقق',evidence_status:'حالة الدليل',control_owner_id:'معرف المالك',control_owner:'مالك الضابط',due_date:'موعد الاستحقاق',next_audit_date:'المراجعة القادمة',last_audit_date:'آخر مراجعة',review_notes:'سبب القرار',notes:'الملاحظات',result:'نتيجة التقييم',rationale:'مبرر التقييم',is_current:'الإصدار الحالي',reviewer_id:'المراجع',assigned_reviewer:'المراجع المكلف',valid_until:'الصلاحية',requirement:'المطلوب',evidence_ids:'الأدلة الداعمة',project_code:'رمز المشروع',requirement_code:'معرف المطلب الداخلي',name_ar:'الاسم',title_ar:'العنوان',initiative_type:'نوع المبادرة',coverage_type:'نوع التغطية',mapping_confidence:'جودة الربط',mapping_status:'حالة الربط',superseded_at:'تاريخ الاستبدال',superseded_reason:'سبب الاستبدال',supersedes_mapping_id:'الربط السابق',project_id:'المشروع',requirement_id:'المتطلب',control_id:'الضابط',planned_year:'السنة',planned_quarter:'الربع',priority:'الأولوية',executive_owner:'المالك التنفيذي',progress_percent:'نسبة الإنجاز'};
function changed(e:Event){return Object.keys({...e.previous_data,...e.new_data}).filter(key=>JSON.stringify(e.previous_data?.[key])!==JSON.stringify(e.new_data?.[key]));}
const show=(v:unknown)=>v==null?'—':typeof v==='object'?JSON.stringify(v):String(v);
export default function GrcAuditTrail({controlId}:{controlId?:number}){
 const [rows,setRows]=useState<Event[]>([]),[page,setPage]=useState(0),[kind,setKind]=useState(''),[since,setSince]=useState(''),[sinceInput,setSinceInput]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);let q=supabase.from('grc_audit_events').select('*').order('id',{ascending:false}).range(page*30,page*30+29);if(controlId)q=q.eq('control_id',controlId);if(kind)q=q.eq('entity_type',kind);if(since)q=q.gte('occurred_at',`${since}T00:00:00+03:00`);const r=await q;setError(r.error?.message??'');setRows(r.data??[]);setLoading(false);},[controlId,page,kind,since]);
 useEffect(()=>{const t=setTimeout(()=>{void load();},0);return()=>clearTimeout(t);},[load]);
 return <section className="workflow-card"><h2>سجل الأحداث التلقائي</h2><p>يبدأ السجل الشامل من تاريخ تفعيل الميزة. القرارات القديمة محفوظة في تاريخ الأدلة.</p><div className="workflow-filter"><label>نوع الحدث <select value={kind} onChange={e=>{setKind(e.target.value);setPage(0);}}><option value="">الكل</option>{Object.entries(entities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>من تاريخ <input type="text" inputMode="numeric" dir="ltr" placeholder="26/09/2026" value={sinceInput} onChange={e=>{const next=e.target.value;setSinceInput(next);const parsed=parseComplianceDateInput(next);if(!next||parsed){setSince(parsed??'');setPage(0);}}}/>{sinceInput&&!parseComplianceDateInput(sinceInput)&&<small role="status">اكتب التاريخ الميلادي بصيغة يوم/شهر/سنة، مثل 26/09/2026.</small>}</label><button className="workflow-button" onClick={()=>csvDownload('grc-audit-events.csv', [['الوقت','الضابط','الحدث','المستخدم','الحقول المتغيرة'],...rows.map(e=>[e.occurred_at,e.control_id??'',`${entities[e.entity_type]??e.entity_type} / ${actions[e.action]??e.action}`,e.actor_name??e.actor_id??'عملية نظام',changed(e).map(k=>fields[k]??k).join('،')])])}>تصدير الصفحة CSV</button></div>{error&&<p role="alert">{error}</p>}{loading?<p role="status">جاري التحميل…</p>:!rows.length?<p>لا توجد أحداث ضمن التصفية.</p>:rows.map(e=><details key={e.id} className="control-evidence-item"><summary>{entities[e.entity_type]??e.entity_type} · {actions[e.action]??e.action} · {e.actor_name??e.actor_id??'عملية نظام'} · <time dateTime={e.occurred_at}>{formatComplianceDateTime(e.occurred_at)}</time></summary><p>{e.control_id?`الضابط #${e.control_id} · `:''}الحدث #{e.id}</p><div style={{overflowX:'auto'}}><table className="workflow-table"><thead><tr><th>الحقل</th><th>قبل</th><th>بعد</th></tr></thead><tbody>{changed(e).map(k=><tr key={k}><td>{fields[k]??k}</td><td style={{overflowWrap:'anywhere'}}>{show(e.previous_data?.[k])}</td><td style={{overflowWrap:'anywhere'}}>{show(e.new_data?.[k])}</td></tr>)}</tbody></table></div></details>)}<div className="workflow-filter"><button disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>الأحدث</button><span>صفحة {page+1}</span><button disabled={rows.length<30||loading} onClick={()=>setPage(p=>p+1)}>الأقدم</button></div></section>;
}
