"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { requireProfile } from "@/lib/auth";
import { ResultSummary, WorkflowHeading, WorkflowMetric } from "@/components/WorkflowUI";

type Control={id:number;control_code:string;title_ar:string;description_ar:string|null;domain_ar:string;};
type Result={id?:number;control_id:number;compliance_status:string;notes:string|null;corrective_action:string|null;expected_compliance_date:string|null;};
const labels:Record<string,string>={implemented:"مطبق كليًا",partially_implemented:"مطبق جزئيًا",not_implemented:"غير مطبق",not_applicable:"لا ينطبق على الجهة"};
const domainNames=["حوكمة الأمن السيبراني","تعزيز الأمن السيبراني","الأمن السيبراني المتعلق بالأطراف الخارجية والحوسبة السحابية"];

export default function OsmaccAssessmentPage(){
 const router=useRouter();const [controls,setControls]=useState<Control[]>([]),[results,setResults]=useState<Result[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState<number|null>(null),[message,setMessage]=useState(""),[activeDomain,setActiveDomain]=useState(""),[activeSubdomain,setActiveSubdomain]=useState(""),[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState("all");
 useEffect(()=>{let active=true;(async()=>{try{await requireProfile(["admin","cybersecurity_team"]);const [{data:c,error},{data:r,error:re}]=await Promise.all([supabase.from("controls").select("id,control_code,title_ar,description_ar,domain_ar,frameworks!inner(code)").eq("frameworks.code","OSMACC").order("id"),supabase.from("osmacc_assessment_results").select("id,control_id,compliance_status,notes,corrective_action,expected_compliance_date")]);if(error||re)throw error||re;if(!active)return;setControls((c??[]) as unknown as Control[]);setResults((r??[]) as Result[]);}catch(e){const m=e instanceof Error?e.message:"";router.replace(m.includes("تسجيل الدخول")?"/login":"/");}finally{if(active)setLoading(false)}})();return()=>{active=false}},[router]);
 const map=useMemo(()=>new Map(results.map(r=>[r.control_id,r])),[results]);const counts=useMemo(()=>Object.fromEntries(Object.keys(labels).map(k=>[k,results.filter(r=>r.compliance_status===k).length])),[results]);
 const domains=useMemo(()=>Map.groupBy(controls,c=>c.domain_ar||"غير مصنف"),[controls]);
 const selectedDomain=activeDomain&&domains.has(activeDomain)?activeDomain:domainNames.find(d=>domains.has(d))||[...domains.keys()][0]||"";
 const domainControls=useMemo(()=>domains.get(selectedDomain)??[],[domains,selectedDomain]);
 const subdomains=useMemo(()=>Map.groupBy(domainControls,c=>c.control_code.split("-").slice(0,2).join("-")),[domainControls]);
 const selectedSubdomain=activeSubdomain&&subdomains.has(activeSubdomain)?activeSubdomain:[...subdomains.keys()][0]||"";
 const subdomainControls=useMemo(()=>subdomains.get(selectedSubdomain)??[],[subdomains,selectedSubdomain]);
 const visibleControls=subdomainControls.filter(c=>{const r=map.get(c.id);return `${c.control_code} ${c.title_ar} ${c.description_ar??""}`.toLowerCase().includes(search.trim().toLowerCase())&&(statusFilter==="all"||(statusFilter==="unassessed"?!r:r?.compliance_status===statusFilter));});
 async function save(controlId:number,patch:Partial<Result>){setSaving(controlId);const current=map.get(controlId);const status=patch.compliance_status??current?.compliance_status??"not_implemented";const payload={control_id:controlId,compliance_status:status,notes:patch.notes??current?.notes??null,corrective_action:patch.corrective_action??current?.corrective_action??null,expected_compliance_date:patch.expected_compliance_date??current?.expected_compliance_date??null,updated_at:new Date().toISOString()};const {data,error}=await supabase.from("osmacc_assessment_results").upsert(payload,{onConflict:"control_id"}).select("id,control_id,compliance_status,notes,corrective_action,expected_compliance_date").single();if(!error&&data)setResults(v=>[...v.filter(r=>r.control_id!==controlId),data as Result]);setMessage(error?"تعذر حفظ التقييم.":(status==="not_applicable"?"تم الحفظ. أضف سبب عدم الانطباق في الملاحظات.":["not_implemented","partially_implemented"].includes(status)?"تم الحفظ. أضف إجراءات التصحيح وتاريخ الالتزام المتوقع.":"تم حفظ نتيجة الضابط."));setSaving(null)}
 if(loading)return <main className="workflow-page" dir="rtl">جاري تحميل أداة OSMACC…</main>;
 const assessed=results.length,applicable=Math.max(assessed-counts.not_applicable,0),percent=applicable?Math.round(counts.implemented/applicable*100):0;
 return <main className="workflow-page" dir="rtl"><WorkflowHeading title="تقييم وقياس الالتزام — OSMACC" description="تطبيق رقمي لأداة NCA: قيّم ضوابط الأمن السيبراني لحسابات التواصل الاجتماعي للجهات OSMACC‑1:2021 ووثّق الأدلة والفجوات وخطة التصحيح."/>
 {message&&<p className="workflow-success" role="status">{message}</p>}<nav className="assessment-steps" aria-label="مراحل التقييم"><span className="active"><b>1</b> المكونات</span><span className="active"><b>2</b> المجالات الفرعية</span><span className="active"><b>3</b> تقييم الضوابط</span><span className="active"><b>4</b> ملخص الالتزام</span></nav>
 <section aria-labelledby="osmacc-summary"><div className="catalog-section-heading"><div><span>OSMACC-1:2021</span><h2 id="osmacc-summary">ملخص نتائج التقييم والالتزام</h2></div><small>{assessed} من {controls.length} ضابط تم تقييمه</small></div><div className="workflow-metrics"><WorkflowMetric label="مستوى الالتزام" value={`${percent}%`} tone="success"/><WorkflowMetric label="مطبق كليًا" value={counts.implemented}/><WorkflowMetric label="مطبق جزئيًا" value={counts.partially_implemented} tone="warning"/><WorkflowMetric label="غير مطبق" value={counts.not_implemented} tone="danger"/></div></section>
 <section aria-labelledby="osmacc-domains"><div className="catalog-section-heading"><div><span>المكونات الأساسية</span><h2 id="osmacc-domains">اختر المكون للتقييم</h2></div><small>{domains.size} مكونات</small></div><div className="assessment-domain-grid">{[...domains].map(([name,rows])=>{const done=rows.filter(c=>map.has(c.id)).length;return <button key={name} className={selectedDomain===name?"active":""} onClick={()=>{setActiveDomain(name);setActiveSubdomain("");setSearch("");setStatusFilter("all")}} aria-pressed={selectedDomain===name}><span><strong>{name}</strong><small>{done} من {rows.length} تم تقييمه</small></span><b>{rows.length?Math.round(done/rows.length*100):0}%</b><progress max={rows.length} value={done}/></button>})}</div></section>
 <section className="catalog-workspace" aria-labelledby="osmacc-controls"><div className="catalog-workspace-head"><div><span>تقييم الضوابط</span><h2 id="osmacc-controls">{selectedDomain}</h2><p>{domainControls.length} ضابط ضمن المكون</p></div></div><div className="assessment-subdomains" role="tablist" aria-label="المجالات الفرعية">{[...subdomains].map(([code,rows])=>{const done=rows.filter(c=>map.has(c.id)).length;return <button role="tab" aria-selected={selectedSubdomain===code} key={code} onClick={()=>{setActiveSubdomain(code);setSearch("");setStatusFilter("all")}}><b dir="ltr">{code}</b><span>{done}/{rows.length}</span></button>})}</div>
 <div className="workflow-filter workflow-filter-grid"><label>البحث داخل المجال الفرعي<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="رقم الضابط أو نصه"/></label><label>مستوى الالتزام<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">كل الحالات</option><option value="unassessed">لم يُقيّم</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div><ResultSummary count={visibleControls.length} total={subdomainControls.length} active={Boolean(search)||statusFilter!=="all"} reset={()=>{setSearch("");setStatusFilter("all")}}/>
 <div className="assessment-table"><div className="assessment-table-head"><span>الضابط</span><span>النص</span><span>مستوى الالتزام</span><span>التفاصيل</span></div>{visibleControls.map(c=>{const r=map.get(c.id);return <div className="assessment-row" key={c.id}><b dir="ltr">{c.control_code}</b><span className="assessment-title">{c.description_ar||c.title_ar}</span><label className="assessment-quick-status"><span className="sr-only">مستوى التزام {c.control_code}</span><select className={r?.compliance_status??"unassessed"} value={r?.compliance_status??""} onChange={e=>void save(c.id,{compliance_status:e.target.value})}><option value="">لم يُقيّم</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><details className="assessment-notes"><summary>{r?.notes||r?.corrective_action?"تعديل التفاصيل":"إضافة تفاصيل"}</summary><div className="assessment-fields"><label>الملاحظات والأدلة<textarea defaultValue={r?.notes??""} onBlur={e=>void save(c.id,{notes:e.target.value||null})} placeholder="الأدلة أو مبرر عدم انطباق الضابط"/></label><label>إجراءات التصحيح<textarea defaultValue={r?.corrective_action??""} onBlur={e=>void save(c.id,{corrective_action:e.target.value||null})} placeholder="الإجراء المطلوب لمعالجة الفجوة"/></label><label>تاريخ الالتزام المتوقع<input type="date" defaultValue={r?.expected_compliance_date??""} onBlur={e=>void save(c.id,{expected_compliance_date:e.target.value||null})}/></label>{saving===c.id&&<small>جاري الحفظ…</small>}</div></details></div>})}</div>{!visibleControls.length&&<div className="workflow-empty">لا توجد ضوابط مطابقة داخل هذا المجال الفرعي.</div>}</section>
 </main>;
}
