"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import "../roadmap.css";

type Project = { id:number; project_code:string; name_ar:string; planned_year:number; planned_quarter:string; status:"planned"|"in_progress"|"on_hold"|"completed"; priority:"high"|"medium"|"low"; executive_owner:string|null; target_outcome:string|null; target_end_date:string|null; recommended_technologies:string|null; progress_percent:number };
type ControlLink = { project_id:number; control_id:number };
type Treatment = { project_id:number; priority:"high"|"medium"|"low" };
const statusLabel={planned:"مخطط",in_progress:"قيد التنفيذ",on_hold:"متوقف",completed:"مكتمل"};
const score=(p:Project,linked:number)=>Math.round((([p.executive_owner,p.target_outcome,p.target_end_date,p.recommended_technologies].filter(Boolean).length+(linked>0?1:0))/5)*100);

export default function PortfolioAnalysisPage(){
 const router=useRouter(); const [projects,setProjects]=useState<Project[]>([]); const [links,setLinks]=useState<ControlLink[]>([]); const [treatments,setTreatments]=useState<Treatment[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{try{await requireProfile();const[p,l,t]=await Promise.all([supabase.from("cybersecurity_projects").select("id,project_code,name_ar,planned_year,planned_quarter,status,priority,executive_owner,target_outcome,target_end_date,recommended_technologies,progress_percent").order("planned_year").order("planned_quarter"),supabase.from("cybersecurity_project_controls").select("project_id,control_id"),supabase.from("cybersecurity_project_gap_treatments").select("project_id,priority")]);if(p.error)throw p.error;if(l.error)throw l.error;if(t.error)throw t.error;if(live){setProjects((p.data??[]) as Project[]);setLinks((l.data??[]) as ControlLink[]);setTreatments((t.data??[]) as Treatment[])}}catch(cause){if(!live)return;const message=cause instanceof Error?cause.message:"تعذر تحميل تحليل المحفظة.";if(message.includes("تسجيل الدخول")){router.replace("/login");return}setError(message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[router]);
 const analysis=useMemo(()=>{const mapped=new Map<number,number>();links.forEach(l=>mapped.set(l.project_id,(mapped.get(l.project_id)??0)+1));const rows=projects.map(project=>({project,linked:mapped.get(project.id)??0,readiness:score(project,mapped.get(project.id)??0)}));const readiness=rows.length?Math.round(rows.reduce((n,row)=>n+row.readiness,0)/rows.length):0;const incomplete=rows.filter(row=>row.readiness<80).sort((a,b)=>a.readiness-b.readiness);const years=[2027,2028,2029].map(year=>{const items=rows.filter(row=>row.project.planned_year===year);return{year,total:items.length,high:items.filter(row=>row.project.priority==="high").length,readiness:items.length?Math.round(items.reduce((n,row)=>n+row.readiness,0)/items.length):0}});return{rows,readiness,incomplete,ready:rows.filter(row=>row.readiness>=80).length,years,linkedControls:new Set(links.map(l=>l.control_id)).size,highTreatments:treatments.filter(t=>t.priority==="high").length}},[projects,links,treatments]);
 if(loading)return <main className="roadmap-page" dir="rtl"><p className="roadmap-loading">جاري تحليل محفظة المشاريع…</p></main>;
 return <main className="roadmap-page portfolio-analysis" dir="rtl"><section className="roadmap-shell"><nav className="roadmap-view-tabs" aria-label="عرض خارطة الطريق"><Link href="/roadmap/dashboard">لوحة خارطة الطريق</Link><Link className="active" href="/roadmap/analysis">تحليل المحفظة</Link><Link href="/roadmap">سجل المشاريع</Link></nav><header className="portfolio-hero"><div><span>تحليل محفظة الأمن السيبراني · 2027–2029</span><h1>جاهزية المشاريع والقرارات</h1><p>عرض تحليلي للمحلل والإدارة: اكتمال التخطيط، عبء الأولويات، وتغطية الضوابط قبل بدء التنفيذ.</p></div><Link className="roadmap-primary" href="/roadmap">تحديث بيانات المشاريع ←</Link></header>{error&&<p className="roadmap-alert" role="alert">{error}</p>}
 <section className="portfolio-kpis" aria-label="مؤشرات تحليل المحفظة"><Kpi label="جاهزية التخطيط" value={`${analysis.readiness}%`} detail="ملاك، تواريخ، نواتج، تقنيات وربط ضوابط" tone="teal"/><Kpi label="مشاريع جاهزة" value={`${analysis.ready}/${projects.length}`} detail="اكتمال تخطيط 80% فأعلى" tone="blue"/><Kpi label="ضوابط مغطاة" value={analysis.linkedControls} detail="مرتبطة بمبادرات الإغلاق"/><Kpi label="معالجات عالية" value={analysis.highTreatments} detail="تحتاج ترتيب اعتماد وتمويل" tone="amber"/></section>
 <section className="portfolio-layout"><article className="portfolio-card portfolio-readiness"><header><div><span>مؤشر ذكي</span><h2>صحة المحفظة</h2></div><small>يتجدد مع كل تعديل</small></header><div className="portfolio-score"><div style={{"--score":`${analysis.readiness*3.6}deg`} as React.CSSProperties}><b>{analysis.readiness}%</b><span>جاهزية</span></div><aside><strong>{analysis.readiness>=80?"جاهزة للانطلاق":analysis.readiness>=55?"تحتاج استكمالًا":"تحتاج ضبط الأساس"}</strong><p>المؤشر لا يقيس الالتزام؛ بل يقيس جاهزية بيانات المشروع لاتخاذ قرار تنفيذي.</p><Link href="/roadmap">فتح سجل المشاريع ←</Link></aside></div></article>
 <article className="portfolio-card portfolio-decision"><span>القرار التالي</span><h2>{analysis.incomplete.length?"اعتماد خط الأساس للمشاريع غير المكتملة":"تأكيد بدء التنفيذ"}</h2><p>{analysis.incomplete.length?`${analysis.incomplete.length} مشروعًا لا يملك بيانات تخطيط مكتملة. ابدأ بتحديد المالك، الموعد المستهدف، والناتج المتوقع.`:"كل المشاريع تحتوي على الحد الأدنى من بيانات التخطيط."}</p><div><b>{analysis.years.find(y=>y.year===2027)?.high??0}</b><span>مبادرات عالية الأولوية في 2027</span></div></article>
 <article className="portfolio-card portfolio-load"><header><div><span>خريطة الحمل</span><h2>التوازن السنوي</h2></div></header><div className="portfolio-years">{analysis.years.map(year=><article key={year.year}><div><b>{year.year}</b><span>{year.total} مشاريع</span></div><div className="portfolio-track"><i style={{width:`${Math.min(100,year.total*18)}%`}}/></div><small>{year.high} عالية الأولوية</small><strong>{year.readiness}% جاهزية</strong></article>)}</div></article>
 <article className="portfolio-card portfolio-calendar"><header><div><span>الجدول الذكي</span><h2>تسلسل المبادرات</h2></div><small>اللون يوضح الأولوية</small></header><div className="portfolio-calendar-grid"><div className="portfolio-calendar-head"><span>السنة</span>{["Q1","Q2","Q3","Q4"].map(q=><b key={q}>{q}</b>)}</div>{[2027,2028,2029].map(year=><div className="portfolio-calendar-row" key={year}><b>{year}</b>{["Q1","Q2","Q3","Q4"].map(q=><span key={q}>{analysis.rows.filter(row=>row.project.planned_year===year&&row.project.planned_quarter===q).map(row=><i key={row.project.id} className={row.project.priority} title={`${row.project.project_code} — ${row.project.name_ar} · ${statusLabel[row.project.status]}`}>{row.project.project_code}</i>)}</span>)}</div>)}</div></article>
 <article className="portfolio-card portfolio-data-gaps"><header><div><span>جودة البيانات</span><h2>أولويات الاستكمال</h2></div><small>{analysis.incomplete.length} تحتاج استكمالًا</small></header><ul>{analysis.incomplete.slice(0,6).map(({project,linked,readiness})=><li key={project.id}><div><b dir="ltr">{project.project_code}</b><strong>{project.name_ar}</strong><span>{missing(project,linked).join(" · ")}</span></div><em>{readiness}%</em></li>)}{!analysis.incomplete.length&&<li className="portfolio-empty">بيانات جميع المشاريع مكتملة بالحد الأدنى.</li>}</ul></article></section></section></main>;
}
function missing(p:Project,linked:number){return[[p.executive_owner,"المالك"],[p.target_end_date,"الموعد"],[p.target_outcome,"الناتج"],[p.recommended_technologies,"المعالجة"],[linked,"الضوابط"]].filter(([value])=>!value).map(([,label])=>label as string)}
function Kpi({label,value,detail,tone=""}:{label:string;value:string|number;detail:string;tone?:string}){return <article className={`roadmap-exec-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
