'use client';
import AssessmentPortfolio from '@/components/AssessmentPortfolio';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {requireProfile,type UserRole} from '@/lib/auth';
import {supabase} from '@/lib/supabase';
import {WorkflowHeading,WorkflowMetric} from '@/components/WorkflowUI';
import {type ReviewCycle,type EvidenceRequest,frequencyLabels,todayRiyadh,formatGrcDate,csvDownload,scheduleState,scheduleStateLabels,cycleStage,cycleStageLabels} from '@/lib/grc';
import './audit-schedule.css';
type Control={id:number;control_code:string;title_ar:string;control_owner:string|null;control_owner_id:string|null;audit_frequency:string;last_audit_date:string|null;next_audit_date:string|null;frameworks:{code:string}|null};
type Person={user_id:string;display_name:string|null};
type Assessment={id:number;control_id:number;assessed_at:string};
const periodOptions=[7,14,30,60,90];
function monthStartRiyadh(){const today=todayRiyadh();return `${today.slice(0,7)}-01`;}
export default function AuditSchedulePage(){
 const [controls,setControls]=useState<Control[]>([]),[cycles,setCycles]=useState<ReviewCycle[]>([]),[requests,setRequests]=useState<EvidenceRequest[]>([]),[assessments,setAssessments]=useState<Assessment[]>([]),[people,setPeople]=useState<Person[]>([]),[owners,setOwners]=useState<Person[]>([]),[role,setRole]=useState<UserRole|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [framework,setFramework]=useState('all'),[frequencyFilter,setFrequencyFilter]=useState('all'),[stateFilter,setStateFilter]=useState('open'),[ownerFilter,setOwnerFilter]=useState('all'),[period,setPeriod]=useState(30),[search,setSearch]=useState('');
 const [editing,setEditing]=useState<Control|null>(null),[reviewer,setReviewer]=useState(''),[frequency,setFrequency]=useState('annual'),[due,setDue]=useState(''),[requirement,setRequirement]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const canManage=role==='admin'||role==='cybersecurity_team';
 const load=useCallback(async()=>{try{const {profile}=await requireProfile();setRole(profile.role);const [c,cy,rq,as]=await Promise.all([supabase.from('controls').select('id,control_code,title_ar,control_owner,control_owner_id,audit_frequency,last_audit_date,next_audit_date,frameworks!inner(code,is_active)').eq('frameworks.is_active',true).order('id'),supabase.from('control_review_cycles').select('*').order('id',{ascending:false}),supabase.from('evidence_requests').select('*').order('id',{ascending:false}),supabase.from('control_assessments').select('id,control_id,assessed_at').gte('assessed_at',monthStartRiyadh())]);if(c.error||cy.error||rq.error||as.error)throw c.error||cy.error||rq.error||as.error;const activeIds=new Set((c.data??[]).map(row=>row.id));setControls((c.data??[]).map(row=>({...row,frameworks:Array.isArray(row.frameworks)?row.frameworks[0]??null:row.frameworks})) as Control[]);setCycles((cy.data??[]).filter(row=>activeIds.has(row.control_id)));setRequests((rq.data??[]).filter(row=>activeIds.has(row.control_id)));setAssessments((as.data??[]).filter(row=>activeIds.has(row.control_id)));const ownerIds=[...new Set((c.data??[]).map(row=>row.control_owner_id).filter((id):id is string=>!!id))];if(ownerIds.length){const ow=await supabase.from('profiles').select('user_id,display_name').in('user_id',ownerIds);if(!ow.error)setOwners(ow.data??[]);}if(['admin','cybersecurity_team'].includes(profile.role)){const p=await supabase.from('profiles').select('user_id,display_name').in('role',['admin','cybersecurity_team']).eq('is_active',true);if(p.error)throw p.error;setPeople(p.data??[]);}}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الجدول');}finally{setLoading(false);}},[]);
 useEffect(()=>{const t=setTimeout(()=>{void load();},0);return()=>clearTimeout(t);},[load]);
 const openCycleFor=useCallback((controlId:number)=>cycles.find(x=>x.control_id===controlId&&x.status==='open'),[cycles]);
 const latestRequestStatusFor=useCallback((controlId:number,cycleId:number|undefined)=>{if(!cycleId)return undefined;const rows=requests.filter(r=>r.cycle_id===cycleId).sort((a,b)=>b.id-a.id);return rows[0]?.status;},[requests]);
 const filtered=useMemo(()=>controls.filter(c=>{const st=scheduleState(c.next_audit_date,period);return (framework==='all'||c.frameworks?.code===framework)&&(frequencyFilter==='all'||c.audit_frequency===frequencyFilter)&&(ownerFilter==='all'||(ownerFilter==='unassigned'?!c.control_owner_id:c.control_owner_id===ownerFilter))&&(stateFilter==='all'||(stateFilter==='open'?['overdue','due_today','due_soon','unscheduled'].includes(st):st===stateFilter))&&`${c.control_code} ${c.title_ar} ${c.control_owner}`.includes(search);}),[controls,framework,frequencyFilter,ownerFilter,stateFilter,period,search]);
 const frameworks=[...new Set(controls.map(c=>c.frameworks?.code).filter(Boolean))];
 const openCycle=editing?openCycleFor(editing.id):undefined;
 function edit(c:Control){const cycle=openCycleFor(c.id);setEditing(c);setReviewer(cycle?.reviewer_id??'');setDue(cycle?.due_date??c.next_audit_date??'');setFrequency(cycle?.frequency??c.audit_frequency);setRequirement(c.title_ar);setReason('');setError('');}
 async function save(){if(!editing||busy)return;setBusy(true);setError('');const r=await supabase.rpc('cgp_grc_command',{p_action:openCycle?'reschedule':'open_cycle',p_control_id:editing.id,p_data:{cycle_id:openCycle?.id,reviewer_id:reviewer,due_date:due,frequency,requirement,reason}});if(r.error)setError(r.error.message);else{setMessage(openCycle?'تم تحديث الدورة وتسجيل التغيير.':'تم إنشاء الدورة وطلب الدليل.');setEditing(null);await load();}setBusy(false);}
 if(loading)return <main role="status">جاري تحميل جدول المراجعات…</main>;
 const awaitingEvidenceCount=requests.filter(r=>['open','changes_requested','rejected'].includes(r.status)).length;
 const underReviewCount=requests.filter(r=>r.status==='submitted').length;
 const openCyclesCount=cycles.filter(c=>c.status==='open').length;
 const overdueCount=controls.filter(c=>scheduleState(c.next_audit_date)==='overdue').length;
 const dueSoonCount=controls.filter(c=>['due_today','due_soon'].includes(scheduleState(c.next_audit_date,period))).length;
 const completedThisPeriodCount=assessments.length;
 return <main className="workflow-page audit-schedule-page" dir="rtl"><WorkflowHeading title="جدول التدقيق الدوري" description="دورات مراجعة محفوظة وفق سياسة الجهة. إغلاق الدورة يتطلب قرار تقييم، وينشئ الدورة التالية تلقائيًا."/>{error&&<p role="alert" className="cgp-shell-error">{error}</p>}{message&&<p role="status">{message}</p>}
 <div className="workflow-metrics">
  <WorkflowMetric label="متأخرة" value={overdueCount} tone="danger"/>
  <WorkflowMetric label={`مستحقة خلال ${period} يومًا`} value={dueSoonCount} tone="warning"/>
  <WorkflowMetric label="دورات مفتوحة" value={openCyclesCount}/>
  <WorkflowMetric label="بانتظار الدليل" value={awaitingEvidenceCount}/>
  <WorkflowMetric label="قيد المراجعة" value={underReviewCount}/>
  <WorkflowMetric label="مكتملة هذا الشهر" value={completedThisPeriodCount} tone="success"/>
 </div>
 <section className="audit-filter-bar">
  <label>الإطار<select value={framework} onChange={e=>setFramework(e.target.value)}><option value="all">جميع الأطر</option>{frameworks.map(f=><option key={f}>{f}</option>)}</select></label>
  <label>التكرار<select value={frequencyFilter} onChange={e=>setFrequencyFilter(e.target.value)}><option value="all">كل التكرارات</option>{Object.entries(frequencyLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
  <label>المالك<select value={ownerFilter} onChange={e=>setOwnerFilter(e.target.value)}><option value="all">الكل</option><option value="unassigned">غير معيّن فقط</option>{owners.map(o=><option key={o.user_id} value={o.user_id}>{o.display_name??o.user_id.slice(0,8)}</option>)}</select></label>
  <label>الحالة<select value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option value="open">تحتاج متابعة</option><option value="all">كل الحالات</option>{Object.entries(scheduleStateLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
  <label>خلال (أيام)<select value={period} onChange={e=>setPeriod(Number(e.target.value))}>{periodOptions.map(p=><option key={p} value={p}>{p}</option>)}</select></label>
 </section>
 <div className="workflow-filter"><label>بحث<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="رقم الضابط أو اسمه أو المالك"/></label><button onClick={()=>window.print()}>طباعة / PDF</button><button onClick={()=>csvDownload('periodic-reviews.csv',[['الإطار','الضابط','الاسم','المالك','التكرار','آخر مراجعة','الموعد القادم','حالة الموعد','مرحلة الدورة'],...filtered.map(c=>{const cycle=openCycleFor(c.id);return [c.frameworks?.code??'',c.control_code,c.title_ar,c.control_owner??'',frequencyLabels[c.audit_frequency],c.last_audit_date??'',c.next_audit_date??'',scheduleStateLabels[scheduleState(c.next_audit_date,period)],cycleStageLabels[cycleStage(!!cycle,latestRequestStatusFor(c.id,cycle?.id))]];})])}>تصدير CSV</button></div>
 <section className="audit-table-wrap"><table className="audit-table"><thead><tr><th>الضابط</th><th>الإطار</th><th>المالك / المراجع</th><th>التكرار</th><th>آخر مراجعة</th><th>القادمة</th><th>حالة الموعد</th><th>مرحلة الدورة</th><th>الإجراء</th></tr></thead><tbody>{filtered.map(c=>{const cycle=openCycleFor(c.id);const stage=cycleStage(!!cycle,latestRequestStatusFor(c.id,cycle?.id));const st=scheduleState(c.next_audit_date,period);if(!c.control_owner_id)return <tr key={c.id} className="audit-row-unowned"><td><strong dir="ltr">{c.control_code}</strong><span>{c.title_ar}</span></td><td>{c.frameworks?.code}</td><td colSpan={5}><span className="audit-no-owner">بلا مالك — لا يمكن جدولة مراجعة دورية حتى يُعيَّن مالك</span></td><td><div className="audit-actions"><Link href={`/controls/${c.id}`}>فتح</Link>{canManage&&<Link href={`/controls/${c.id}/assign`}>تعيين مالك</Link>}</div></td></tr>;return <tr key={c.id}><td><strong dir="ltr">{c.control_code}</strong><span>{c.title_ar}</span></td><td>{c.frameworks?.code}</td><td>{c.control_owner}<br/>{cycle?(people.find(p=>p.user_id===cycle.reviewer_id)?.display_name??'مراجع مكلف'):'دون دورة مفتوحة'}</td><td>{frequencyLabels[c.audit_frequency]}</td><td>{formatGrcDate(c.last_audit_date)}</td><td>{formatGrcDate(c.next_audit_date)}</td><td><span className={`audit-state ${st}`}>{scheduleStateLabels[st]}</span></td><td><span className={`audit-stage ${stage}`}>{cycleStageLabels[stage]}</span></td><td><div className="audit-actions"><Link href={`/controls/${c.id}`}>فتح</Link>{canManage&&<button onClick={()=>edit(c)}>{cycle?'تعديل الدورة':'إنشاء دورة'}</button>}</div></td></tr>;})}</tbody></table>{!filtered.length&&<p>لا توجد نتائج مطابقة.</p>}</section>
 <details className="grc-cycle-history"><summary>تاريخ الدورات المكتملة</summary>{cycles.filter(c=>c.status==='completed').map(c=><p key={c.id}><Link href={`/controls/${c.control_id}`}>دورة #{c.id}</Link> · {formatGrcDate(c.completed_at)} · {c.notes}</p>)}</details>
 {editing&&<dialog ref={node=>{if(node&&!node.open)node.showModal();}} onCancel={e=>{e.preventDefault();if(!busy)setEditing(null);}} className="audit-editor" aria-labelledby="cycle-title"><form className="grc-form" onSubmit={e=>{e.preventDefault();void save();}}>{error&&<p role="alert">{error}</p>}<h2 id="cycle-title">{openCycle?'تعديل الدورة':'إنشاء دورة وطلب دليل'} · {editing.control_code}</h2>{!editing.control_owner_id&&<p className="grc-warning">عيّن مالك الضابط أولًا. <Link href={`/controls/${editing.id}/assign`}>تعيين مالك</Link></p>}<label>المراجع<select required value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">اختر مراجعًا</option>{people.filter(p=>p.user_id!==editing.control_owner_id).map(p=><option key={p.user_id} value={p.user_id}>{p.display_name??p.user_id}</option>)}</select></label><label>موعد الاستحقاق<input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>التكرار<select value={frequency} onChange={e=>setFrequency(e.target.value)}>{Object.entries(frequencyLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{openCycle?<label>سبب التعديل<textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label>:<label>الأدلة المطلوبة<textarea required value={requirement} onChange={e=>setRequirement(e.target.value)}/></label>}<div className="grc-inline-actions"><button className="audit-save" disabled={busy||!editing.control_owner_id}>حفظ</button><button type="button" className="audit-cancel" disabled={busy} onClick={()=>setEditing(null)}>إلغاء</button></div></form></dialog>}
 <AssessmentPortfolio view="schedule"/></main>;
}
