-- Corrective fix for 20260919150000: private.grc_audit() requires a single
-- `id` column on every audited table (it reads entity_id from row->>'id').
-- cybersecurity_project_requirements and cybersecurity_requirement_controls
-- were created with composite primary keys only (matching the pre-existing
-- cybersecurity_project_controls convention), which made every write to them
-- fail the grc_audit_events NOT NULL constraint on entity_id. Both tables are
-- empty on every environment this migration has touched (confirmed on QA
-- before writing this fix), so this is a plain additive/structural correction,
-- not a data migration. Audit triggers themselves are untouched.

alter table public.cybersecurity_project_requirements
  drop constraint cybersecurity_project_requirements_pkey,
  add column id bigint generated by default as identity;

alter table public.cybersecurity_project_requirements
  add constraint cybersecurity_project_requirements_pkey primary key (id),
  add constraint cybersecurity_project_requirements_unique unique (project_id, requirement_id);

grant usage, select on sequence public.cybersecurity_project_requirements_id_seq to authenticated;

alter table public.cybersecurity_requirement_controls
  drop constraint cybersecurity_requirement_controls_pkey,
  add column id bigint generated by default as identity;

alter table public.cybersecurity_requirement_controls
  add constraint cybersecurity_requirement_controls_pkey primary key (id),
  add constraint cybersecurity_requirement_controls_unique unique (requirement_id, control_id);

grant usage, select on sequence public.cybersecurity_requirement_controls_id_seq to authenticated;
