-- QA-ONLY. Requirement<->Control mapping refinement, per the independently
-- validated review in nca_reconciliation/04_requirement_mapping_review.csv.
-- No mapping is deleted. VALID_AS_IS mappings (128) are untouched.
-- VALID_BUT_PARENT_LEVEL (40) and MANUAL_REVIEW (2) mappings are left
-- pointing at their current target and only get a 'notes' annotation.
-- MOVE_TO_SUBCONTROL (27) and MAP_TO_MULTIPLE (3) mappings get a new,
-- additional mapping row to the more specific official sub-control target(s)
-- (now that those sub-controls exist, post catalog-correction migration) —
-- the original parent-level mapping is kept, not deleted, and annotated as
-- superseded, preserving full traceability. Idempotent: ON CONFLICT DO
-- NOTHING on the existing (requirement_id, control_id) unique constraint for
-- inserts; notes updates are plain idempotent UPDATEs.

update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 8 sub-items case-by-case but not urgent.' where id = 76 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-5-3-8. Original mapping retained for traceability, not deleted.' where id = 30 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 9 sub-items case-by-case but not urgent.' where id = 27 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MANUAL_REVIEW — unchanged, needs human judgment: ECC 2-11-3 is Penetration Testing, not APT/sandbox detection — topically weak fit for this requirement; needs human judgment on whether pentest scope should stay mapped here at all.' where id = 28 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MANUA%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 25 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-4-3-4. Original mapping retained for traceability, not deleted.' where id = 29 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE: superseded by more specific mapping(s) to ECC 2-9-3-1, ECC 2-9-3-2, ECC 2-9-3-3. Original mapping retained for traceability, not deleted.' where id = 33 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MAP_T%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 3 sub-items case-by-case but not urgent.' where id = 31 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 160 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to CCC 1-3-T-1-1. Original mapping retained for traceability, not deleted.' where id = 164 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to CCC 2-1-T-1-1. Original mapping retained for traceability, not deleted.' where id = 165 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to CCC 3-1-T-1-1. Original mapping retained for traceability, not deleted.' where id = 161 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE: superseded by more specific mapping(s) to CCC 1-2-T-1-1, CCC 1-2-T-1-2, CCC 1-2-T-1-3. Original mapping retained for traceability, not deleted.' where id = 163 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MAP_T%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 5 sub-items case-by-case but not urgent.' where id = 191 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 9 sub-items case-by-case but not urgent.' where id = 59 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-5-3-9. Original mapping retained for traceability, not deleted.' where id = 60 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-3-3-2. Original mapping retained for traceability, not deleted.' where id = 81 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-5-3-7. Original mapping retained for traceability, not deleted.' where id = 77 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 4 sub-items case-by-case but not urgent.' where id = 44 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 3-1-3-3. Original mapping retained for traceability, not deleted.' where id = 46 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Backup is a supporting capability for DR/BCM broadly, not one narrow sub-item; parent-level mapping is defensible but should be reviewed alongside the 3-1-3 mapping below for overlap.' where id = 45 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Requirement is a category ("Email Security") spanning all of 2-4-3''s sub-items, not one specific technique — parent-level mapping is topically appropriate despite the generic opener text.' where id = 61 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: ECC 2-8-3''s official text already states the specific NCS-1:2020 encryption-level requirement (not a bare opener) — reasonable parent-level target as-is.' where id = 20 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "full", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 5 sub-items case-by-case but not urgent.' where id = 19 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 83 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-5-3-1. Original mapping retained for traceability, not deleted.' where id = 35 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 9 sub-items case-by-case but not urgent.' where id = 34 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to CSCC 2-3-1-6. Original mapping retained for traceability, not deleted.' where id = 62 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MANUAL_REVIEW — unchanged, needs human judgment: ECC domain-2 has no explicitly named "hardening" sub-item under either 2-5-3 (network) or 2-3-3 (systems) — this requirement may have no precise ECC target; needs human judgment on best-available ECC anchor.' where id = 63 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MANUA%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 130 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 129 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 8 sub-items case-by-case but not urgent.' where id = 21 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-2-3-3. Original mapping retained for traceability, not deleted.' where id = 24 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-5-3-6. Original mapping retained for traceability, not deleted.' where id = 86 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 5 sub-items case-by-case but not urgent.' where id = 203 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-13-3-1. Original mapping retained for traceability, not deleted.' where id = 87 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Requirement is the general MDM/UEM capability category spanning multiple 2-6-3 sub-items (encryption, restricted use, remote wipe) — parent-level mapping is topically appropriate.' where id = 39 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-4-3-2. Original mapping retained for traceability, not deleted.' where id = 50 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-2-3-2. Original mapping retained for traceability, not deleted.' where id = 49 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 8 sub-items case-by-case but not urgent.' where id = 74 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 9 sub-items case-by-case but not urgent.' where id = 75 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-15-3-2. Original mapping retained for traceability, not deleted.' where id = 88 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 9 sub-items case-by-case but not urgent.' where id = 66 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-5-3-4. Original mapping retained for traceability, not deleted.' where id = 67 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-3-3-4. Original mapping retained for traceability, not deleted.' where id = 89 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 5 sub-items case-by-case but not urgent.' where id = 16 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-10-3-4. Original mapping retained for traceability, not deleted.' where id = 56 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-3-3-3. Original mapping retained for traceability, not deleted.' where id = 57 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-11-3-2. Original mapping retained for traceability, not deleted.' where id = 70 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 68 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 5 sub-items case-by-case but not urgent.' where id = 142 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 116 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 119 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 4 sub-items case-by-case but not urgent.' where id = 117 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 5 sub-items case-by-case but not urgent.' where id = 120 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 1 sub-items case-by-case but not urgent.' where id = 168 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 3 sub-items case-by-case but not urgent.' where id = 177 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 110 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "full", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 3 sub-items case-by-case but not urgent.' where id = 109 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 3 sub-items case-by-case but not urgent.' where id = 115 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 5 sub-items case-by-case but not urgent.' where id = 144 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE: superseded by more specific mapping(s) to ECC 2-12-3-3, ECC 2-12-3-4. Original mapping retained for traceability, not deleted.' where id = 8 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MAP_T%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 3 sub-items case-by-case but not urgent.' where id = 154 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 152 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 155 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-13-3-5. Original mapping retained for traceability, not deleted.' where id = 91 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-13-3-4. Original mapping retained for traceability, not deleted.' where id = 92 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 5 sub-items case-by-case but not urgent.' where id = 6 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-15-3-1. Original mapping retained for traceability, not deleted.' where id = 73 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] VALID_BUT_PARENT_LEVEL: Coverage already marked "partial", honestly signalling partial/category-level coverage of a parent control whose text is a list-opener; consider reviewing against its 2 sub-items case-by-case but not urgent.' where id = 71 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] VALID%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-5-3-3. Original mapping retained for traceability, not deleted.' where id = 93 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');
update public.cybersecurity_requirement_controls set notes = coalesce(notes || E'\n', '') || '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL: superseded by more specific mapping(s) to ECC 2-3-3-1. Original mapping retained for traceability, not deleted.' where id = 82 and (notes is null or notes not like '%[Master-Catalog review 2026-09-21] MOVE_%');

-- New, more specific mappings (MOVE_TO_SUBCONTROL / MAP_TO_MULTIPLE targets):
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (11, 323, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=30 (ECC 2-5-3): Official text of 2-5-3 is a bare list-opener; the specific APT/sandbox-over-internet-channel requirement is 2-5-3-8, not the parent.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (11, 310, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=29 (ECC 2-4-3): Parent 2-4-3 is a bare opener; APT protection for email specifically is sub-item 2-4-3-4.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (12, 348, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE from mapping_id=33 (ECC 2-9-3): Parent 2-9-3 is a bare opener; the Backup requirement is fully covered only by combining its 3 sub-items (scope, restore speed, restore-test frequency).')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (12, 349, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE from mapping_id=33 (ECC 2-9-3): Parent 2-9-3 is a bare opener; the Backup requirement is fully covered only by combining its 3 sub-items (scope, restore speed, restore-test frequency).')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (12, 350, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE from mapping_id=33 (ECC 2-9-3): Parent 2-9-3 is a bare opener; the Backup requirement is fully covered only by combining its 3 sub-items (scope, restore speed, restore-test frequency).')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (60, 676, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=164 (CCC 1-3-T-1): Parent is a bare opener wrapping a single sub-item; map directly to the sub-item.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (60, 695, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=165 (CCC 2-1-T-1): Parent is a bare opener wrapping a single sub-item; map directly to the sub-item.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (60, 830, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=161 (CCC 3-1-T-1): Parent is a bare opener wrapping a single sub-item; map directly to the sub-item.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (60, 670, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE from mapping_id=163 (CCC 1-2-T-1): Parent is a bare opener; the risk-management requirement is realized across all 3 sub-items.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (60, 671, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE from mapping_id=163 (CCC 1-2-T-1): Parent is a bare opener; the risk-management requirement is realized across all 3 sub-items.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (60, 672, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE from mapping_id=163 (CCC 1-2-T-1): Parent is a bare opener; the risk-management requirement is realized across all 3 sub-items.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (22, 324, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=60 (ECC 2-5-3): Exact-match sub-item exists for DDoS protection; parent text does not mention DDoS at all.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (35, 300, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=81 (ECC 2-3-3): Exact-match sub-item exists for external storage/media device control; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (32, 322, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=77 (ECC 2-5-3): Exact-match sub-item exists for DNS security; parent text does not mention DNS.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (16, 357, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=46 (ECC 3-1-3): Parent 3-1-3 is a bare opener; the Disaster Recovery Plan requirement matches sub-item 3-1-3-3 specifically (3-1-3-2 covers incident-response continuity, a related but distinct concept).')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (13, 316, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=35 (ECC 2-5-3): Exact-match sub-item exists for firewall/segmentation; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (24, 499, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=62 (CSCC 2-3-1): CSCC 2-3-1-6 is explicitly "مراجعة إعدادات الأنظمة الحساسة وتحصيناتها (Secure Configuration and Hardening)" — an exact match; parent 2-3-1 is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (10, 292, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=24 (ECC 2-2-3): Parent 2-2-3 is a bare opener; general IAM/authorization (least-privilege, need-to-know) is specifically 2-2-3-3, distinct from the MFA-specific 2-2-3-2 already used by REQ-MFA.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (40, 321, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=86 (ECC 2-5-3): Exact-match sub-item exists for Intrusion Prevention Systems; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (41, 263, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=87 (ECC 2-13-3): Exact-match sub-item exists for incident response plans; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (17, 308, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=50 (ECC 2-4-3): Exact-match sub-item exists for MFA on email/webmail access; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (17, 291, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=49 (ECC 2-2-3): Exact-match sub-item exists for Multi-Factor Authentication; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (42, 282, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=88 (ECC 2-15-3): Exact-match sub-item exists for multi-tier architecture; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (26, 319, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=67 (ECC 2-5-3): Closest-match sub-item covers wireless network security and access control; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (43, 302, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=89 (ECC 2-3-3): Exact-match sub-item exists for clock synchronization; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (20, 242, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=56 (ECC 2-10-3): Exact-match sub-item exists for patch/update management tied to vulnerability remediation; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (20, 301, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=57 (ECC 2-3-3): Exact-match sub-item exists for Patch Management; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (27, 249, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=70 (ECC 2-11-3): Parent 2-11-3 is a bare opener; periodic penetration testing is specifically 2-11-3-2 (2-11-3-1 covers scope definition, a related but distinct concept — consider MAP_TO_MULTIPLE if both aspects are intended).')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (6, 256, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE from mapping_id=8 (ECC 2-12-3): Parent 2-12-3 is a bare opener; the SIEM/SOC requirement specifically matches 2-12-3-3 (SIEM tooling) and 2-12-3-4 (continuous monitoring).')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (6, 257, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MAP_TO_MULTIPLE from mapping_id=8 (ECC 2-12-3): Parent 2-12-3 is a bare opener; the SIEM/SOC requirement specifically matches 2-12-3-3 (SIEM tooling) and 2-12-3-4 (continuous monitoring).')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (46, 267, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=91 (ECC 2-13-3): Exact-match sub-item exists for Threat Intelligence; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (47, 266, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=92 (ECC 2-13-3): Exact-match sub-item exists for sharing threat indicators/alerts with the Authority; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (28, 281, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=73 (ECC 2-15-3): Exact-match sub-item exists for Web Application Firewall; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (48, 318, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=93 (ECC 2-5-3): Exact-match sub-item exists for internet browsing/proxy security; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
insert into public.cybersecurity_requirement_controls (requirement_id, control_id, coverage_type, mapping_confidence, notes)
values (36, 299, 'full', 'confirmed', '[Master-Catalog review 2026-09-21] MOVE_TO_SUBCONTROL from mapping_id=82 (ECC 2-3-3): Exact-match sub-item exists for endpoint/malware protection; parent text is a bare opener.')
on conflict (requirement_id, control_id) do nothing;
