create table if not exists public.cybersecurity_project_gap_treatments (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.cybersecurity_projects(id) on delete cascade,
  gap_title text not null,
  treatment_type text not null check (treatment_type in ('technology','procedure','policy','training')),
  recommendation text not null,
  priority text not null default 'medium' check (priority in ('high','medium','low')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cybersecurity_project_gap_treatments_project_idx
  on public.cybersecurity_project_gap_treatments(project_id);

alter table public.cybersecurity_project_gap_treatments enable row level security;
revoke all on public.cybersecurity_project_gap_treatments from anon;
grant select, insert, update, delete on public.cybersecurity_project_gap_treatments to authenticated;
grant usage, select on sequence public.cybersecurity_project_gap_treatments_id_seq to authenticated;

create policy cybersecurity_project_gap_treatments_read
on public.cybersecurity_project_gap_treatments for select to authenticated
using (
  exists (
    select 1 from public.cybersecurity_projects project
    where project.id = cybersecurity_project_gap_treatments.project_id
      and (
        (select private.current_user_role()) in ('admin','cybersecurity_team')
        or exists (
          select 1 from public.cybersecurity_project_controls link
          join public.controls control on control.id = link.control_id
          where link.project_id = project.id
            and (control.control_owner_id = (select auth.uid()) or private.can_external_auditor_view_control(control.id))
        )
      )
  )
);

create policy cybersecurity_project_gap_treatments_write
on public.cybersecurity_project_gap_treatments for all to authenticated
using ((select private.current_user_role()) in ('admin','cybersecurity_team'))
with check ((select private.current_user_role()) in ('admin','cybersecurity_team'));

insert into public.cybersecurity_project_gap_treatments
(project_id, gap_title, treatment_type, recommendation, priority)
select id,
case project_code
  when 'R-01' then 'غياب منصة موحدة لإدارة الالتزام والأدلة'
  when 'R-02' then 'عدم توحيد إدارة الهوية والوصول المميز'
  when 'R-03' then 'ضعف عزل الشبكات والخدمات الحساسة'
  when 'R-04' then 'محدودية الرصد والحماية الموحدة لنقاط النهاية'
  when 'R-05' then 'غياب الرصد المركزي والاستجابة المنظمة للحوادث'
  when 'R-06' then 'عدم وجود دورة موحدة لمعالجة الثغرات'
  when 'R-07' then 'قصور تصنيف البيانات وحمايتها وتشفيرها'
  when 'R-08' then 'عدم وضوح وضع أمن الخدمات السحابية'
  when 'R-09' then 'قصور اختبارات الاستعادة والتعافي من الكوارث'
  when 'R-10' then 'ضعف حماية التطبيقات والبريد الإلكتروني'
  when 'R-11' then 'عدم وجود قياس التزام ومراجعة مستمرة'
end,
case project_code
  when 'R-01' then 'procedure'
  when 'R-09' then 'procedure'
  when 'R-11' then 'procedure'
  when 'R-05' then 'technology'
  else 'technology'
end,
case project_code
  when 'R-01' then 'إعداد سجل فجوات ومكتبة أدلة وإجراءات اعتماد ومراجعة دورية.'
  when 'R-02' then 'تطبيق IAM وMFA وPAM وربطها بمراجعة دورية لصلاحيات الحسابات.'
  when 'R-03' then 'تطبيق NGFW وتقسيم شبكي وNAC ومراقبة DNS وفق تصميم معتمد.'
  when 'R-04' then 'نشر EDR/XDR وإدارة مركزية للأجهزة والتحديثات وضبط الأجهزة الطرفية.'
  when 'R-05' then 'تشغيل SIEM/SOC مع إدارة السجلات وSOAR وإجراءات استجابة واختبارها.'
  when 'R-06' then 'تطبيق منصة إدارة الثغرات وربطها بالمسح والاختبار وخطط المعالجة.'
  when 'R-07' then 'تطبيق التصنيف وDLP والتشفير وإدارة المفاتيح وفق حساسية البيانات.'
  when 'R-08' then 'تطبيق CSPM وتسجيل سحابي وإدارة هوية سحابية وتقييم مزودي الخدمة.'
  when 'R-09' then 'تحديد RTO/RPO وتنفيذ نسخ غير قابلة للعبث واختبارات استعادة دورية.'
  when 'R-10' then 'تطبيق WAF وأمن API وفحص SAST/DAST وبوابة بريد آمنة.'
  when 'R-11' then 'إنشاء مؤشرات قياس والتدقيق الدوري وقياس فعالية الضوابط والأدلة.'
end,
case when project_code in ('R-01','R-02','R-03','R-04','R-05','R-06','R-07','R-09') then 'high' else 'medium' end
from public.cybersecurity_projects
where project_code in ('R-01','R-02','R-03','R-04','R-05','R-06','R-07','R-08','R-09','R-10','R-11')
  and not exists (
    select 1 from public.cybersecurity_project_gap_treatments existing
    where existing.project_id = cybersecurity_projects.id
  );
