-- Phase 1 of the Program -> Project -> Cybersecurity Requirement -> Control ->
-- Evidence architecture (Program layer deferred to Phase 2). Purely additive:
-- no change to controls/evidence/review/assessment lifecycle, RLS, or RPCs.
-- No compliance_status/compliance_percentage column anywhere here — compliance
-- stays derived only from controls.implementation_status/verification_status.

create table if not exists public.cybersecurity_requirements (
  id bigint generated by default as identity primary key,
  requirement_code text not null unique,
  title_ar text not null,
  description_ar text,
  source_reference text,
  status text not null default 'active' check (status in ('draft','active','retired')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cybersecurity_project_requirements (
  project_id bigint not null references public.cybersecurity_projects(id) on delete cascade,
  requirement_id bigint not null references public.cybersecurity_requirements(id) on delete cascade,
  coverage_type text not null default 'full' check (coverage_type in ('full','partial','supporting')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (project_id, requirement_id)
);

create table if not exists public.cybersecurity_requirement_controls (
  requirement_id bigint not null references public.cybersecurity_requirements(id) on delete cascade,
  control_id bigint not null references public.controls(id) on delete cascade,
  coverage_type text not null default 'full' check (coverage_type in ('full','partial','supporting')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (requirement_id, control_id)
);

alter table public.cybersecurity_projects
  add column if not exists initiative_type text not null default 'technology_project'
  check (initiative_type in (
    'technology_project','managed_service','framework_agreement',
    'internal_program','policy_governance','assessment','continuous_activity'
  ));

create index if not exists cybersecurity_project_requirements_requirement_idx
  on public.cybersecurity_project_requirements (requirement_id);
create index if not exists cybersecurity_requirement_controls_control_idx
  on public.cybersecurity_requirement_controls (control_id);

alter table public.cybersecurity_requirements enable row level security;
alter table public.cybersecurity_project_requirements enable row level security;
alter table public.cybersecurity_requirement_controls enable row level security;

revoke all on public.cybersecurity_requirements, public.cybersecurity_project_requirements, public.cybersecurity_requirement_controls from anon;
grant select, insert, update, delete on public.cybersecurity_requirements, public.cybersecurity_project_requirements, public.cybersecurity_requirement_controls to authenticated;
grant usage, select on sequence public.cybersecurity_requirements_id_seq to authenticated;

-- cybersecurity_requirements: catalog-style read, same roster as public.frameworks.
create policy cybersecurity_requirements_read on public.cybersecurity_requirements
for select to authenticated using (
  (select private.current_user_role()) in ('admin','cybersecurity_team','control_owner')
);

create policy cybersecurity_requirements_write on public.cybersecurity_requirements
for all to authenticated
using ((select private.current_user_role()) in ('admin','cybersecurity_team'))
with check ((select private.current_user_role()) in ('admin','cybersecurity_team'));

-- cybersecurity_project_requirements: visibility flows through the NEW
-- requirement->control chain (not the old direct project_controls junction,
-- which a Requirement-driven project need not populate at all) — an owner
-- sees this link if any control they own is mapped to the same requirement.
create policy cybersecurity_project_requirements_read on public.cybersecurity_project_requirements
for select to authenticated using (
  (select private.current_user_role()) in ('admin','cybersecurity_team')
  or exists (
    select 1 from public.cybersecurity_requirement_controls rc
    join public.controls control on control.id = rc.control_id
    where rc.requirement_id = cybersecurity_project_requirements.requirement_id
      and (control.control_owner_id = (select auth.uid()) or private.can_external_auditor_view_control(control.id))
  )
);

create policy cybersecurity_project_requirements_write on public.cybersecurity_project_requirements
for all to authenticated
using ((select private.current_user_role()) in ('admin','cybersecurity_team'))
with check ((select private.current_user_role()) in ('admin','cybersecurity_team'));

-- cybersecurity_requirement_controls: same pattern as cybersecurity_project_controls
-- (control_id present directly).
create policy cybersecurity_requirement_controls_read on public.cybersecurity_requirement_controls
for select to authenticated using (
  (select private.current_user_role()) in ('admin','cybersecurity_team')
  or exists (
    select 1 from public.controls control
    where control.id = cybersecurity_requirement_controls.control_id
      and (control.control_owner_id = (select auth.uid()) or private.can_external_auditor_view_control(control.id))
  )
);

create policy cybersecurity_requirement_controls_write on public.cybersecurity_requirement_controls
for all to authenticated
using ((select private.current_user_role()) in ('admin','cybersecurity_team'))
with check ((select private.current_user_role()) in ('admin','cybersecurity_team'));

create trigger grc_audit after insert or delete or update on public.cybersecurity_requirements
  for each row execute function private.grc_audit();
create trigger grc_audit after insert or delete or update on public.cybersecurity_project_requirements
  for each row execute function private.grc_audit();
create trigger grc_audit after insert or delete or update on public.cybersecurity_requirement_controls
  for each row execute function private.grc_audit();
