-- مستخرج من الوثيقة العربية الرسمية Policies001.pdf: الإصدار 2021، القسم 9
insert into public.data_governance_controls (domain_id, control_code, title_ar, implementation_status) values
(1, 'DG.1', 'الاستراتيجية والخطة', 'not_started'),
(1, 'DG.2', 'السياسات والقواعد الاسترشادية', 'not_started'),
(1, 'DG.3', 'التدريب والتوعية', 'not_started'),
(1, 'DG.4', 'تنظيم إدارة البيانات وحوكمتها وحماية البيانات الشخصية', 'not_started'),
(1, 'DG.5', 'إطار تدقيق الامتثال', 'not_started'),
(1, 'DG.6', 'حوكمة دورة حياة البيانات', 'not_started'),
(1, 'DG.7', 'إدارة الأداء', 'not_started'),
(1, 'DG.8', 'السجلات', 'not_started'),
(2, 'MCM.1', 'التخطيط', 'not_started'),
(2, 'MCM.2', 'السياسات والقواعد الاسترشادية', 'not_started'),
(2, 'MCM.3', 'التدريب والتوعية', 'not_started'),
(2, 'MCM.4', 'إدارة دورة حياة البيانات', 'not_started'),
(2, 'MCM.5', 'أتمتة دليل البيانات', 'not_started'),
(2, 'MCM.6', 'إدارة الأداء', 'not_started'),
(3, 'DQ.1', 'التخطيط', 'not_started'),
(3, 'DQ.2', 'عمليات جودة البيانات', 'not_started'),
(3, 'DQ.3', 'إدارة الأداء', 'not_started'),
(3, 'DQ.4', 'إدارة دورة حياة البيانات', 'not_started'),
(4, 'DO.1', 'التخطيط', 'not_started'),
(4, 'DO.2', 'السياسات والقواعد الاسترشادية', 'not_started'),
(4, 'DO.3', 'عمليات قواعد البيانات', 'not_started'),
(4, 'DO.4', 'استمرارية الأعمال', 'not_started'),
(4, 'DO.5', 'إدارة الأداء', 'not_started'),
(5, 'DCM.1', 'التخطيط', 'not_started'),
(5, 'DCM.2', 'السياسات والقواعد الاسترشادية', 'not_started'),
(5, 'DCM.3', 'التدريب والتوعية', 'not_started'),
(5, 'DCM.4', 'عمليات إدارة المحتوى والوثائق', 'not_started'),
(5, 'DCM.5', 'إدارة الأداء', 'not_started'),
(6, 'DAM.1', 'التخطيط', 'not_started'),
(6, 'DAM.2', 'السياسات والقواعد الاسترشادية', 'not_started'),
(6, 'DAM.3', 'تعريف إطار هيكلة البيانات', 'not_started'),
(6, 'DAM.4', 'تعريف نمذجة البيانات', 'not_started'),
(6, 'DAM.5', 'إدارة دورة حياة البيانات', 'not_started'),
(6, 'DAM.6', 'إدارة الأداء', 'not_started'),
(6, 'DAM.7', 'السجلات', 'not_started'),
(9, 'DSI.1', 'التخطيط', 'not_started'),
(9, 'DSI.2', 'التدريب والتوعية', 'not_started'),
(9, 'DSI.3', 'دورة حياة تطوير حلول التكامل', 'not_started'),
(9, 'DSI.4', 'عمليات معالجة البيانات', 'not_started'),
(9, 'DSI.5', 'عملية مشاركة البيانات', 'not_started'),
(9, 'DSI.6', 'طلبات مشاركة البيانات', 'not_started'),
(9, 'DSI.7', 'اتفاقيات مشاركة البيانات', 'not_started'),
(9, 'DSI.8', 'إدارة الأداء', 'not_started'),
(7, 'RMD.1', 'التخطيط', 'not_started'),
(7, 'RMD.2', 'هيكلة البيانات', 'not_started'),
(7, 'RMD.3', 'التدريب والتوعية', 'not_started'),
(7, 'RMD.4', 'إدارة دورة الحياة للبيانات', 'not_started'),
(7, 'RMD.5', 'إدارة الأداء', 'not_started'),
(7, 'RMD.6', 'السجلات', 'not_started'),
(8, 'BIA.1', 'التخطيط', 'not_started'),
(8, 'BIA.2', 'التدريب والتوعية', 'not_started'),
(8, 'BIA.3', 'إدارة دورة حياة البيانات', 'not_started'),
(8, 'BIA.4', 'إدارة الأداء', 'not_started'),
(8, 'BIA.5', 'السجلات', 'not_started'),
(10, 'DVR.1', 'التخطيط', 'not_started'),
(10, 'DVR.2', 'عملية تحقيق الإيرادات من البيانات', 'not_started'),
(10, 'DVR.3', 'المراقبة والصيانة', 'not_started'),
(10, 'DVR.4', 'إدارة الأداء', 'not_started'),
(11, 'OD.1', 'التخطيط', 'not_started'),
(11, 'OD.2', 'التدريب والتوعية', 'not_started'),
(11, 'OD.3', 'إدارة دورة حياة البيانات', 'not_started'),
(11, 'OD.4', 'إدارة الأداء', 'not_started'),
(11, 'OD.5', 'السجلات', 'not_started'),
(12, 'FOI.1', 'التخطيط', 'not_started'),
(12, 'FOI.2', 'التدريب والتوعية', 'not_started'),
(12, 'FOI.3', 'إدارة دورة حياة البيانات', 'not_started'),
(12, 'FOI.4', 'السجلات', 'not_started'),
(13, 'DC.1', 'التخطيط', 'not_started'),
(13, 'DC.2', 'ضوابط التصنيف', 'not_started'),
(13, 'DC.3', 'عملية التصنيف', 'not_started'),
(13, 'DC.4', 'إدارة الأداء', 'not_started'),
(13, 'DC.5', 'السجلات', 'not_started'),
(14, 'PDP.1', 'التخطيط', 'not_started'),
(14, 'PDP.2', 'التدريب والتوعية', 'not_started'),
(14, 'PDP.3', 'تسريب البيانات', 'not_started'),
(14, 'PDP.4', 'إدارة دورة حياة البيانات', 'not_started'),
(14, 'PDP.5', 'السجلات', 'not_started')
on conflict (control_code) do update set domain_id=excluded.domain_id, title_ar=excluded.title_ar;
