-- Reproducible baseline for the schema required by later CGP migrations.
-- Regulatory catalog rows are versioned in the framework-specific migrations.
begin;

create schema if not exists private;
revoke all on schema private from public;

create table if not exists public.frameworks (
  id bigint generated by default as identity primary key,
  code text not null unique default '',
  name_ar text not null,
  name_en text not null,
  version text not null,
  description_ar text default '',
  is_active boolean not null default true
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'control_owner' check (role in ('admin','cybersecurity_team','control_owner')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.controls (
  id bigint generated by default as identity primary key,
  framework_id bigint not null references public.frameworks(id),
  control_code text not null,
  title_ar text not null,
  description_ar text not null default '',
  domain_ar text not null,
  implementation_status text not null default 'not_started',
  evidence_status text not null default 'not_uploaded',
  verification_status text not null default 'not_verified',
  due_date date,
  last_review_date date,
  control_owner text,
  evidence_owner text,
  implementation_notes text,
  control_owner_id uuid references auth.users(id),
  unique (framework_id, control_code)
);

create table if not exists public.evidence (
  id bigint generated by default as identity primary key,
  control_id bigint not null references public.controls(id) on delete cascade,
  evidence_name text,
  description text,
  file_name text,
  file_path text,
  mime_type text,
  file_size bigint,
  status text default 'not_uploaded' check (status in ('not_uploaded','pending_review','under_review','accepted','rejected')),
  uploaded_at timestamptz,
  is_current boolean default true,
  reviewed_by text,
  reviewed_at timestamptz,
  review_notes text,
  submitted_at timestamptz
);

create table if not exists public.evidence_reviews (
  id bigint generated by default as identity primary key,
  evidence_id bigint not null references public.evidence(id) on delete cascade,
  decision text not null check (decision in ('accepted','rejected')),
  reviewer_name text,
  review_notes text,
  reviewed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.frameworks enable row level security;
alter table public.profiles enable row level security;
alter table public.controls enable row level security;
alter table public.evidence enable row level security;
alter table public.evidence_reviews enable row level security;

create or replace function private.current_user_role() returns text
language sql stable security definer set search_path='' as $$
  select p.role from public.profiles p
  where p.user_id = (select auth.uid()) and p.is_active = true limit 1;
$$;
revoke all on function private.current_user_role() from public, anon, authenticated;

create or replace function private.is_cgp_admin() returns boolean
language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.profiles p where p.user_id=(select auth.uid()) and p.is_active and p.role='admin');
$$;
revoke all on function private.is_cgp_admin() from public, anon, authenticated;

create or replace function public.is_cgp_admin_or_team() returns boolean
language sql stable security invoker set search_path='public' as $$
  select exists(select 1 from public.profiles p where p.user_id=auth.uid() and p.is_active and p.role in ('admin','cybersecurity_team'));
$$;
revoke all on function public.is_cgp_admin_or_team() from public, anon;
grant execute on function public.is_cgp_admin_or_team() to authenticated;

revoke all on public.frameworks, public.profiles, public.controls, public.evidence, public.evidence_reviews from anon;
grant select on public.frameworks, public.profiles, public.controls, public.evidence, public.evidence_reviews to authenticated;
grant update on public.profiles, public.controls to authenticated;
grant insert on public.evidence to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles for select to authenticated
using ((select auth.uid()) = user_id);
drop policy if exists "Admins can read all profiles" on public.profiles;
create policy "Admins can read all profiles" on public.profiles for select to authenticated
using ((select private.is_cgp_admin()));
drop policy if exists "Admins can update profiles" on public.profiles;
create policy "Admins can update profiles" on public.profiles for update to authenticated
using ((select private.is_cgp_admin())) with check ((select private.is_cgp_admin()));

drop policy if exists cgp_admin_team_update_controls on public.controls;
create policy cgp_admin_team_update_controls on public.controls for update to authenticated
using (public.is_cgp_admin_or_team()) with check (public.is_cgp_admin_or_team());

insert into storage.buckets (id, name, public, file_size_limit)
values ('evidence-files', 'evidence-files', false, 20971520)
on conflict (id) do update set public=false, file_size_limit=20971520;

commit;
