create table if not exists public.cybersecurity_projects (
  id bigint generated by default as identity primary key,
  project_code text not null unique,
  name_ar text not null,
  description_ar text,
  planned_year smallint not null check (planned_year between 2027 and 2029),
  planned_quarter text not null check (planned_quarter in ('Q1','Q2','Q3','Q4')),
  status text not null default 'planned' check (status in ('planned','in_progress','on_hold','completed')),
  priority text not null default 'medium' check (priority in ('high','medium','low')),
  executive_owner text,
  solution_scope text,
  framework_scope text,
  target_outcome text,
  actual_start_date date,
  target_end_date date,
  actual_end_date date,
  progress_percent numeric(5,2) not null default 0 check (progress_percent between 0 and 100),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cybersecurity_project_controls (
  project_id bigint not null references public.cybersecurity_projects(id) on delete cascade,
  control_id bigint not null references public.controls(id) on delete cascade,
  relationship_type text not null default 'coverage' check (relationship_type in ('primary','coverage','dependency')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (project_id, control_id)
);

create index if not exists cybersecurity_projects_schedule_idx on public.cybersecurity_projects (planned_year, planned_quarter, status);
create index if not exists cybersecurity_project_controls_control_idx on public.cybersecurity_project_controls (control_id);

alter table public.cybersecurity_projects enable row level security;
alter table public.cybersecurity_project_controls enable row level security;
revoke all on public.cybersecurity_projects, public.cybersecurity_project_controls from anon;
grant select, insert, update, delete on public.cybersecurity_projects, public.cybersecurity_project_controls to authenticated;
grant usage, select on sequence public.cybersecurity_projects_id_seq to authenticated;

create policy cybersecurity_projects_read on public.cybersecurity_projects
for select to authenticated using (
  (select private.current_user_role()) in ('admin','cybersecurity_team')
  or exists (
    select 1 from public.cybersecurity_project_controls link
    join public.controls control on control.id = link.control_id
    where link.project_id = cybersecurity_projects.id
      and (control.control_owner_id = (select auth.uid()) or private.can_external_auditor_view_control(control.id))
  )
);

create policy cybersecurity_projects_write on public.cybersecurity_projects
for all to authenticated
using ((select private.current_user_role()) in ('admin','cybersecurity_team'))
with check ((select private.current_user_role()) in ('admin','cybersecurity_team'));

create policy cybersecurity_project_controls_read on public.cybersecurity_project_controls
for select to authenticated using (
  (select private.current_user_role()) in ('admin','cybersecurity_team')
  or exists (
    select 1 from public.controls control
    where control.id = cybersecurity_project_controls.control_id
      and (control.control_owner_id = (select auth.uid()) or private.can_external_auditor_view_control(control.id))
  )
);

create policy cybersecurity_project_controls_write on public.cybersecurity_project_controls
for all to authenticated
using ((select private.current_user_role()) in ('admin','cybersecurity_team'))
with check ((select private.current_user_role()) in ('admin','cybersecurity_team'));

insert into public.cybersecurity_projects
(project_code,name_ar,planned_year,planned_quarter,status,priority,executive_owner,solution_scope,framework_scope,target_outcome,progress_percent,notes)
values
('R-01','برنامج الحوكمة والأدلة والامتثال',2027,'Q1','planned','high','مدير الامتثال','إطار إدارة الفجوات، تعيين ملاك الضوابط، مكتبة الأدلة','ECC / DCC / CSCC / CST','سجل فجوات معتمد وخطة أدلة',0,'تخطيط أولي — يعتمد قبل بدء التنفيذ'),
('R-02','برنامج الهوية والوصول المميز',2027,'Q2','planned','high','مدير الهوية والوصول','IAM / RBAC / MFA / PAM','ECC / DCC / CSCC / CST','تصميم وتنفيذ ضوابط الوصول',0,'تخطيط أولي — يعتمد قبل بدء التنفيذ'),
('R-03','برنامج حماية الشبكات والتقسيم',2027,'Q3','planned','high','مدير الشبكات','Firewall / Segmentation / NAC / DNS / DDoS','ECC / CSCC','خطة تقسيم وحماية شبكات معتمدة',0,'تخطيط أولي — يعتمد قبل بدء التنفيذ'),
('R-04','برنامج حماية وإدارة نقاط النهاية',2027,'Q3','planned','high','مدير البنية التحتية','EDR / MDM / Device Control / Patch','ECC / DCC / CSCC','تغطية نقاط النهاية وسياسة تحديثات',0,'تخطيط أولي — يعتمد قبل بدء التنفيذ'),
('R-05','برنامج المراقبة والاستجابة الأمنية',2027,'Q4','planned','high','مدير مركز العمليات الأمنية','SIEM / SOC / Logging / Threat Intelligence','ECC / CSCC / CST','مراقبة مركزية وإجراءات استجابة',0,'تخطيط أولي — يعتمد قبل بدء التنفيذ'),
('R-06','برنامج إدارة الثغرات والاختبارات',2028,'Q1','planned','high','مدير الأمن السيبراني','Vulnerability Management / VAPT / Sandbox','ECC / CSCC / CST','دورة معالجة ثغرات واختبارات دورية',0,'تخطيط أولي — يعتمد قبل بدء التنفيذ'),
('R-07','برنامج حماية البيانات والتشفير',2028,'Q2','planned','high','مالك حماية البيانات','DLP / Data Masking / Encryption / KMS','ECC / DCC / CSCC / CST','ضوابط حماية وتصنيف وتشفير بيانات',0,'تخطيط أولي — يعتمد قبل بدء التنفيذ'),
('R-08','برنامج أمن الخدمات السحابية',2028,'Q3','planned','medium','مدير البنية السحابية','CMDB / Cloud Logging / CSPM / Exit Strategy','CST / مراجع CCC في كتالوج المصدر','سجل أصول سحابية وضوابط تشغيلية',0,'يلزم توثيق إطار CCC الرسمي قبل القياس'),
('R-09','برنامج التعافي واستمرارية الأعمال',2028,'Q4','planned','high','مدير استمرارية الأعمال','Backup / DR / BCM','ECC / CSCC / CST','خطط تعافٍ واختبارات استعادة',0,'تخطيط أولي — يعتمد قبل بدء التنفيذ'),
('R-10','برنامج أمن التطبيقات والبريد',2029,'Q1','planned','medium','مدير التطبيقات','WAF / Email Security / HTTPS / Secure Architecture','ECC / CSCC','تحسين حماية التطبيقات والبريد',0,'تخطيط أولي — يعتمد قبل بدء التنفيذ'),
('R-11','برنامج التحسين المستمر والاعتماد',2029,'Q2','planned','medium','مدير الامتثال','مراجعات دورية / قياس / أدلة','كافة الأطر','دورة تدقيق وقياس التزام متكررة',0,'تحدد تواريخ التنفيذ الفعلية عند الاعتماد')
on conflict (project_code) do nothing;
