-- External auditors are deliberately scoped by framework and dates.
-- They may read only the controls and evidence that an administrator assigns.
begin;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
  check (role in ('admin', 'cybersecurity_team', 'data_governance_team', 'control_owner', 'nca_external_auditor'));

create table if not exists public.external_auditor_framework_scopes (
  id bigint generated by default as identity primary key,
  auditor_id uuid not null references public.profiles(user_id) on delete cascade,
  framework_id bigint not null references public.frameworks(id) on delete cascade,
  starts_on date not null default current_date,
  ends_on date not null,
  is_active boolean not null default true,
  created_by uuid not null default auth.uid() references public.profiles(user_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on >= starts_on),
  unique (auditor_id, framework_id)
);

create index if not exists external_auditor_scope_lookup_idx
  on public.external_auditor_framework_scopes (auditor_id, framework_id, starts_on, ends_on)
  where is_active;

alter table public.external_auditor_framework_scopes enable row level security;
revoke all on public.external_auditor_framework_scopes from anon;
grant select, insert, update, delete on public.external_auditor_framework_scopes to authenticated;

create policy external_auditor_scopes_admin_read on public.external_auditor_framework_scopes
  for select to authenticated using ((select private.current_user_role()) = 'admin');
create policy external_auditor_scopes_admin_create on public.external_auditor_framework_scopes
  for insert to authenticated with check ((select private.current_user_role()) = 'admin' and created_by = (select auth.uid()));
create policy external_auditor_scopes_admin_update on public.external_auditor_framework_scopes
  for update to authenticated using ((select private.current_user_role()) = 'admin')
  with check ((select private.current_user_role()) = 'admin');
create policy external_auditor_scopes_admin_delete on public.external_auditor_framework_scopes
  for delete to authenticated using ((select private.current_user_role()) = 'admin');

create or replace function private.can_external_auditor_view_framework(p_framework_id bigint) returns boolean
language sql stable security definer set search_path = '' as $$
  select (select private.current_user_role()) = 'nca_external_auditor'
    and exists (
      select 1
      from public.external_auditor_framework_scopes scope
      where scope.auditor_id = (select auth.uid())
        and scope.framework_id = p_framework_id
        and scope.is_active
        and scope.starts_on <= current_date
        and scope.ends_on >= current_date
    );
$$;
revoke all on function private.can_external_auditor_view_framework(bigint) from public, anon;
grant execute on function private.can_external_auditor_view_framework(bigint) to authenticated;

create or replace function private.can_external_auditor_view_control(p_control_id bigint) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.controls control
    where control.id = p_control_id
      and private.can_external_auditor_view_framework(control.framework_id)
  );
$$;
revoke all on function private.can_external_auditor_view_control(bigint) from public, anon;
grant execute on function private.can_external_auditor_view_control(bigint) to authenticated;

drop policy if exists cgp_controls_read on public.controls;
create policy cgp_controls_read on public.controls for select to authenticated using (
  (select private.current_user_role()) in ('admin', 'cybersecurity_team')
  or ((select private.current_user_role()) = 'control_owner' and control_owner_id = (select auth.uid()))
  or (select private.can_external_auditor_view_control(id))
);

drop policy if exists cgp_evidence_read on public.evidence;
create policy cgp_evidence_read on public.evidence for select to authenticated using (
  exists (select 1 from public.controls control where control.id = evidence.control_id)
);

drop policy if exists cgp_review_history on public.evidence_reviews;
create policy cgp_review_history on public.evidence_reviews for select to authenticated using (
  exists (
    select 1 from public.evidence evidence
    join public.controls control on control.id = evidence.control_id
    where evidence.id = evidence_reviews.evidence_id
  )
);

drop policy if exists cgp_frameworks_read on public.frameworks;
create policy cgp_frameworks_read on public.frameworks for select to authenticated using (
  (select private.current_user_role()) in ('admin', 'cybersecurity_team', 'control_owner', 'data_governance_team')
  or (select private.can_external_auditor_view_framework(id))
);

drop policy if exists cgp_file_read on storage.objects;
create policy cgp_file_read on storage.objects for select to authenticated using (
  bucket_id = 'evidence-files'
  and exists (select 1 from public.controls control where control.id::text = split_part(name, '/', 1))
);

commit;
