"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { requireProfile, type UserRole } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import { WorkflowHeading, WorkflowMetric } from "@/components/WorkflowUI";
import "./assets.css";

type Asset = { id:number; asset_code:string; name_ar:string; description:string|null; asset_type:string; business_owner:string; technical_owner:string|null; environment:string; data_classification:string; criticality:string; status:string; location:string|null; last_review_date:string|null; next_review_date:string|null; updated_at:string };
const typeLabels:Record<string,string>={application:"تطبيق",server:"خادم",database:"قاعدة بيانات",network:"شبكة",cloud_service:"خدمة سحابية",endpoint:"جهاز طرفي",ot_system:"نظام تشغيلي",social_account:"حساب تواصل اجتماعي",other:"أصل آخر"};
const envLabels:Record<string,string>={production:"إنتاج",staging:"تهيئة",testing:"اختبار",development:"تطوير",other:"أخرى"};
const classLabels:Record<string,string>={public:"عام",internal:"داخلي",confidential:"سري",restricted:"سري للغاية"};
const statusLabels:Record<string,string>={active:"نشط",maintenance:"تحت الصيانة",retired:"متقاعد",planned:"مخطط"};
const criticalityLabels:Record<string,string>={low:"منخفض",medium:"متوسط",high:"عالٍ",critical:"حرج"};
const dateToday=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Riyadh"});
const defaultForm={asset_code:"",name_ar:"",description:"",asset_type:"application",business_owner:"",technical_owner:"",environment:"production",data_classification:"internal",criticality:"medium",status:"active",location:"",last_review_date:"",next_review_date:""};

export default function AssetsPage(){
 const router=useRouter(); const [role,setRole]=useState<UserRole>("control_owner"); const [assets,setAssets]=useState<Asset[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState<Asset|null>(null); const [selected,setSelected]=useState<Asset|null>(null); const [search,setSearch]=useState(""); const [criticality,setCriticality]=useState("all"); const [form,setForm]=useState(defaultForm);
 async function load(){const {data,error}=await supabase.from("assets").select("*").order("criticality",{ascending:false}).order("name_ar");if(error)throw error;setAssets((data??[]) as Asset[])}
 useEffect(()=>{let live=true;(async()=>{try{const {profile}=await requireProfile(["admin","cybersecurity_team"]);if(!live)return;setRole(profile.role);await load()}catch(e){if(!live)return;const text=e instanceof Error?e.message:"";if(text.includes("تسجيل الدخول"))router.replace("/login");else if(text.includes("الصلاحية"))router.replace("/");else setError("تعذر تحميل سجل الأصول. تحقق من الاتصال ثم أعد المحاولة.")}finally{if(live)setLoading(false)}})();return()=>{live=false}},[router]);
 const visible=useMemo(()=>assets.filter(asset=>{const q=search.trim().toLowerCase();return (!q||[asset.asset_code,asset.name_ar,asset.business_owner,asset.technical_owner,asset.location].filter(Boolean).join(" ").toLowerCase().includes(q))&&(criticality==="all"||asset.criticality===criticality)}),[assets,search,criticality]);
 const due=assets.filter(a=>a.next_review_date&&a.next_review_date<dateToday()&&a.status==="active").length;
 function openCreate(){setEditing(null);setForm(defaultForm);setShowForm(true)}
 function openEdit(asset:Asset){setEditing(asset);setForm({asset_code:asset.asset_code,name_ar:asset.name_ar,description:asset.description||"",asset_type:asset.asset_type,business_owner:asset.business_owner,technical_owner:asset.technical_owner||"",environment:asset.environment,data_classification:asset.data_classification,criticality:asset.criticality,status:asset.status,location:asset.location||"",last_review_date:asset.last_review_date||"",next_review_date:asset.next_review_date||""});setShowForm(true)}
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");setMessage("");try{await requireProfile(["admin","cybersecurity_team"]);const payload={...form,description:form.description||null,technical_owner:form.technical_owner||null,location:form.location||null,last_review_date:form.last_review_date||null,next_review_date:form.next_review_date||null,updated_at:new Date().toISOString()};const result=editing?await supabase.from("assets").update(payload).eq("id",editing.id):await supabase.from("assets").insert(payload);if(result.error)throw result.error;await load();setShowForm(false);setEditing(null);setMessage(editing?"تم تحديث الأصل.":"تمت إضافة الأصل إلى السجل.")}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ الأصل.")}finally{setSaving(false)}}
 if(loading)return <main className="workflow-page assets-page" dir="rtl" role="status">جاري تحميل سجل الأصول…</main>;
 return <main className="workflow-page assets-page" dir="rtl">
  <WorkflowHeading title="سجل الأصول التقنية" description="قائمة جرد منظمة للأصول المعلوماتية والتقنية لدعم متطلبات إدارة الأصول والأمن السيبراني." action={<button className="workflow-button workflow-primary" onClick={openCreate}>+ إضافة أصل</button>}/>
  {error&&<p className="cgp-shell-error" role="alert">{error}</p>}{message&&<p className="workflow-success" role="status">{message}</p>}
  <div className="workflow-metrics"><WorkflowMetric label="إجمالي الأصول" value={assets.length}/><WorkflowMetric label="أصول حرجة" value={assets.filter(a=>a.criticality==="critical").length} tone="danger"/><WorkflowMetric label="في بيئة الإنتاج" value={assets.filter(a=>a.environment==="production").length}/><WorkflowMetric label="مراجعات مستحقة" value={due} tone={due?"warning":"neutral"}/></div>
  <section className="assets-guidance"><div><b>متطلب إدارة الأصول</b><p>احتفظ بقائمة محدثة، حدّد ملاك الأصول، وصنّف الحساسية والأهمية. راجع الأصول الحساسة دوريًا.</p></div><span>ECC · CSCC · CCC</span></section>
  {showForm&&<form className="asset-form" onSubmit={submit}><header><h2>{editing?"تحديث الأصل":"إضافة أصل جديد"}</h2><button type="button" onClick={()=>setShowForm(false)} aria-label="إغلاق النموذج">×</button></header><div className="asset-fields"><label>رمز الأصل<input required dir="ltr" value={form.asset_code} onChange={e=>setForm({...form,asset_code:e.target.value})} placeholder="AST-001"/></label><label>اسم الأصل<input required value={form.name_ar} onChange={e=>setForm({...form,name_ar:e.target.value})} placeholder="نظام الموارد البشرية"/></label><label>نوع الأصل<select value={form.asset_type} onChange={e=>setForm({...form,asset_type:e.target.value})}>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>مالك العمل<input required value={form.business_owner} onChange={e=>setForm({...form,business_owner:e.target.value})} placeholder="إدارة الموارد البشرية"/></label><label>المالك الفني<input value={form.technical_owner} onChange={e=>setForm({...form,technical_owner:e.target.value})} placeholder="فريق التطبيقات"/></label><label>البيئة<select value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}>{Object.entries(envLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>تصنيف البيانات<select value={form.data_classification} onChange={e=>setForm({...form,data_classification:e.target.value})}>{Object.entries(classLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>الأهمية<select value={form.criticality} onChange={e=>setForm({...form,criticality:e.target.value})}>{Object.entries(criticalityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>الموقع / نطاق الاستضافة<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="مركز البيانات أو مزود سحابي"/></label><label>آخر مراجعة<input type="date" value={form.last_review_date} onChange={e=>setForm({...form,last_review_date:e.target.value})}/></label><label>المراجعة القادمة<input type="date" value={form.next_review_date} onChange={e=>setForm({...form,next_review_date:e.target.value})}/></label><label className="wide">وصف الأصل<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="وظيفة الأصل والبيانات أو الخدمات التي يدعمها."/></label></div><footer><button disabled={saving} className="workflow-button workflow-primary">{saving?"جاري الحفظ…":"حفظ الأصل"}</button><button type="button" className="workflow-button" onClick={()=>setShowForm(false)}>إلغاء</button></footer></form>}
  <div className="workflow-filter workflow-filter-grid"><label>البحث<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="الاسم أو الرمز أو المالك أو الموقع"/></label><label>الأهمية<select value={criticality} onChange={e=>setCriticality(e.target.value)}><option value="all">جميع المستويات</option>{Object.entries(criticalityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
  <section className="assets-table-wrap"><table className="assets-table"><thead><tr><th>الأصل</th><th>النوع والبيئة</th><th>الملاك</th><th>التصنيف</th><th>الأهمية</th><th>المراجعة</th><th></th></tr></thead><tbody>{visible.map(asset=><tr key={asset.id} onClick={()=>setSelected(asset)}><td><b dir="ltr">{asset.asset_code}</b><strong>{asset.name_ar}</strong><small>{asset.location||"الموقع غير محدد"}</small></td><td>{typeLabels[asset.asset_type]}<small>{envLabels[asset.environment]}</small></td><td>{asset.business_owner}<small>{asset.technical_owner||"المالك الفني غير محدد"}</small></td><td><span className={"asset-class "+asset.data_classification}>{classLabels[asset.data_classification]}</span></td><td><span className={"asset-criticality "+asset.criticality}>{criticalityLabels[asset.criticality]}</span></td><td className={asset.next_review_date&&asset.next_review_date<dateToday()?"review-due":""}>{asset.next_review_date||"غير مجدولة"}</td><td><button type="button" className="asset-edit" onClick={event=>{event.stopPropagation();openEdit(asset)}}>تعديل</button></td></tr>)}</tbody></table>{!visible.length&&<p className="workflow-empty">لا توجد أصول مطابقة. أضف الأصل الأول لبدء سجل الجرد.</p>}</section>
  {selected&&<section className="asset-detail"><button type="button" onClick={()=>setSelected(null)} aria-label="إغلاق تفاصيل الأصل">×</button><span className="exec-eyebrow">تفاصيل الأصل</span><h2>{selected.name_ar} <b dir="ltr">{selected.asset_code}</b></h2><p>{selected.description||"لم يضف وصف لهذا الأصل بعد."}</p><div><span><b>مالك العمل</b>{selected.business_owner}</span><span><b>المالك الفني</b>{selected.technical_owner||"غير محدد"}</span><span><b>الحالة</b>{statusLabels[selected.status]}</span><span><b>آخر مراجعة</b>{selected.last_review_date||"غير محددة"}</span></div></section>}
 </main>
}