"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import "../data-governance.css";

type Request = { id:number; request_code:string; request_type:string; title_ar:string; business_owner:string; data_steward:string|null; status:string; created_at:string };
const types:Record<string,string>={data_sharing:"مشاركة بيانات",data_classification:"تصنيف بيانات",data_quality:"جودة بيانات",personal_data:"حماية بيانات شخصية",open_data:"بيانات مفتوحة",information_access:"طلب معلومات"};
const statuses:Record<string,string>={draft:"مسودة",submitted:"مقدم",steward_review:"مراجعة أمين البيانات",governance_review:"مراجعة الحوكمة",approved:"معتمد",returned:"معاد للاستكمال",rejected:"مرفوض"};

export default function DataRequestsPage(){
 const router=useRouter();const [rows,setRows]=useState<Request[]>([]);const [loading,setLoading]=useState(true);const [show,setShow]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [form,setForm]=useState({request_type:"data_sharing",title_ar:"",description:"",business_owner:"",data_steward:""});
 async function load(){const {data,error}=await supabase.from("data_governance_requests").select("id,request_code,request_type,title_ar,business_owner,data_steward,status,created_at").order("created_at",{ascending:false});if(error)throw error;setRows((data??[]) as Request[])}
 useEffect(()=>{let active=true;(async()=>{try{await requireProfile(["admin","data_governance_team"]);if(active)await load()}catch(e){router.replace(e instanceof Error&&e.message.includes("تسجيل الدخول")?"/login":"/")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[router]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");const {error}=await supabase.from("data_governance_requests").insert({request_code:"DG-"+Date.now(),...form,status:"submitted"});if(error){setError("تعذر حفظ الطلب. تأكد من الحقول ثم أعد المحاولة.");setSaving(false);return}setForm({request_type:"data_sharing",title_ar:"",description:"",business_owner:"",data_steward:""});setShow(false);await load();setSaving(false)}
 return <main className="dg-page" dir="rtl"><div className="workflow-heading"><div><span>سير العمل</span><h1>طلبات إدارة البيانات</h1><p>طلب موحد للمشاركة أو التصنيف أو الجودة أو الخصوصية، ويتجه تلقائيًا إلى أمين البيانات ثم فريق الحوكمة.</p></div><button className="workflow-button workflow-primary" onClick={()=>setShow(v=>!v)}>+ طلب جديد</button></div>
 {show&&<form className="asset-form" onSubmit={submit}><header><h2>تسجيل طلب إدارة بيانات</h2><button type="button" onClick={()=>setShow(false)} aria-label="إغلاق">×</button></header><div className="asset-fields"><label>نوع الطلب<select value={form.request_type} onChange={e=>setForm({...form,request_type:e.target.value})}>{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>مالك البيانات<input required value={form.business_owner} onChange={e=>setForm({...form,business_owner:e.target.value})}/></label><label>أمين البيانات<input value={form.data_steward} onChange={e=>setForm({...form,data_steward:e.target.value})}/></label><label className="wide">عنوان الطلب<input required minLength={3} value={form.title_ar} onChange={e=>setForm({...form,title_ar:e.target.value})}/></label><label className="wide">الوصف<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>{error&&<p role="alert">{error}</p>}<footer><button disabled={saving} className="workflow-button workflow-primary">{saving?"جاري الحفظ…":"إرسال للمراجعة"}</button></footer></form>}
 <section className="assets-table-wrap"><table className="assets-table"><thead><tr><th>الطلب</th><th>النوع</th><th>مالك البيانات</th><th>أمين البيانات</th><th>الحالة</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>جاري التحميل…</td></tr>:rows.length?rows.map(row=><tr key={row.id}><td><strong>{row.title_ar}</strong><small dir="ltr">{row.request_code}</small></td><td>{types[row.request_type]}</td><td>{row.business_owner}</td><td>{row.data_steward||"غير معين"}</td><td><span className="asset-class internal">{statuses[row.status]}</span></td></tr>):<tr><td colSpan={5}>لا توجد طلبات حالياً. ابدأ بتسجيل أول طلب.</td></tr>}</tbody></table></section></main>
}